### ISSUE TITLE
Cannot import AgentPubKeyB64 into DNA

### ISSUE THREAD

**Issue by zo-el** [holochain/holochain#1001]
Based on this Holochain rev `a1206a694fe3b521440fe633db99a50b8255c1b2` the `AgentPubKeyB64` is moved from `holo_hash` crate to `holochain_type`

And I am unable to build `holochain_type` in `wasm32` for the DNA.

My basic need from this issue is that we need to access AgentPubKeyB64 and other such b64's easily

**Comment by steveeJ** [comment]
copy and paste from chat

---

Here is a branch: https://github.com/holochain/hc-zome-lib/pull/5

To run you need to enter `nix-shell` then run `make build`

**Comment by timotree3** [comment]
It turns out this was just due to confusion with not importing the `"encoding"` feature of holo_hash. I think this can be safely closed

**Comment by zo-el** [comment]
Yes, we tested this out succesfully
