### ISSUE TITLE
proper shutdown of holochain

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#1013]
https://github.com/holochain/holochain/blob/12dfef0b2a710304697ddcd9ee731b4fe9933b0f/crates/holochain/src/bin/holochain/main.rs#L92

Since I would often find while spawning holochain as a subprocess that sending it a signal to kill it would not work, and the process would be left dangling, I wrote holochain-runner which is an alternative binary. 
For me, the ctrlc crate has worked well, with the feature called 'termination turned on which makes it call whatever shutdown handler you want when receiving the unix SIGTERM signal, and it also works a different way, but works on windows. 

Since there seems to be cleanup happening I thought I'd mention this. 

@thedavidmeister @freesig @maackle

**Comment by maackle** [comment]
@Connoropolous are you still using holochain-runner? can you link to it?

**Comment by Connoropolous** [comment]
hey @maackle yes we very much are. Acorn runs on it. 

Here's a related snippet where we handle SIGINT or SIGTERM or Ctrl-C in windows. 
https://github.com/lightningrodlabs/holochain-runner/blob/0d14ddeba16b18cf28d85295bf30a61a67b361b3/src/main.rs#L103-L121

There would often be an orphan process when we spawn `holochain` binary or `holochain-runner` binary from a nodejs thread and then attempt to shut it down, which is a really important use case.

Things are also better since I used the InProc lair-keystore process with it as well. Much easier to manage one child process from another language, instead of two, and the relationship between them.

**Comment by Connoropolous** [comment]
Closed in #1761

**Comment by Connoropolous** [comment]
Actually @maackle this is still an issue... 
instead of writing custom shutdown logic, you should use the conductor.shutdown() method, because the gossip processes are still running after you shutdown the other tasks

**Comment by Connoropolous** [comment]
https://github.com/holochain/holochain/blob/b4351eeef1b07885bd15e376fe1bc7d2a15aa647/crates/holochain/src/bin/holochain/main.rs#L117
