### ISSUE TITLE
`AdminRequest.ListAppInterfaces` times out in v0.0.112 with Rust 1.56

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#1067]
Other requests (for example `AdminRequest.AttachAppInterface`) works.

**Comment by freesig** [comment]
@guillemcordoba I'm unable to reproduce this problem. Can you give some more details of your setup?

**Comment by guillemcordoba** [comment]
Closing this as it has to do with Tauri's management of the UI interfering with @holochain/conductor-api. Sorry for the trouble.
