### ISSUE TITLE
Signals not working for particular agents in v0.0.109+ (launcher 0.3.4)

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#1069]
While using the Holochain Launcher, some agents get the signals from the conductor, some don't. It's not a matter of the UI that the application is running, the UI socket end doesn't actually receive anything.

At least me and David Richards (from Humm) are seeing this. Will update if I have more information on this.

**Comment by abe-njama** [comment]
@guillemcordoba We tried running tests to recreate this issue but couldn't find the issue with the latest versions of Holochain 
cc @freesig

**Comment by abe-njama** [comment]
@guillemcordoba checking back here. If the issue isn't being encountered anymore, can I proceed to close this issue?

**Comment by guillemcordoba** [comment]
Yeah let me close this for now.
