### ISSUE TITLE
delete_entry documentation is outdated ++ `delete` should take ChainTopOrdering also??

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#1071]
https://github.com/holochain/holochain/blob/63498e6231d7604d0f68d78d9d0a02892f9b61ff/crates/hdk/src/entry.rs#L74-L83

we are working on using ChainTopOrdering to improve performance in Acorn, but we can't specify ChainTopOrdering like we can for create and update, even though I believe it's relevant (and we get Head Moved errors when calling `delete_entry` in Acorn)

@thedavidmeister  thoughts on the ChainTopOrdering thing here?

**Comment by thedavidmeister** [comment]
@Connoropolous you are probably correct in that chain top ordering should work for deletes

**Comment by Connoropolous** [comment]
I'm guessing then it's going to be awkward to keep using the name `CreateInput`, now that it would be used across Create, Update, and Delete.

Anyways, would love to see that happen! Thanks

**Comment by maackle** [comment]
Fix forthcoming: https://github.com/holochain/holochain/pull/1213

**Comment by Connoropolous** [comment]
Sweet. We had to run our async client side calls in sequence not parallel to work around this.

**Comment by abe-njama** [comment]
@jost-s ChainTopOrdering works for Deletes courtesy of this PR #1213. You can proceed to update the documentation to reflect this change.

**Comment by abe-njama** [comment]
@Connoropolous all the associated fixes have been resolved. Please confirm if this now works and you can proceed to close the issue.
