### ISSUE TITLE
holochain Crash Report from running flux on Debian 11 

### ISSUE THREAD

**Issue by anaxareian** [holochain/holochain#1090]
[report-72e7d66d-f94c-483d-9136-184a19226802.txt](https://github.com/holochain/holochain/files/7470370/report-72e7d66d-f94c-483d-9136-184a19226802.txt)

Changed from .tom file to .txt so I could upload it here. 

This crash happened on my third startup.  I had started and properly closed the flux app twice before.

**Comment by maackle** [comment]
My guess is that you have specified an admin interface port in your `conductor-config.toml` which is already in use on your system. Can you check if that is the case?

**Comment by ThetaSinner** [comment]
@anaxareian did you get further with the suggestion above?
