### ISSUE TITLE
SysValidationError(CascadeError(DhtOpError(HeaderWithoutEntry error causes Auto Cell/App Shutdown

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#1101]
The context for this issue starts here, along with logs: 
https://github.com/h-be/acorn/issues/56#issuecomment-961989325

We are not sure, because there's no line numbers in the error reporting, which of these instances of HeaderWithoutEntry is the one which we are seeing: 
https://github.com/holochain/holochain/search?q=HeaderWithoutEntry
However, the one with a TODO left on it strikes me as suspicious:
https://github.com/holochain/holochain/blob/2f48c67e4244d66d86643525c230c5f0c1727aca/crates/holochain_state/src/query/live_entry.rs#L118

**Comment by freesig** [comment]
If this is where the bug is coming from it's definitely a bug because that is iterating over `Create` headers. I suspect it could be coming from somewhere else. I will look into this though.

**Comment by freesig** [comment]
Actually this could be an issue if there is private entries but I don't think it's the error you're hitting because your log says `Delete`

**Comment by Connoropolous** [comment]
thanks for looking into this. I defer my sensemaking to wiser authorities :) 
I can provide details, up to a certain level of precision, as to how the issue manifests though.

**Comment by freesig** [comment]
I've just put up a PR that should address this issue.

**Comment by zippy** [comment]
> I've just put up a PR that should address this issue.

Woot!
