### ISSUE TITLE
Problems with installation holochain in WSL

### ISSUE THREAD

**Issue by faha-berdiev** [holochain/holochain#1119]
Hi, everyone

I have problems with installation holochain to WSL, using that command `nix-shell https://nightly.holochain.love`

Installation guid: https://developer.holochain.org/install/#keeping-everything-local-working-offline

Can anyone help me please, how can I fix it? 

Thanks

![image](https://user-images.githubusercontent.com/62469844/141476968-a7a0154c-6ebf-485d-b1ff-b879330e5b1f.png)

**Comment by abe-njama** [comment]
Hi @faha-berdiev . Can you give me more details about your local machine? OS etc?

**Comment by f13end** [comment]
Hello @faha-berdiev. If the problem still persists, please let me know or you can give us details about machine.

**Comment by steveeJ** [comment]
closing this as there has been no answer from @faha-berdiev. please feel free to reopen this issue again and provide more information about your local machine.
