### ISSUE TITLE
wasmer_compiler_cranelift thrashes the logs on startup, with just RUST_LOG=info set

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#1173]
hundreds of these come through, this looks like it might have to be configured upstream at holochain-wasmer though

INFO wasmer_compiler_cranelift::translator::func_translator: translate(338 bytes, u0:898(i64 vmctx, i32, i32, i32, i32, i32, i32) system_v)

**Comment by freesig** [comment]
Yeh I'm aware of this. It's very annoying but we can't do anything about it as it's a dependency. I do have a plan to update the tracing logs to be able to exclude this module though
