### ISSUE TITLE
docs.rs docs have been broken since 0.0.118

### ISSUE THREAD

**Issue by mhuesch** [holochain/holochain#1175]
https://docs.rs/crate/holochain/0.0.121

apologies if this is known/tracked. I didn't find an issue in a cursory search.

fwiw, I am able to `cargo doc` 0.0.121 just fine in my local project.

**Comment by abe-njama** [comment]
@jost-s or @steveeJ mind taking a look at this?

**Comment by steveeJ** [comment]
this was closed prematurely. i assumed that https://github.com/holochain/holochain/pull/1194 would fix this but it didn't. we still have build errors for the docs: https://docs.rs/crate/holochain/0.0.124/builds

**Comment by jost-s** [comment]
I'm looking into it.

**Comment by jost-s** [comment]
> fwiw, I am about to `cargo doc` 0.0.121 just fine in my local project.
That command runs fine on my machine too. I ran it with v0.0.124 successfully.

The docs.rs README explains [how to build docs locally for testing](https://docs.rs/about/builds#testing-builds-locally). That command `cargo run -- build crate <CRATE_NAME> <CRATE_VERSION>` doesn't work on my machine. Error is "build is unexpected argument".

@steveeJ @thedavidmeister @freesig @neonphog I need some help, please.

**Comment by neonphog** [comment]
@jost-s - did you do the whole `docker-compose up` and you are in the checked out doc.rs repository directory (as opposed to holochain) and you get the "build is unexpected argument" error?

**Comment by steveeJ** [comment]
i don't think we need to replicate the entire docs.rs build suite. it's probably enough to run the following command in our repository:

```shell
nix-shell --arg rustVersion '{ track = "nightly"; version = "2021-12-01"; }' --pure --run "cargo clean; cargo doc -p holochain"
```

the nightly version here is based on the [first failing docs build that happened on holochain 0.0.118](https://docs.rs/crate/holochain/0.0.118/builds/471546).

**Comment by steveeJ** [comment]
maybe we do have to reproduce the entire docs.rs build environment. this is as close as i could get without much effort and it doesn't reproduce the build error:

```
$ nix-shell --arg rustVersion '{ track = "nightly"; version = "2022-01-20"; }' --pure --run "unset RUSTFLAGS; cargo rustdoc --lib --manifest-path=crates/holochain/Cargo.toml -- -Z unstable-options --check --cap-lints warn --disable-per-crate-search"
(...)
warning: unresolved link to `run_callback`
   --> crates/holochain/src/core/ribosome.rs:555:5
    |
555 | /     /// Helper function for running a validation callback. Just calls
556 | |     /// [`run_callback`][] under the hood.
557 | |     /// [`run_callback`]: #method.run_callback
    | |______________________________________________^
    |
    = note: the link appears in this line:

            [`run_callback`][] under the hood.
             ^^^^^^^^^^^^^^
    = note: no item named `run_callback` in scope
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: `holochain` (lib doc) generated 27 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 9.84s
```

**Comment by jost-s** [comment]
The issue has been fixed by the rustdoc team. Docs for `holochain` are built correctly again, starting with v0.0.126.
@mhuesch @steveeJ @abe-njama

**Comment by steveeJ** [comment]
![image](https://user-images.githubusercontent.com/1181362/155204189-c0010d7e-0345-4c44-9bfb-76ffc3c7c332.png)

confirmed :raised_hands:
