### ISSUE TITLE
Proposal that the compatible or most recent HDK version is included in the Release info

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#1301]
Just including the HDK version in this information. The rest of the related crates people could click through for. 

Rationale: this information is by far the most useful to happ developers.

Current framing:
<img width="1036" alt="Screen Shot 2022-03-20 at 2 48 20 PM" src="https://user-images.githubusercontent.com/1409121/159187398-e12ca592-9765-4d63-a6d8-a1c397a28bce.png">

**Comment by abe-njama** [comment]
Thanks for this suggestion @Connoropolous. I believe that this speaks to the usability of the top-level release notes so as to serve up the most useful information first.
@jost-s @steveeJ we could look at this as an extension or related item to #1241 or have a separate scope for it.

**Comment by jost-s** [comment]
@steveeJ Agreed, it's a nifty command and one possible solution to this use case. We should include it, in the installation instructions for example.

I'll add a task for me to do that.

**Comment by abe-njama** [comment]
Currently, the HDK and HDI version is being included in the release info to releases that are not pre-releases.

**Comment by ThetaSinner** [comment]
To find latest HDK version, use `holochain --build-info`

To find the min compatible version for a given Holochain version, this is a problem to be solved. This is what we want to refine on this ticket in a team meeting.
