### ISSUE TITLE
Crash when running holochain for the first time

### ISSUE THREAD

**Issue by Z2Up1UwcaYOyZq** [holochain/holochain#1333]
I tried to run holochain according to instructions in readme, it throws an error.

OS: Artix Linux
Holochain version: 0.0.132

1. `$ cargo install holochain`
2. `$ cargo install hc`
3. `$ holochain` 

```Apr 10 00:17:20.340 ERROR lair_keystore_client: error=IpcClientConnectError("/home/$USER/.local/share/lair/socket", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }) file="/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/lair_keystore_client-0.0.9/src/lib.rs" line=41
Apr 10 00:17:21.084 ERROR lair_keystore_client: error=Other(RecvError(())) file="/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/lair_keystore_client-0.0.9/src/lib.rs" line=53
   Updating crates.io index
   Installing lair_keystore v0.0.9
   Compiling autocfg v1.1.0
   Compiling libc v0.2.122
   [stuff compiling]
   Compiling rusqlite v0.26.3
   Finished release [optimized] target(s) in 4m 50s
   Replacing /home/$USER/.cargo/bin/lair-keystore
   Replaced package `lair_keystore v0.0.9` with `lair_keystore v0.0.9` (executable `lair-keystore`)
Apr 10 00:22:12.906 ERROR lair_keystore_client: error=Other(RecvError(())) file="/home/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/lair_keystore_client-0.0.9/src/lib.rs" line=70

```
[error log here](https://github.com/holochain/holochain/files/8457862/error2.txt)

**Comment by abe-njama** [comment]
@steveeJ could you take a look at this?

**Comment by steveeJ** [comment]
hey @Z2Up1UwcaYOyZq 

i see you slightly modified the instructions from the readme to install the versions published to crates.io.
in that case i assume you are not trying to build the latest code from the git repository.
i therefore suggest you follow the instructions at https://developer.holochain.org/install/ which is our recommended set up at the moment. in case you want to follow those instructions please reverse the installation you did previously by running

```shell
cargo uninstall holochain
cargo uninstall hc
cargo uninstall lair_keystore
```

please let me know either way, and also what your desired use-case is for installing holochain, i.e. are you trying to develop a hApp from scratch, use an existing one, etc.?

---

@jost-s WDYT about introducing a section in the readme that speaks to users who just want to use a released version of holochain? maybe we could also point towards the launcher, depending on whether they are looking to build a hApp or just use one.

**Comment by jost-s** [comment]
@steveeJ Yes, we can do that.
There's a need for a section or a page for using Holochain after installation, like the `hn-` commands and then using the launcher.
