### ISSUE TITLE
Handle error messages in startup panics gracefully

### ISSUE THREAD

**Issue by pospi** [holochain/holochain#1444]
**Describe the bug**

There are some libraries using a [(quite nice) pattern](https://github.com/holochain-open-dev/holochain-time-index/blob/ac8c9ba/src/lib.rs#L268) for statically reading DNA configuration at startup time.

Unfortunately the error message being sent with such assertions is being discarded by the runtime, making debugging configuration issues difficult (or impossible for complex configurations).

**Expected behavior**

Any `Err` value panicking should log the panic message as with other errors so that developers can more easily debug.

**Steps to reproduce**

Embed the library linked above without adding any of the indicated DNA properties, run the conductor with debug enabled and attempt to call a zome function within the embedding zome. You should see a generic "unreachable" error in the console.

For completeness, I am using `WASM_LOG=debug RUST_LOG=error RUST_BACKTRACE=1` in case additional verbosity is needed.

**Alternative resolution**

If this isn't possible for some technical reasons, recommendation for an alternative efficient configuration parsing pattern would suffice. In such a case we should probably also document this as a gotcha.

CC @jdeepee

**Comment by abe-njama** [comment]
@thedavidmeister please assist with your input on this issue. I thought this issue may have been related to this earlier fix; #1279 which ensured that the error is logged, but I could be mistaken in my assumption.
