### ISSUE TITLE
[BUG] Path::children_paths() panics

### ISSUE THREAD

**Issue by shanedeeodonnell** [holochain/holochain#1464]
**Describe the bug**
When `Path::children_paths()` is called, code panics with `Err(Serialize(Deserialize("invalid type: integer `100`, expected byte array")))`

Currently using hdk 0.0.136

**Expected behavior**
Return children paths.

**Steps to reproduce**
Create Path entries and then call `Path::children_paths()`

**Additional context**
The bug seems to have been introduced between hdk 0.0.125 and 0.0.126 on [this commit](https://github.com/holochain/holochain/commit/840342887fdf31d6258489514dc26951eea03af2#diff-5a7cec15e60c68129d12c257d1882e809d24592190481831b8f459905a921904R369)

**Comment by abe-njama** [comment]
@thedavidmeister mind taking a look at this reported issue and forming an opinion on it?

**Comment by abe-njama** [comment]
@shanedeeodonnell this issue could be caused by a version mismatch between the HDK and Conductor. From the reported issue it also points to an old version of HDK. Could you try to use the latest HDK (0.0.145) and inform us whether this issue is still recurring?

**Comment by ddd-mtl** [comment]
FWIW, I get panics in `children_path()` when I manually create paths and forgot to make them utf32.
I'd suggest making sure the path and its children were made correctly with utf32 strings.
