### ISSUE TITLE
InstalledCell shouldn't be deprecated?

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#1480]
https://github.com/holochain/holochain/blob/0c8865b034061980d82ea499fcff848f482b743e/crates/holochain_types/src/app.rs#L172

It is still returned by AppInfo requests. Also there is a TODO about role_id that is irrelevant

**Comment by maackle** [comment]
Yes, and #1547 makes further use of `InstalledCell`. So it will be un-deprecated.

**Comment by Connoropolous** [comment]
Great!
