### ISSUE TITLE
`hdk_entry` behaves strangely on structs w/ generic type params

### ISSUE THREAD

**Issue by mhuesch** [holochain/holochain#1484]
**Describe the bug**

`hdk_entry` behaves strangely on structs w/ generic type params.

**Expected behavior**

I would expect this to be an acceptable entry type:

```
#[hdk_entry]
pub struct Test<D>
    where D: std::fmt::Debug
{
    data: D,
}
```

**System information:**
 - OS: NixOS
 - Browser: irrelevant
 - Holochain and HDK Version (run `hn-introspect` as well as `holochain --build-info`
 from the nix shell and paste output):

```
List of applications and their version information

v0_0_143
- hc-0.0.41: https://github.com/holochain/holochain/tree/holochain-0.0.143
- holochain-0.0.143: https://github.com/holochain/holochain/tree/holochain-0.0.143
- kitsune-p2p-tx2-proxy-0.0.24: https://github.com/holochain/holochain/tree/holochain-0.0.143
- lair-keystore-0.0.10: https://github.com/holochain/lair/tree/v0.0.10

- rustc: rustc 1.60.0 (7737e0b5c 2022-04-04)
- cargo fmt: rustfmt 1.4.38-stable (7737e0b 2022-04-04)
- cargo clippy: clippy 0.1.60 (7737e0b 2022-04-04)
- perf: mirror://kernel/linux/kernel/v5.x/linux-5.10.118.tar.xz
```

**Steps to reproduce**

create a hApp and define the above struct / entry type.

observe output when building:

```
  --> crates/common/src/lib.rs:59:12
   |
59 | pub struct Test<D>
   |            ^^^^ expected 1 generic argument
   |
note: struct defined here, with 1 generic parameter: `D`
  --> crates/common/src/lib.rs:59:12
   |
59 | pub struct Test<D>
   |            ^^^^ -
help: add missing generic argument
   |
59 | pub struct Test<D><D>
   |            ~~~~~~~

For more information about this error, try `rustc --explain E0107`.
error: could not compile `common` due to previous error
```

**Comment by Connoropolous** [comment]
The lack of generics for entries is, sadly, what led me down the path of macro-ization in hdk_crud library . David Meister, if Iremember correctly, told me when they wouldn't support it as it didn't make sense. If I recall more I'll share

**Comment by mhuesch** [comment]
ah, thx @Connoropolous. I imagine it has to do with difficulty in consistently deserializing an arbitrary-sized generic term in a struct/enum... however I'd be curious about the specific issue which makes this unworkable, as I know that e.g. Haskell's [binary](https://hackage.haskell.org/package/binary-0.8.9.0/docs/Data-Binary.html) can do the equivalent thing. but there are of course a bunch of differences between generics in Rust & Haskell.

will close this.
