### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Gkhanm** [holochain/holochain#1541]
**Describe the bug**
A clear and concise description of what the bug is, how you encountered it, and
the text of any error you received.

**Expected behavior**

**System information:**
 - Holochain and HDK Version (run `hn-introspect` as well as `holochain --build-info`
 from the nix shell and paste output)

**Steps to reproduce**
For isolating the bug, it is helpful to see a failing test or a repo that
reproduces the bug in a fresh hApp. Some suggestions for methods
of writing a reproduction of a bug:

- Write a failing test with [Sweettest](https://docs.rs/holochain/latest/holochain/sweettest/index.html)
- Write a failing test with [Tryorama](https://github.com/holochain/tryorama/)
- Create a minimal reproduction project using `hn-init` and add the code that
produces the bug.

**Screenshots**

**Additional context**

**Comment by abe-njama** [comment]
@Gkhanm looks like you didn't report any issue. What's been submitted is just the Bug Template. I'm going to close this for now, but please do use the template to submit any other issues that you may be encountering.
