### ISSUE TITLE
CHANGELOG file has grown too large to load

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#1567]
The CHANGELOG file is having a hard time loading in the browser, due to its length and size.

<img width="1680" alt="Screen Shot 2022-09-09 at 5 40 28 PM" src="https://user-images.githubusercontent.com/1409121/189461906-0429895c-2639-4f11-9b7d-5e3139faf2e4.png">

**Comment by Connoropolous** [comment]
sometimes now I am also just getting the magic unicorn

**Comment by abe-njama** [comment]
I've taken note of this as I'm encountering the same. We'll look into it.

**Comment by abe-njama** [comment]
@Connoropolous The Changelog view is now back up. Strangely, nothing was changed or fixed to make it work. We'll monitor this in case the issue recurs.
<img width="1208" alt="Screenshot 2022-09-13 at 20 51 55" src="https://user-images.githubusercontent.com/62102332/189974831-750acb4a-8e12-4f3a-aba1-00572986a591.png">
