### ISSUE TITLE
Potential License Infringement?

### ISSUE THREAD

**Issue by FollowTheProcess** [holochain/holochain#1655]
Hey all,

Just noticed on my GitHub feed this morning that a new person as followed me and seems to have claimed(?) ownership of this project under their own name (with no obvious fork or attribution). Not sure if this is okay or not? Normally I see the "forked from" in GItHub and it's not present here so not sure how they've got it on their profile.

I'm not overly familiar with the license you guys use but this seems like this probably breaches it, just raising it here so you're aware: https://github.com/SuperButterfly/Holochain. Could be an innocent mistake (not knowing how to fork maybe?)

**Comment by abe-njama** [comment]
Thanks for raising this @FollowTheProcess. We will look into this further.

**Comment by maackle** [comment]
Interesting, looks like they also re-wrote the git history to replace @freesig's contributions under their own name. Definitely suspect. https://github.com/SuperButterfly/Holochain/graphs/contributors

**Comment by freesig** [comment]
Can confirm that's not me. I didn't even know that was possible

**Comment by maackle** [comment]
I create [an issue](https://github.com/SuperButterfly/Holochain/issues/1) on the offending repo months ago, and there has been no response. Unless anyone wants to elevate this to GitHub itself, I say we forget about this and close this issue.
