### ISSUE TITLE
[BUG] Code-signing on macOS makes Holochain crash on some systems during execution

### ISSUE THREAD

**Issue by lucksus** [holochain/holochain#1699]
**Describe the bug**
We are seeing weird crashes of Holochain on macOS with code-signed holochain binaries. 
These crashes are weird for two reasons:

1. It's only happening on some systems - on some it's working. At first it seemed as though the problem was macOS <12 but we also found version 12 macOS systems where this happens (while on some there is no problem). Good thing is, it reliably crashes in our Github CI (see below).

2. Although "Code signature invalid" is mentioned in the crash report, the crash doesn't happen when loading the holochain executable, but at some point when/after installing a DNA.

We have a CI run here with the crash report printed out at the end: https://github.com/perspect3vism/ad4m/actions/runs/3618718752/jobs/6098904343

Interesting items of the crash report:
```
System Integrity Protection: enabled

Crashed Thread:        1  holochain-tokio-thread

Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x000000010c7dfa80
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2
```

Looking at the stack of the crashed thread I see this:

```
Thread 1 Crashed:: holochain-tokio-thread
0   ???                               0x000000010c7dfa80 0 + 4504550016
1   holochain                         0x000000010af455d2 wasmer_register_setjmp + 82
2   holochain                         0x0000000109bc0871 wasmer_vm::trap::traphandlers::tls::set::hc5100b79d184f168 + 129
3   holochain                         0x000000010976065a wasmer_vm::trap::traphandlers::wasmer_call_trampoline::h275fd334cf24c213 + 138
4   holochain                         0x0000000109cb5f69 wasmer::sys::native::NativeFunc$LT$$LP$$RP$$C$Rets$GT$::call::h0e00d05d0c7c671a + 169
```

**Expected behavior**
If there was be a problem with the code-signature, the binary wouldn't even start.
If it does run on a system after being correctly signed, it should work.

**System information:**
 - OS: macOS
 - Holochain version: seen on 0.0.161 and 0.0.174

**Steps to reproduce**
* get or build holochain binary
* confirm that it works
* use Apple developer account and developer certificate to sign and notarise holochain binary
```
codesign --deep --force --options=runtime  --sign "<ID of your certifcate>" --timestamp ./holochain
...zip binary(ies) into Archive.zip...
xcrun notarytool submit ./Archive.zip --keychain-profile "<your keychain profile for keychain passwords>" --wait  --password "<your keychain password id / or verbatim password>" --apple-id "<your Apple developer account>" 
```
* confirm binary still works on your machine
* try running this signed binary on other machines

**Additional context**
I can't tell if this is a problem with Apple's code-signing infrastructure, or with the way we're using it, or with Holochain.

BUT, the last frame in the crashing call-stack (`0   ???                               0x000000010c7dfa80 0 + 4504550016`) makes me wonder, is this actually "just" a bad memory access, that might be handled differently (by macOS) when the executable was code-signed? Is there an exeception/signal that might be handled by the code normally, but since it is now running as a code-signed binary, that situation doesn't trigger the same signal and gets caught by macOS's gatekeeper...?

**Comment by lucksus** [comment]
I might have found the solution myself. Tested and documented here: https://github.com/perspect3vism/ad4m/pull/135
Will run some more tests on other machines where it was failing before, but the fact that our CI on this PR is green is great since it was failing with above problem before consistently.

**Comment by lucksus** [comment]
Yes, we confirmed today that we don't see crashes anymore with that fix. I'll summarise here:

Wasmer is doing JIT compiling which means writing to and thus changing the process' code in run-time which breaks the signature, if the JIT entitlement is not set.

To set it we need to provide a .plist file like so:
```xml
<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"> <plist version="1.0"> <dict>
	<key>com.apple.security.cs.allow-jit</key>
	<true/>
	<key>com.apple.security.cs.allow-unsigned-executable-memory</key>
	<true/>
</dict>
</plist>
```

And then provide when running the signing command:
```
codesign --deep --force --options=runtime  --sign "<YOUR CERTIFICATE ID>" --timestamp --entitlements entitlements.plist ./holochain
```

**Comment by Connoropolous** [comment]
ah interesting. the reason we don't see that with Acorn is that bundling with Electron (when bundling with electron-builder) automatically provides that entitlement. 
https://github.com/electron-userland/electron-builder/issues/4385
