### ISSUE TITLE
When are 'unprovisioned' cells coming

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#1738]
For Acorn to adopt a pattern of cloning for adding projects we need to have the ability to start with 0 projects, which means having, as I understand it, an unprovisioned cell. Any ETA on when those may make it in? Is that a in-Beta or post Beta feature?

**Comment by maackle** [comment]
We're reviving the design of cell provisioning and working out some details, and then we can get this implemented.

What we can do relatively soon is implement `deferred: false`, which gives the option to install the base cell at a later time, as well as what's currently known as the `Disabled` provisioning strategy (probably to be renamed), which will never provision a base cell, giving only the option for clone cells.

**Comment by Connoropolous** [comment]
nice. Disabled will be useful for Acorn

**Comment by maackle** [comment]
FYI here's the first step of this https://github.com/holochain/holochain/pull/2243
