### ISSUE TITLE
[Feature Request] add ability to define admin websocket port with `hc` sandbox

### ISSUE THREAD

**Issue by pospi** [holochain/holochain#1745]
Currently there is no way to specify the admin websocket as there is with the app socket, it's assigned randomly.

This makes local development of some hApps (which don't run through the conductor) awkward since the admin socket URI has to be pulled from the log output and manually specified when running the hApp frontend.

**Additional context**

https://github.com/h-REA/hREA/pull/376/commits/bfed96dd74d700e7e613156f2794c6b403898827

**Comment by pospi** [comment]
CC @Connoropolous

**Comment by Connoropolous** [comment]
Aha there is, just hard to find
https://github.com/holochain/holochain/blob/c085bd47532e4bc58f4f317b4ce12e08ad9a412e/crates/hc_sandbox/src/cli.rs
