### ISSUE TITLE
Include event macros in hdi crate

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain#1860]
Thanks for your great work! Just a small request: I would love to be able to use macros `warn!()`, `debug!()`, and `info!()` from integrity zomes.

**Comment by mattyg** [comment]
For anyone who discovers this, you just have to enable the feature flag "trace" for the hdi crate by importing it with

 ```hdi = { version = "0.2.0" features = ["trace"] }```

**Comment by guillemcordoba** [comment]
Oh interesting. @thedavidmeister why isn't "trace" a feature enabled by default?
