### ISSUE TITLE
[BUG] Same clone can be installed arbitrarily many times

### ISSUE THREAD

**Issue by matthme** [holochain/holochain#1969]
**Describe the bug**
It looks like the exact same clone with the same DNA hash and under the same public key can be installed arbitrarily many times.
This should obviously not be allowed as it is a source chain fork.

**Expected behavior**
The conductor returns an error if a clone of the given DNA hash is already installed.

**Steps to reproduce**
Install a clone. Install the same clone again.

**Screenshots**
![image](https://user-images.githubusercontent.com/36768177/219947571-e500a871-e88e-4e84-87ec-d69adda1a194.png)

**Comment by abe-njama** [comment]
@matthme This bug is now fixed courtesy of #1997
