### ISSUE TITLE
[BUG] Network seed is not changing the DNA hash when source is `AppBundleSource::Bundle(AppBundle)`

### ISSUE THREAD

**Issue by mjbrisebois** [holochain/holochain#2039]
**Describe the bug**
Installing an app using `bundle` instead of `path` results in the same DNA hash even when `network_seed` is also provided.

**Expected behavior**
I expect that providing a `network_seed` will always change the DNA hash regardless of the app source used.

**System information:**
 - OS: ubuntu 22.04
 - Holochain v0.1.0 

**Steps to reproduce**
When installing an app using [`AppBundleSource::Bundle(AppBundle)`](https://github.com/holochain/holochain/blob/develop/crates/holochain_types/src/app.rs#L154) and a `network_seed` the network seed is ignored.  The DNA hash is the same as without the network seed.

#### Call 1 - bundle without network seed

```js
{
    "installed_app_id": "appstore-alice",
    "agent_key": "uhCAkU9Lo-H0vGzZNWB7116BpborSAItxYq8DDTHFaStSyEaBYxGh",
    "membrane_proofs": {},
    "network_seed": null,
    "bundle": {
        "manifest": {
            "manifest_version": "1",
            "name": "appstore",
            "roles": [
                {
                    "name": "appstore",
                    "dna": {
                        "path": "/projects/app-store-dnas/bundled/appstore.dna"
                    }
                },
                {
                    "name": "portal",
                    "dna": {
                        "path": "/projects/app-store-dnas/bundled/portal.dna"
                    }
                }
            ]
        },
        "resources": {}
    }
}
```

Portal DNA hash == `uhC0knmUIHLo7p1XORNSHReovyinmj7WmRGef82nyoUvzDt2LJZRT` (correct)

#### Call 2 - bundle with network seed

```js
{
    "installed_app_id": "appstore-alice",
    "agent_key": "uhCAknz5iK5FFMKn_v9RTmfo3wgrDWKipUUiRkG3UH-t9GhWKaUP7",
    "membrane_proofs": {},
    "network_seed": "test-network",
    "bundle": {
        "manifest": {
            "manifest_version": "1",
            "name": "appstore",
            "roles": [
                {   
                    "name": "appstore",
                    "dna": {
                        "path": "/projects/app-store-dnas/bundled/appstore.dna"
                    }
                },
                {   
                    "name": "portal",
                    "dna": {
                        "path": "/projects/app-store-dnas/bundled/portal.dna"
                    }
                }
            ]
        },
        "resources": {}
    }
}
```

Portal DNA hash == `uhC0knmUIHLo7p1XORNSHReovyinmj7WmRGef82nyoUvzDt2LJZRT` (incorrect)

#### Call 3 - path with network seed

```js
{
    "installed_app_id": "appstore-alice",
    "agent_key": "uhCAkjDQY6E7heEv8iF2f7lB-tYnfQ5iGvdxyc39xomAAlLTrFQx7",
    "membrane_proofs": {},
    "network_seed": "test-network",
    "path": "/projects/app-store-dnas/appstore.happ"
}
```

Portal DNA hash == `uhC0kWQfOGS-ruIu-mOu_BC4yns-xhcCrahinLpPpVuunOGqrLLBL` (correct)

The hash from call 2 should be the same as call 3.

**Comment by maackle** [comment]
@mjbrisebois I tried to reproduce this with Sweettest, but the test passes. Can you have a look and see if this covers your case? https://github.com/holochain/holochain/pull/2102/files#diff-49d6b93c91c1c50fddc09ed5c9db70676e39c167192bc46d1219b71fd62ceb58R134-R275

If not can you modify it or point out how it could be modified? And if so, I may have to try testing at a higher level using the websocket interface. Perhaps you can also show your reproduction.

**Comment by mjbrisebois** [comment]
@maackle The only difference I can see is that you have the DNA bytes in the resources section, but my failing hApp input uses a file path reference.

[This](https://github.com/holochain/app-store-dnas/blob/master/tests/e2e/test_multiple.js) is what I was writing when the issue popped up.  The part where I install App Store (https://github.com/holochain/app-store-dnas/blob/master/tests/e2e/test_multiple.js#L438) used to be the bundled input, but when I added network seeds it had to be switched to a file path to make it work.

I captured all the example inputs by putting a console log right before the conductor admin client call so that I could be sure the network seed isn't getting missed somewhere on the client-side.

**Comment by mjbrisebois** [comment]
@maackle I was able to reproduce the error with a minimal script - https://github.com/mjbrisebois/tmp-reproduction-holochain-network-seed-error/blob/master/test.js

The final install fails with `CellAlreadyExists` due to the issue.  It should have created unique cells with the same DNA hashes as the 2nd install command.

**Comment by maackle** [comment]
Thank you! I can work with this.

**Comment by maackle** [comment]
I'm having a hard time reproducing this! It might be overkill, but I wrote [a test](https://github.com/holochain/holochain/pull/2102/files#diff-49d6b93c91c1c50fddc09ed5c9db70676e39c167192bc46d1219b71fd62ceb58R139) that attempts to explore every possible combination of ways that network seeds can be set (3 different levels: in the DNA manifest, in the App manifest, and passed during InstallApp), and every combination of Path and Bundle (DNA specified by path/bundle in the role, App specified by path/bundle in the InstallApp call). And this test passes!

It includes your failing case too ("A-None-None-Bundle-Path").

Just a progress update since I've been scratching my head on this for a day. I guess I will have to take a step back and examine more carefully why my test case doesn't match yours. I'm able to get a failure when running your test.

**Comment by mjbrisebois** [comment]
My reproduction nix-shell is using beta 1, so I thought maybe it got fixed since then, but it failed the same using beta 2rc1

**Comment by maackle** [comment]
Finally fixed it: https://github.com/holochain/holochain/pull/2102

The bug is that when `provisioning` is `None`, the network seed does not get updated. Turns out it had nothing to do with the bundle/path source, other than that apparently the `None` was getting properly resolved to `Create` in one and not the other.

**Comment by mjbrisebois** [comment]
Excellent!  Those subtle diffs can be so hard to find, thanks :+1:
