### ISSUE TITLE
[BUG] Tauri environment does not support dynamic `CSSStyleSheet` construction

### ISSUE THREAD

**Issue by pospi** [holochain/holochain#2056]
**Describe the bug**

Modern TypeScript / Rollup configs are by default configured to compile CSS module exports using `CSSStyleSheet` instances and specialised syntax. Tauri throws an "illegal constructor" error upon encountering these, which crashes application initialisation entirely. Odd because [support for this](https://caniuse.com/mdn-api_cssstylesheet_cssstylesheet) seems at least reasonably mature.

**Expected behavior**

`new CSSStyleSheet()` to not cause an error.

**System information:**
 - OS: Ubuntu
 - Holochain and HDK Version (run `hn-introspect` as well as `holochain --build-info`
 from the nix shell and paste output)
 
    holochain (holochain 0.1.3): ed5b7bb461c2a8bfd4d2633bad604a20b8f2da03
    lair-keystore (lair_keystore 0.2.3): cbfbefefe43073904a914c8181a450209a74167b
    hc-launch (holochain_cli_launch 0.0.11): 3bcd14e81cda07e015071b070c2ef032aa1d1193
    hc-scaffold (holochain_scaffolding_cli 0.1.7): 8bf000b4a8c79352633d21bfdd8fa46e27bd479f

**Steps to reproduce**

See [this repository, at this version](https://github.com/pospi/neighbourhoods-css-styles/tree/6ad0dea). If the [commented trailing syntax](https://github.com/pospi/neighbourhoods-css-styles/blob/6ad0deadac770c603a0ee2d15ac4b85ccef27585/index.ts#L2) in `index.ts` is removed, the compiled module will cause a running Tauri window to throw an error and halt script interpretation immediately.

Maybe future Tauri updates will solve this one?

**Comment by matthme** [comment]
I ported this issue over to the Launcher repository https://github.com/holochain/launcher/issues/143 where `holochain_cli_launch` is maintained. It can probably be closed here in the main repo.
