### ISSUE TITLE
[BUG - HOLONIX] Build error libsqllite for sweetest dependencies

### ISSUE THREAD

**Issue by nphias** [holochain/holochain#2222]
**Describe the bug**
adding _holochain test_utils_ and _fixt_ as a dependencies (for sweetest) in Cargo.toml without adding `resolver ="2" `
in the workspace section results in a build error: 
failed to run custom build command for libsqlite3-sys v0.25.2

**Expected behavior**
Either an error message pre-build saying that `resolver ="2" ` is required in the root Cargo.toml file, or the build to work (nix develop)

**System information:**
 - OS: [macOS 12, Ubuntu Linux 22.04]
 - Nix version: (`2.13.3`)

**Steps to reproduce**
Scaffold any project and add sweetest dependencies
then `nix develop` to compile and build

**Screenshots**
![error_sqlite_hc](https://user-images.githubusercontent.com/17417820/231777566-3678a9c5-1e96-4829-8f14-6ed1ef98d810.png)

**Comment by ThetaSinner** [comment]
Hi @nphias. Just given this a go on my laptop (osx 13, m1) and haven't run into the issue so I'm hoping we can try to nail down the reproduction scenario.

- I'm running the same nix version
- I've created a new project using the scaffolding tooling (`nix run github:holochain/holochain#hc-scaffold`)
- I've added `holochain = { version = "0.2.0-beta-rc.3", features = [ "fixt", "test_utils" ] }` to the `[workspace.dependencies]` in the `Cargo.toml` at the root of the project (next to the `flake.nix`)
- All of the following commands work for me `cargo build`, `cargo build --release`, `npm start`

I don't see a dependency on sqlite which is likely part of the problem. Have you configured a feature I'm missing on the `holochain` dependency or anything like that?

**Comment by harlantwood** [comment]
@ThetaSinner thanks for your response.  

I ran into this while adding sweettest to deepkey a few days ago.  Here’s my branch:

https://github.com/harlantwood/deepkey/commits/chore/sweettest

Specifically at this commit  https://github.com/harlantwood/deepkey/commit/8ce16152f59a0db816bda16446536db1533dad77 I had the described failure on my mac m1 within ‘nix develop’ shell when running ‘pnpm install && pnpm test:sweet’

**Comment by ThetaSinner** [comment]
A couple of changes have gone in which should solve these issues. `resolver = "2"` is still recommended but the next release on 0.1 (which will be 0.1.5) adds a new feature `sweetest` which hides these details. You should be able to consume holochain without default features and just that feature flag for this use case.

**Comment by ThetaSinner** [comment]
This has all released now, I will close this issue and we can start a new one if there are any problems integrating these changes
