### ISSUE TITLE
[Enhancement] Standarize macro names for integrity type definitions

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain#2403]
Actually this is one of the first quirks I felt about holochain when I was first learning it. I thought I was missing something, but now I've realized it's just a historical quirk of the implementation:

We should standardize the macro names `hdk_entry_defs` and `hdk_link_types` -- either they're both named `_defs` or both named `_types`. 

I personally like `_types` better.

**Comment by ThetaSinner** [comment]
It also took me a bit of time to figure out that these are both referring to application defined types. I'd also be happy with `_types` as the common name
