### ISSUE TITLE
[Enhancement] Macro to simplify deserializing expected dna properties and expose to hdk extern

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain#2405]
This is more of an ergonomic "nice to have" than a real pain-point. 

I find that in almost every zome I write I need to create a struct `MyDnaProperties`, a helper function to deserialize the `dna_info()?.properties` into the expected format and expose it to my frontend.

It would be very nice to have a macro to annotate a DnaProperties struct with such that it generates an hdk_extern function get_dna_properties() that does this work for us.

I also wonder if this really belongs in the integrity zome since dna properties are part of the DNA hash, and thus the expected structure of the dna properties seems like it should be a breaking change.

**Comment by ThetaSinner** [comment]
I've just had to use properties in a test wasm and it's a fiddle, I'd like to take a look at this

**Comment by ThetaSinner** [comment]
Oh my mistake, there's an open PR for this already, I will take a look at that instead

**Comment by ThetaSinner** [comment]
Back-ported in https://github.com/holochain/holochain/pull/3115
