### ISSUE TITLE
[Enhancement] [Discussion] Split `get` into `get_from_action` and `get_from_entry`

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain#2408]
I'm not convinced this is the right idea, but I wanted to surface it anyway. It always felt like quite a "gotcha" that we have one `get()` function that behaves differently depending on if you pass in an ActionHash or an EntryHash.

Should we move away from this pattern by adding aliases for `get_from_action()` and `get_from_entry()`? Then we can clearly differentiate when we're getting *the* action + *the* entry versus *some* action + *the* entry.

I mean I like that the function name is very short and sweet, maybe another option would be to keep `get()` for just actions and add `get_from_entry()` as the best-practice for getting a record from entry hash.

**Comment by mattyg** [comment]
moved to github discussions: https://github.com/holochain/holochain/discussions/2410

**Comment by ddd-mtl** [comment]
I'd probably agree 3/4 years ago, but I got used to `get()` now.
I don't feel this adds much at this stage. I'd prefer a stable API for now.

**Comment by mattyg** [comment]
> I'd probably agree 3/4 years ago, but I got used to `get()` now.
> I don't feel this adds much at this stage. I'd prefer a stable API for now.

I hear that but I'd also just note that I expect (hope) that the holochain devs active today are 0.00001% of all the devs that will be learning the framework over the next several years, so our pain points in learning are really good feedback to make it easier for everyone else.
