### ISSUE TITLE
this log seems misleading or wrong (but I could be wrong!)

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#2433]
https://github.com/holochain/holochain/blob/7d2607ce21610f6e636b9eb23c0256e7bc026215/crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs#L43-L46

this log gives the impression of publishing to nodes, but I get the impression reading the source that it relates to a set of data that SHOULD be published to nodes. 
Can I get a pair of eyes on this?

This is based on my reading of `publish_dht_ops_workflow_inner`

**Comment by Connoropolous** [comment]
https://github.com/holochain/holochain/blob/7d2607ce21610f6e636b9eb23c0256e7bc026215/crates/holochain/src/core/workflow/publish_dht_ops_workflow.rs#L106-L118

**Comment by Connoropolous** [comment]
cc @maackle

**Comment by ThetaSinner** [comment]
I've approved the PR because it looks right to me but it's probably worth letting @maackle give this a check

**Comment by Connoropolous** [comment]
@maackle previously confirmed with me in a DM. Ill share a screenshot

**Comment by ThetaSinner** [comment]
Ahh perfect, in that case please feel free to go ahead with merging the PR

**Comment by maackle** [comment]
Correct!
