### ISSUE TITLE
Request to add some path functionality into HDI

### ISSUE THREAD

**Issue by alastairong** [holochain/holochain#2519]
**Describe the bug**

This was a question to Guillem and he asked me to file it with Holochain team.
In my app I need to create a link based on the content of the target entry. For example: 

```
let badge = Badge {
    name: "Alastair",
    location: "London",
    ...
  }; 

let action_hash = create_entry(EntryTypes::Badge(badge.clone()))?;
let anchor_str = format!("{}{}", badge.name, badge.location);;
let anchor = Path::from(&anchor_string).path_entry_hash()?
create_link(
    anchor, 
    action_hash,        
    None,
    None,
)?;
```
In validation I would like to check that the link anchor is in fact the correct one for the badge. So something like...

```
let link_base = // get link base

    let link_target_badge = badge_record.entry().to_app_option::<Badge>().unwrap().unwrap();

    let base_path_string = format!("{}{}", link_target_badge.name, link_target_badge.location);
    let base_path = Path::from(base_path_string).path_entry_hash()?;

if base_path == link_base {
  Ok(ValidationCallbackResult::Valid)
}
```

But `let base_path = Path::from(base_path_string).path_entry_hash()?;` doesn't work because Path doesn't exist in the HDI. 
**Expected behavior**

**System information:**
holochain (holochain 0.1.5): db5b8b27da3bf296958c3bf54ac3950dc60a39c8
lair-keystore (lair_keystore 0.2.4): 43be404da0fd9d57bf4429c44def405bd6490f61
hc-launch (holochain_cli_launch 0.0.12): 1ad188a43900c139e52df10a21e3722f41dfb967
hc-scaffold (holochain_scaffolding_cli 0.1.8): 85997cbc4c92f0fea87447d7c7daed1245b47700

{"git_info":null,"cargo_pkg_version":"0.1.5","hdk_version_req":"0.1.3","hdi_version_req":"0.2.3","timestamp":"2023-06-12T10:14:14.311672Z","hostname":"Alastairs-MacBook-Pro.local","host":"x86_64-apple-darwin","target":"x86_64-apple-darwin","rustc_version":"rustc 1.66.1 (90743e729 2023-01-10)","rustflags":"","profile":"release"}

**Steps to reproduce**
N/A

**Comment by ThetaSinner** [comment]
@maackle do you know why paths aren't available in the HDI?

**Comment by ThetaSinner** [comment]
Also just noticed that this has been requested here too https://github.com/holochain/holochain/issues/2397

**Comment by maackle** [comment]
I think we just neglected to move Path to the HDI when we split off the HDI from the HDK. We should move it.

Also, our ultimate intention is to take Path out of the HDK completely and make it just another zome. But for now we should move it to the HDI.
