### ISSUE TITLE
[BUG] Having a zome in your DNA with no link types / entry types causes *all* delete_link / delete_entry actions to fail for other zomes

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain#2541]
**Describe the bug**
Same issue appears in 2 cases:
- If *any* zomes in a DNA do not contain link types, then any `delete_link()` calls for other zomes in the same DNA fail with `Source chain error: InvalidCommit error: There are no link types in this integrity zome`
- If *any* zomes in a DNA do not contain entry types, then any `delete_entry()` calls for other zomes in the same DNA fail with `Source chain error: InvalidCommit error: There are no entry types in this integrity zome`

**Expected behavior**
A zome with no entry types / link types should not prevent successful validation of delete_link / delete_entry calls related to types in a different zome in the same DNA.

**System information:**
 - OS: ubuntu 22.04
 - Browser: n/a
 - Holochain and HDK Version: 0.1.5

**Steps to reproduce**
Minimal example: https://github.com/mattyg/delete-link-bug-example
Run tests to see issue

**Screenshots**
n/a

**Additional context**
thanks to @mrbianchi for identifying and raising this issue (https://github.com/mattyg/herddit/pull/39/files/3541dc85f1ad58a5b7f1db001d373dd53b055674..450ac15a24535e152c7132567bf4321c3e95c307#r1246985598)

**Comment by ThetaSinner** [comment]
That's a really interesting edge case, I suspect we've run into this and not realized what the problem was so thank you for identifying and raising! That sounds like it should be a straight-forward hole to close

**Comment by mattyg** [comment]
I'd like to clarify something related to this issue -- is the validation callback for every zome in a DNA **supposed** to be run when something is validated? Or is it supposed to only run the validation callback for the single zome where that entry / link type is defined?

**Comment by ThetaSinner** [comment]
I'm not sure what the answer to that is. I'd say that even if you import the same struct into two zomes they become distinct types so it wouldn't make sense to attempt to validate it in another zome... 

@maackle Any idea about this?

**Comment by ThetaSinner** [comment]
Or maybe we should move the discussion to the linked issue actually

**Comment by maackle** [comment]
Yes this clearly seems like a consequence of #2868, so we could close this issue and focus on the other one
