### ISSUE TITLE
winerror when installing lair_keystore on Windows

### ISSUE THREAD

**Issue by dellams** [holochain/holochain#2731]
**Describe the bug**

When running `cargo install --version 0.2.4 lair_keystore ` as per the instructions here:
https://github.com/holochain/holochain/blob/develop/docs/happ_dev_setup_windows.md

You get the following error message:

```
error[E0433]: failed to resolve: could not find `winerror` in `shared`
  --> C:\Users\david\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lair_keystore_api-0.2.4\src\ipc_keystore\raw_ipc.rs:99:45
   |
99 | ...                   winapi::shared::winerror::ERROR_PIPE_BUSY as i32,
   |                                       ^^^^^^^^ could not find `winerror` in `shared`

   Compiling regex-automata v0.1.10
For more information about this error, try `rustc --explain E0433`.
error: could not compile `lair_keystore_api` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
    Building [===================>     ] 295/356: openssl-sys(build)
```

Not sure what is causing this, any ideas?

Thanks!

**Expected behavior**
To install and not error.

**System information:**
 - OS: Win11
 - Browser Chrome
 - Holochain and HDK Version (run `hn-introspect` as well as `holochain --build-info`
 from the nix shell and paste output)

**Steps to reproduce**

Follow https://github.com/holochain/holochain/blob/develop/docs/happ_dev_setup_windows.md

**Screenshots**

**Additional context**

**Comment by ThetaSinner** [comment]
Hi @dellams, yes this is one we know about. We've released v0.3.0 of Lair which fixes the problem but you'll need a version of Holochain that works with that. 
- We've released 0.1.6 if you're on the 0.1.x series. It hasn't been announced yet but it's ready to use.
- We have a release candidate out for 0.2.2 but that isn't tested yet. It mostly contains bugfixes so it should be fairly safe to use as release candidates go but it's hard to say until we finish our testing.

You can find the fix here -> https://github.com/holochain/lair/commit/3229604b6e17e92633d2f631561736dcaa997477

**Comment by dellams** [comment]
Ok great thanks, good to know! :) 

I will give 0.1.6 a go then since I am currently working with 0.1.5 so will be easiest to migrate to, hope there were not many other changes from 0.1.5? I'm getting close to releasing the updated c# client for 0.1.5 so didn't want to create too much work for myself at this stage! ;-) lol

When is it safe to upgrade to 0.3.0? I would love to upgrade the client to this version next so its bang up to date. Hope there were not too many changes? ;-) Thanks!

**Comment by dellams** [comment]
It is also odd that lair_keystore installed fine on my PC with 0.1.5 but failed on my laptop when I tried earlier today?

**Comment by ThetaSinner** [comment]
The diff is really small, it's just dealing with problems in dependencies. We've bumped/pinned a few dependencies both in Lair and Holochain but in terms of functionality there's no changes expected. It's really just a maintenance release this one.

It's expected that you'd see different results but time is the factor more than environment. The lair problem was a dependency that we're using changing the feature flags it sets for the winapi crate but we were relying on a feature flag being turned on. So when you build from `crates.io` you get new deps and the compile breaks.

**Comment by dellams** [comment]
Arrrr ,ok, that makes sense, thanks for clearing that up for me! :)

Keep up the great work guys, your doing great! We are nearly there! ;-) Keep pushing! 

Soon we will show the world what Holochain can really do! ;-)
