### ISSUE TITLE
[BUG] "failed to get data_local_dir" error on Android

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#2801]
**Describe the bug**

While running holochain v0.2.2 in Android, this error happened:

```
09-16 22:56:37.376 12628 12788 I RustStdoutStderr: ###ADMIN_PORT:18863###
09-16 22:56:37.376 12628 12788 I RustStdoutStderr: ###HOLOCHAIN_SETUP_END###
09-16 22:56:37.434 12628 12628 I WebViewFactory: Loading com.google.android.webview version 116.0.5845.173 (code 584517331)
09-16 22:56:37.450 12628 12628 W linker  : Warning: "/data/app/com.google.android.webview-PStRcZrWH1s3LVezUQ9vMQ==/base.apk!/lib/arm64-v8a/libmonochrome.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
09-16 22:56:37.450 12628 12788 I RustStdoutStderr: WARNING: linker: Warning: "/data/app/com.google.android.webview-PStRcZrWH1s3LVezUQ9vMQ==/base.apk!/lib/arm64-v8a/libmonochrome.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
09-16 22:56:37.497 12628 12628 I cr_WVCFactoryProvider: Loaded version=116.0.5845.173 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
09-16 22:56:37.559 12628 12628 I cr_LibraryLoader: Successfully loaded native library
09-16 22:56:37.561 12628 12628 I cr_CachingUmaRecorder: Flushed 6 samples from 6 histograms, 0 samples were dropped.
09-16 22:56:37.678 12628 13231 W chromium: [WARNING:dns_config_service_android.cc(115)] Failed to read DnsConfig.
09-16 22:56:37.679 12628 12788 I RustStdoutStderr: [WARNING:dns_config_service_android.cc(115)] Failed to read DnsConfig.
09-16 22:56:37.922 12628 12628 W ContentCatcher: Failed to notify a WebView
09-16 22:56:37.946 12628 13238 W cr_media: registerBluetoothIntentsIfNeeded: Requires BLUETOOTH permission
09-16 22:56:38.113 12628 13250 W chromium: [WARNING:display_webview.cc(32)] WebView overlays are enabled!
09-16 22:56:38.113 12628 12788 I RustStdoutStderr: [WARNING:display_webview.cc(32)] WebView overlays are enabled!
09-16 22:56:38.895 12628 12788 I RustStdoutStderr: FATAL PANIC PanicInfo {
09-16 22:56:38.895 12628 12788 I RustStdoutStderr:     payload: Any { .. },
09-16 22:56:38.895 12628 12788 I RustStdoutStderr:     message: Some(
09-16 22:56:38.895 12628 12788 I RustStdoutStderr:         failed to get data_local_dir,
09-16 22:56:38.895 12628 12788 I RustStdoutStderr:     ),
09-16 22:56:38.895 12628 12788 I RustStdoutStderr:     location: Location {
09-16 22:56:38.895 12628 12788 I RustStdoutStderr:         file: "/home/guillem/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tx5-core-0.0.2-alpha/src/file_check.rs",
09-16 22:56:38.895 12628 12788 I RustStdoutStderr:         line: 30,
09-16 22:56:38.895 12628 12788 I RustStdoutStderr:         col: 32,
09-16 22:56:38.895 12628 12788 I RustStdoutStderr:     },
09-16 22:56:38.895 12628 12788 I RustStdoutStderr:     can_unwind: true,
09-16 22:56:38.895 12628 12788 I RustStdoutStderr: }
09-16 22:56:38.895 12628 12788 I RustStdoutStderr: thread 'tokio-runtime-worker' panicked at 'failed to get data_local_dir', /home/guillem/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tx5-core-0.0.2-alpha/src/file_check.rs:30:32
09-16 22:56:38.895 12628 12788 I RustStdoutStderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
09-16 22:56:47.591 12628 13221 W cr_ChildProcessConn: Fallback to ComponentInfo{com.google.android.webview/org.chromium.content.app.SandboxedProcessService1}
09-16 22:57:12.337 12628 12628 W IInputConnectionWrapper: getExtractedText on inactive InputConnection
```

After a small investigation, it seems to come from [this line in tx5](https://github.com/holochain/tx5/blob/8d0e74387d8aa541ef283db770541ff933f52b26/crates/tx5-core/src/file_check.rs#L30).

And the problem seems to be that the dependency crate that that line uses [doesn't actually have an android implementation](https://github.com/dirs-dev/dirs-rs/blob/1c2e3efad531aa67a5656eaedf53fdb8fa9094f7/src/lib.rs#L18), so it obviously fails.

I'll try to work around it for now, if I'm able to I'll share the provisional solution. But otherwise this is blocking me from continuing my experiments in android.

@neonphog @abe-njama @ThetaSinner 

**System information:**
 - OS: Android 10
 - Holochain and HDK Version (run `hn-introspect` as well as `holochain --build-info`
 from the nix shell and paste output)

```
[holonix:~/projects/darksoil/rostanga-test]$ hn-introspect
holochain (holochain 0.2.2): 1f59d33623031eefe76b5f3573970c9c33f21877
lair-keystore (lair_keystore 0.3.0): 6ab41b60744515f1760669db6fc5272298a5f324
hc-launch (holochain_cli_launch 0.0.13): 75ecdd0aa191ed830cc209a984a6030e656042ff
hc-scaffold (holochain_scaffolding_cli 0.1.11): 8a63d356a0856643769adc567e078796c6509511
```

```
[holonix:~/projects/darksoil/rostanga-test]$ holochain --build-info
{"git_info":null,"cargo_pkg_version":"0.2.2","hdk_version_req":"0.2.2","hdi_version_req":"0.3.2","timestamp":"2023-09-15T06:31:39.286281418Z","hostname":"localhost","host":"x86_64-unknown-linux-gnu","target":"x86_64-unknown-linux-gnu","rustc_version":"rustc 1.66.1 (90743e729 2023-01-10)","rustflags":"","profile":"release"}
```

**Steps to reproduce**

Run holochain v0.2.2 in an android phone.

**Comment by guillemcordoba** [comment]
Using [app_dirs2](https://docs.rs/app_dirs2/2.5.5/app_dirs2/) seems to work.

**Comment by ThetaSinner** [comment]
@steveej FYI

**Comment by ThetaSinner** [comment]
As a general comment on this kind of problem, the Holochain team compiling for android chip targets won't be enough to catch this kind of problem. I'm almost certain that we'll find other issues like this within Holochain. In fact it took me about 10 seconds to find one in `holochain` -> https://crates.io/crates/directories which supports Win/Mac/Linux but not mobile environments. It's really good of dirs to error on an unrecognized platform. I think there's a good chance not all libraries will be that well behaved and will try to write to 'Linux' locations on mobile and will just fail with strange errors.

Obviously Holochain having CI for mobile would be a nice end goal but in the meantime I wonder if a review of dependencies that provide a platform specific implementation would be worthwhile to try and unblock people trying to develop for mobile

cc: @abe-njama

**Comment by neonphog** [comment]
[Tx5 now has an android CI test](https://github.com/holochain/tx5/pull/52) - It cross-compiles all the unit tests for the android platform, starts up an api-level 29 emulator, and uses adb to push them up sequentially and run them.

**Comment by guillemcordoba** [comment]
Thanks @neonphog ! I am now getting the `assertion failed: flags.is_empty()` error in my android emulator as well, I think it shows up as soon as I start another node in my computer and the node in the android emulator tries to connect with it. So right now this error is blocking me (ping @abe-njama) , but I'm happy that we got this far and can start ironing these bugs out.

**Comment by guillemcordoba** [comment]
I've just opened an [issue in tx5 about the flags.is_empty() problem](https://github.com/holochain/tx5/issues/62). I'm keeping this issue open because the original issue is still there.

**Comment by neonphog** [comment]
@guillemcordoba - Now that https://github.com/holochain/tx5/issues/62 is fixed, the Android CI is actually passing.

Are you still running into this problem?

It seems like either:

- Some other change (like a dependency bump) fixed this, or
- It works fine on the android api level 29 that i am testing with, but not on whatever emulator you are running?

**Comment by neonphog** [comment]
[Working on android 33 CI](https://github.com/holochain/tx5/pull/65) - for the most part it seems to be working, except that for whatever reason it is a lot slower than 29, and is blowing out the timings on some unit tests, so I'm working on test fixes to make them less timing dependent.

**Comment by neonphog** [comment]
This should be fixed with https://github.com/holochain/tx5/issues/69 in https://github.com/holochain/holochain/pull/3287
