### ISSUE TITLE
[BUG] this error feels 'over the top' as an error

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#2832]
The fact that these are logging at the Error level feels odd. Should this be a warning instead?
Sep 23 13:36:51.684 ERROR holochain_sqlite::db::access: Connection pool took 38.38448ms to be free'd

**Comment by ThetaSinner** [comment]
Yes very true. I've taken this down to a warning for now with the intention to switch it to a metric because it really doesn't need to be in the logs at all as it's performance information
