### ISSUE TITLE
[QUESTION] how to interpret certain 'error' logs

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#2949]
How should we interpret certain error logs? What do they mean? What might be their implications in practice?

<pre>
ERROR kitsune_p2p::gossip::sharded_gossip: Gossip failed to send outgoing message because of:
 KitsuneError(Other(Custom { kind: Other, error: Timeout }))
</pre>
this is something that appears routinely in Acorn logs, during regular use.

Here's another:
```
ERROR kitsune_p2p::gossip::sharded_gossip: Tgt expired [83, 77, 28, 70, 247, 14, 15, 200, 68, 220, 243, 37, 58, 229, 197, 184, 108, 219, 22, 30, 93, 224, 6, 27, 23, 179, 161, 72, 54, 252, 133, 87]
```
routinely visible. 

@neonphog @maackle

**Comment by Connoropolous** [comment]
I guess the latter comes from line 555:
https://github.com/holochain/holochain/blob/02795698bd903e2b6e262e5bac99861b99d40d8c/crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip.rs#L543-L573

**Comment by Connoropolous** [comment]
and the former, in `process_incoming_outgoing`

https://github.com/holochain/holochain/blob/02795698bd903e2b6e262e5bac99861b99d40d8c/crates/kitsune_p2p/kitsune_p2p/src/gossip/sharded_gossip.rs#L369-L378

**Comment by Connoropolous** [comment]
I'm actually also wondering whether these should be logged as errors, maybe warnings?

**Comment by Connoropolous** [comment]
@ThetaSinner

**Comment by jost-s** [comment]
I was wondering recently why there are so many logs that happen routinely and bear no clue to underlying problems. When sifting through a log file and finding hundreds of lines of logs that are not to do with a problem, why are they there to begin with? I'm in favor of at least demoting their log level.

**Comment by neonphog** [comment]
The most common reason for both of these is that the node has a valid peer_info for a remote peer that is actually not on the network anymore. We initiate a gossip round with this remote peer and get timeout errors trying to send them messages, and then finally give up trying to gossip with them and print out the target expired message.

**Comment by Connoropolous** [comment]
thanks, so message one likely eventually leads to message two, for a given peer who's gone offline. And we have them in our 'peer_info' because the bootstrap still serves them up?

**Comment by neonphog** [comment]
It would be fairly trivial to remove nodes from the bootstrap server on conductor shutdown. But we haven't even bothered to implement that because the agent_info would just be re-gossiped to each other. We haven't yet designed a good way to "publish" the fact that we're going offline before we do, since publishing is such a time-intensive process...

So, yes, for the moment you have to wait the 20 minutes until the agent_info expires.

**Comment by Connoropolous** [comment]
thanks. do you suppose it would be better to A. change the message, or B. change the log level
?

**Comment by neonphog** [comment]
We could potentially move them to WARN level... This is another one of those cases where if we hide it too much, it could make it hard to diagnose problems like a bad firewall config that is blocking outgoing communications.

And I'm fine changing the message too, I just have no idea to what... I'm to close to the code, it makes perfect sense to me : )

**Comment by Connoropolous** [comment]
I recommend changing them to WARN and also basically just filling them both in with the expanded context that you just provided in this thread

**Comment by Connoropolous** [comment]
if these scenarios ever become non-routine and something closer to fatal or indicating a truly bad state, then they could be flipped back to ERROR

**Comment by maackle** [comment]
Yes, seems like this should be a warning at least until we implement proper "leaving".

The ideal would probably be something like tracking all connection attempts, and if *all* of them fail within a certain period of time, like a minute, then these become errors, showing that it's more likely a problem with you than a problem with everyone else

**Comment by maackle** [comment]
Also this is pointing more and more to the fact that we should probably just get around to implementing "leave network". See also https://github.com/holochain/holochain/pull/3032#issuecomment-1810798455
