### ISSUE TITLE
[ENHANCEMENT] Make sqlite_encrypted feature default for release profile

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain#2957]
As discussed on the office hours today. I think we should make `sqlite_encrypted` a default feature for release builds.

**Comment by ThetaSinner** [comment]
I've contributed to this PR to address my concerns about the operational side of this change. I'm now happy for it to proceed but we'll need another reviewer now I've worked on the PR. I've pinged the assigned reviewers and please do have a look yourself!
