### ISSUE TITLE
[BUG] Having multiple Unrestricted CapGrants doesn't work

### ISSUE THREAD

**Issue by ddd-mtl** [holochain/holochain#3037]
**Describe the bug**
If multiple Unrestricted CapGrants are created (by different zomes in the same dna for example), Holochain will only lookup the first one when validating remote calls, and return a BadCapGrant error for remote calls to subsequent capGranted functions.

**Expected behavior**
Remote calling zome functions with unrestricted capGrants should be valid, regardless of how many capGrants have been already created. Even by other zomes.

**System information:**
 - Holochain 0.2.2

**Steps to reproduce**
Have a dna with two zomes. Each one creating an unrestricted capGrant for one of its zome function at init().
Launch two agents with that dna. Remote call each unrestricted zome function. The one with the last created CapGrant will fail with BadCapGrant.
Changing the order of zomes in the DNA will have the other zome function call fail instead.

**Other note**
I haven't tested with multiple unrestricted capGrant from the same zome.

**Comment by ThetaSinner** [comment]
@jost-s Do you know anything about this one? I think you worked on something similar recently?

**Comment by jost-s** [comment]
I have worked on something similar, yes, but this is new to me. Nothing jumps out at me from looking at the query. I'd like to look into this issue. cc @abe-njama

**Comment by ddd-mtl** [comment]
Well it seems to only look for one entry in the sql database, whereas it should look for all unrestricited cap grants.
Maybe this is already fixed in 0.3.x ?
https://github.com/holochain/holochain/blob/1081f0026438aaca16539ce8d3d5fc831011cedb/crates/holochain_state/src/source_chain.rs#L686

**Comment by jost-s** [comment]
It looks up [an unrestricted cap grant](https://github.com/holochain/holochain/blob/1081f0026438aaca16539ce8d3d5fc831011cedb/crates/holochain_sqlite/src/sql/conductor/select_valid_unrestricted_cap_grant.sql) for the [chain author](https://github.com/holochain/holochain/blob/1081f0026438aaca16539ce8d3d5fc831011cedb/crates/holochain_state/src/source_chain.rs#L690), so any cap grant should be returned regardless of how many there are.

No, it's the same [in 0.3.0](https://github.com/holochain/holochain/blob/develop/crates/holochain_sqlite/src/sql/conductor/select_valid_unrestricted_cap_grant.sql).

**Comment by jost-s** [comment]
Bug confirmed for `GrantedFunctions::Listed`. Using `GrantedFunctions::All` works.
I'll create an integration test in the Holochain repo and fix it.

**Comment by jost-s** [comment]
In fact it's not a stable bug/feature. I've recreated it as a sweettest and it fails and succeeds randomly. Then I went back to the Tryorama test and ran it again and it passes now too. Something depending on timing could be causing this fluctuation.

**Comment by jost-s** [comment]
This is released with Holochain v0.3.0-beta-dev.26 and will be included in v0.2.4 too.
