### ISSUE TITLE
Committing more than 116 entries in the same zome call hangs the conductor

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#308]
In the context of the same zome call, I am able to commit 116 correctly and very quickly, but committing 117 hangs the conductor and doesn't return any results.

This doesn't depend on the size of the entries, as the same behavior applies to entries of 100KB or a few bytes.

Should I post publicly a repository to be able to reproduce?

This should be retested once the memory leak on the LMDB databases is fixed.

**Comment by artbrock** [comment]
Isn't this issue solved now @guillemcordoba ?  I think the updates to our async calling methods for wasm may have fixed this issue.  But I've lost track.

**Comment by guillemcordoba** [comment]
Yes, solved! No more limit in sight, I'm able to commit thousands of entries in one zome call with very reasonable performance.
