### ISSUE TITLE
[BUG] Wasmer error: Cannot allocate memory, on iOS

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#3096]
**Describe the bug**

Running the latest Holochain release on iOS and trying to install an app makes Holochain throw this error: 

```
Link(Resource("Failed to create memory: Error when allocating memory: Cannot allocate memory (os error 12)"))
```

On [this line](https://github.com/holochain/holochain/blob/e0f514381e42f6071263babd22e3a03ae8acf0d8/crates/holochain/src/core/ribosome/real_ribosome.rs#L447).

**Expected behavior**

Holochain is able to install an app.

**System information:**
 - OS: iOS v17.1.1
 - Holochain v0.3.0-beta-dev.26
 - HDK v0.3.0-beta-dev.21

**Steps to reproduce**

I've needed to clone Holochain and add the println to that map_err manually, otherwise the error was obscured in the logs.

1. Run Holochain on iOS, you can use [this app](https://github.com/darksoil-studio/rostanga-test).
2. Install an app, [this is a minimal 1 zome app](https://github.com/darksoil-studio/gather/releases/download/v0.0.4/profiles.webhapp) compiled with hdk v0.3.0-beta-dev.21.

@abe-njama this is blocking further iOS development.

**Comment by guillemcordoba** [comment]
I've been able to work around the issue by setting tuneables to the Wasmer engine:

```rust
        let mut engine =   EngineBuilder::new(crane).engine();
        engine.set_tunables(BaseTunables {
            static_memory_bound: 0x4000.into(), 
            static_memory_offset_guard_size: 0x1_0000,
            dynamic_memory_offset_guard_size: 0x1_0000,
            });

        let store = Store::new(engine);
```

[In this line](https://github.com/holochain/holochain-wasmer/blob/91cbd3ee679bddfb9ef89ccb9a9dbc5ac052c141/crates/host/src/module.rs#L182). @thedavidmeister do you want me to open a PR for this?

**Comment by thedavidmeister** [comment]
actually this was done pretty sure

**Comment by guillemcordoba** [comment]
Actually [this PR](https://github.com/holochain/holochain-wasmer/pull/106/files#diff-405852649eac9f73c8e14022468037eb4ffcc720f1a06195f67e1f475821de8aL182) removes this. And AFAIU that PR is to be merged soon.

**Comment by jost-s** [comment]
@guillemcordoba Sorry, brought that back.

**Comment by guillemcordoba** [comment]
:+1:
