### ISSUE TITLE
Misleading error when creating entry not listed in entry_defs

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#339]
When I try to create an entry not listed in `entry_defs`, this is the error I get:

```
  type: 'Error',
  data: {
    type: 'RibosomeError',
    data: 'Wasm error while working with Ribosome: CallError("RuntimeError: unknown error")'
  }
```

Which made it hard for me to find the actual issue. I reckon a better message would suffice.

**Comment by zippy** [comment]
Hey @guillemcordoba I just ran into this too after an hour of searching for the issue!.  Currently now that things are working across the board, the team is prioritizing a bunch of usability issues, and so I'm hoping this one gets fixed as part of that!

**Comment by freesig** [comment]
Backlog item created

**Comment by artbrock** [comment]
Did this get fixed in the most recent round of HDK changes including major changes to tracing & errors/results?

**Comment by thedavidmeister** [comment]
@artbrock i believe i can confirm this is no longer an issue since i changed the way that the HDK interfaces with entry defs when it uses it under the hood now dials out to the host, which gets an actual error message

@guillemcordoba feel free to reopen and ping me if still an issue
