### ISSUE TITLE
Remove provision of openssl in Holochain builds in favour of not depending on the system openssl

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain#3423]
This is likely to cause problems downstream, such as when a different openssl is available or none is found like in #3422.

In theory we're only depending on the static openssl, so it should be getting compiled into binaries that we produce. That's fine for us, but for anybody else doing builds, if they end up depending on a dynamically linked openssl then the experience is potentially worse.

We should start by removing any dependencies on openssl being provided during builds. Then we can remove it and then builds will fail for us if we make a change that re-introduces the dependency, rather than downstream where it's harder to debug.

**Comment by jost-s** [comment]
not a problem right now
