### ISSUE TITLE
Tests for sharded gossip

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain#3436]
Ideally using the same mocks that are being used by the most recent Kitsune integration tests. We need to find a way to write tests for sharded gossip. There currently aren't any tests that actually check what happens when sharding kicks in. There are tests that verify the behaviour of gossip with fewer nodes, just not the sharding cases. A potential approach could be to turn the sharding threshold down so that it kicks in during a test with 5/6 nodes because we can only run so many instances of Kitsune reliably in a single test on CI.

**Comment by maackle** [comment]
There is this test and others, but it's been ignored for over a year :/ https://github.com/holochain/holochain/blob/fb5c60a11b9bd3582393956c5617502cec6748d7/crates/kitsune_p2p/kitsune_p2p/src/test/switchboard/tests.rs#L66

**Comment by ThetaSinner** [comment]
Refinement notes:
- We'll try to stick to the initial test scale of using a few nodes. If we don't find problems there and everything works then great and we need a new issue to look at running with more nodes.
- What can we learn from the existing switchboard tests? These might need some dusting off but are designed to test sharding.
- If the tests discover a problem, then fixing the problem is not in scope.
