### ISSUE TITLE
'A continuous arc set could not be properly quantized' error message

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#3440]
**Describe the bug**
This error has been popping up in holochain 0.2.7-rc.1 

u001b[2m:\u001b[0m \u001b[2mholochain::conductor::kitsune_host_impl::query_region_set\u001b[0m\u001b[2m:\u001b[0m \u001b[2m/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.2.7-rc.1/src/conductor/kitsune_host_impl/query_region_set.rs\u001b[0m\u001b[2m:\u001b[0m\u001b[2m54:\u001b[0m A continuous arc set could not be properly quantized."}
{"timestamp":"2024-03-12T12:17:03.262Z","label":"HOLOCHAIN 0.2.7-rc.1","level":"info","message":"            Original:  DhtArcSet(["}
{"timestamp":"2024-03-12T12:17:03.262Z","label":"HOLOCHAIN 0.2.7-rc.1","level":"info","message":"    Interval {"}
{"timestamp":"2024-03-12T12:17:03.262Z","label":"HOLOCHAIN 0.2.7-rc.1","level":"info","message":"        lb: DhtLocation("}
{"timestamp":"2024-03-12T12:17:03.262Z","label":"HOLOCHAIN 0.2.7-rc.1","level":"info","message":"            1831460650,"}
{"timestamp":"2024-03-12T12:17:03.262Z","label":"HOLOCHAIN 0.2.7-rc.1","level":"info","message":"        ),"}
{"timestamp":"2024-03-12T12:17:03.262Z","label":"HOLOCHAIN 0.2.7-rc.1","level":"info","message":"        ub: DhtLocation("}
{"timestamp":"2024-03-12T12:17:03.263Z","label":"HOLOCHAIN 0.2.7-rc.1","level":"info","message":"            1835654954,"}
{"timestamp":"2024-03-12T12:17:03.263Z","label":"HOLOCHAIN 0.2.7-rc.1","level":"info","message":"        ),"}
{"timestamp":"2024-03-12T12:17:03.263Z","label":"HOLOCHAIN 0.2.7-rc.1","level":"info","message":"    },"}
{"timestamp":"2024-03-12T12:17:03.263Z","label":"HOLOCHAIN 0.2.7-rc.1","level":"info","message":"])"}
{"timestamp":"2024-03-12T12:17:03.263Z","label":"HOLOCHAIN 0.2.7-rc.1","level":"info","message":"            Quantized: ArqSet { arqs: [Arq { start: SpaceOffset(3493), power: 7, count: SpaceOffset(8) }], power: 7 }"}

**Comment by maackle** [comment]
Interestingly there's this PR from almost a year ago that was supposed to solve it. Guess it didn't. Note to self to look into that. https://github.com/holochain/holochain/pull/2332/files

**Comment by maackle** [comment]
Another example from @zippy

```
{"timestamp":"2024-04-03T15:23:52.751Z","label":"HOLOCHAIN 0.3.0-beta-dev.42-1ddfd2d","level":"info","message":"            Quantized: ArqSet { arqs: [Arq { start: SpaceOffset(155676), power: 0, count: SpaceOffset(8) }], power: 0 }"}
{"timestamp":"2024-04-03T15:23:53.866Z","label":"HOLOCHAIN 0.3.0-beta-dev.42-1ddfd2d","level":"info","message":"\u001b[2m2024-04-03T15:23:53.866793Z\u001b[0m \u001b[33m WARN\u001b[0m \u001b[1mkitsune metric task\u001b[0m\u001b[2m:\u001b[0m \u001b[2mholochain::conductor::kitsune_host_impl::query_region_set\u001b[0m\u001b[2m:\u001b[0m \u001b[2mcrates/holochain/src/conductor/kitsune_host_impl/query_region_set.rs\u001b[0m\u001b[2m:\u001b[0m\u001b[2m54:\u001b[0m A continuous arc set could not be properly quantized."}
{"timestamp":"2024-04-03T15:23:53.866Z","label":"HOLOCHAIN 0.3.0-beta-dev.42-1ddfd2d","level":"info","message":"            Original:  DhtArcSet(["}
{"timestamp":"2024-04-03T15:23:53.866Z","label":"HOLOCHAIN 0.3.0-beta-dev.42-1ddfd2d","level":"info","message":"    Interval {"}
{"timestamp":"2024-04-03T15:23:53.866Z","label":"HOLOCHAIN 0.3.0-beta-dev.42-1ddfd2d","level":"info","message":"        lb: DhtLocation("}
{"timestamp":"2024-04-03T15:23:53.866Z","label":"HOLOCHAIN 0.3.0-beta-dev.42-1ddfd2d","level":"info","message":"            637649458,"}
{"timestamp":"2024-04-03T15:23:53.866Z","label":"HOLOCHAIN 0.3.0-beta-dev.42-1ddfd2d","level":"info","message":"        ),"}
{"timestamp":"2024-04-03T15:23:53.866Z","label":"HOLOCHAIN 0.3.0-beta-dev.42-1ddfd2d","level":"info","message":"        ub: DhtLocation("}
{"timestamp":"2024-04-03T15:23:53.867Z","label":"HOLOCHAIN 0.3.0-beta-dev.42-1ddfd2d","level":"info","message":"            637682226,"}
{"timestamp":"2024-04-03T15:23:53.867Z","label":"HOLOCHAIN 0.3.0-beta-dev.42-1ddfd2d","level":"info","message":"        ),"}
{"timestamp":"2024-04-03T15:23:53.867Z","label":"HOLOCHAIN 0.3.0-beta-dev.42-1ddfd2d","level":"info","message":"    },"}
{"timestamp":"2024-04-03T15:23:53.867Z","label":"HOLOCHAIN 0.3.0-beta-dev.42-1ddfd2d","level":"info","message":"])"}
{"timestamp":"2024-04-03T15:23:53.867Z","label":"HOLOCHAIN 0.3.0-beta-dev.42-1ddfd2d","level":"info","message":"            Quantized: ArqSet { arqs: [Arq { start: SpaceOffset(155676), power: 0, count: SpaceOffset(8) }], power: 0 }"}
```
