### ISSUE TITLE
Assess and reduce time spent on building the time tree in gossip

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain#3446]
In order to communicate the DHT state we see to other nodes during gossip, we build a time tree that represents the content of the DHT in time increments that aggregate up the tree. (A very rough summary that doesn't use quite the right language! Good enough for the purpose of this issue)

When an op arrives that is in a previous time segment, the tree leaf corresponding to that segment changes and that has a knock-on effect up the tree. This means that we have to do some recalculation when ops arrive later than we expect. That's fine, that's the point of this mechanism.

What we might not want to do, is rebuild this tree too often when nothing has changed. There is an [issue](https://github.com/holochain/wind-tunnel/issues/2) on Wind Tunnel that includes an item to track how much time this takes. This issue is a placeholder to implement caching for the time tree if that testing reveals an problem with gossip using an unreasonable amount of resources when the DHT size grows.

The suggested approach is to persist the time tree in a new database. The tree could be size-limited by restricting the depth to a fixed value. This means that when we receive an old op, the persisted state has to be updated. But most of the time when we need the time tree we can just grab it without querying the entire DHT database to rebuild the tree.

**Comment by jost-s** [comment]
closing as there's no known issue with time tree
