### ISSUE TITLE
Holonix is too large to depend on in CI

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain#3453]
It's fine that when you ask for a Holonix shell you get a build environment provided, but when you just ask for Holochain binaries you still get a bunch of stuff delivered that you really shouldn't need. I could understand if the binaries needed to be built but when they're coming from the `holochain-ci` cache, you still pull down an entire Python toolchain along with a bunch of other stuff.

When pulling [this](https://github.com/holochain/wind-tunnel/blob/main/flake.nix#L73) from the cache, I'd expect maybe 500Mb-1Gb. Not 5Gb. That's just the download size, it takes up more space on disk once it's decompressed.

**Comment by ThetaSinner** [comment]
I ended up hacking around this https://github.com/holochain/wind-tunnel/blob/main/.github/workflows/test.yaml#L19

**Comment by jost-s** [comment]
superseded by new holonix
