### ISSUE TITLE
Run a separate STUN infrastructure server

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#3479]
Run a separate STUN infrastructure server so that it can keep running and connecting folks that are able even if our TURN server is overloaded / offline.

- Pick a STUN server:
  - [coturn](https://github.com/coturn/coturn) venerable, but lightly maintained
  - [eturnal](https://eturnal.net/) fresh but written in erlang
- DISABLE TURN IN THE CONFIG
  - [coturn: stun-only](https://github.com/coturn/coturn/blob/bc54a4d9404f7e1fee7f0f907acec5f4882b2ae1/examples/etc/turnserver.conf#L610)
  - [eturnal: enable_turn false in listen directive](https://eturnal.net/doc/)
- Make it fast and reliable:
  - webrtc connection setup time is highly dependent on how quickly we get back the required data. I vote for redundant geosteered load balancing. Perhaps starting with two zones: America, and Euro, something like:
    - stun-1.holo.host geo steered load balance = [stun-1-america.holo.host, stun-1-euro.holo.host]
    - stun-2.holo.host geo steered load balance = [stun-2-america.holo.host, stun-2-euro.holo.host]
    - then set STUN config for RTC connections to ["stun:stun-1.holo.host", "stun:stun-2.holo.host"]
    - for a total of 4 stun servers

**Comment by steveej** [comment]
* [IETF DatatrackerA REST API For Access To TURN Services](https://datatracker.ietf.org/doc/html/draft-uberti-behave-turn-rest-00)
steveej
* implemented in pion/turn: https://github.com/pion/turn/commit/a9681a0fefde4911d5b3ff3343dc19487ea49cc4
    * [ ] double-check whether it's exposed in the rust bindings we use

**Comment by steveej** [comment]
in light of #3585 this will become a no-op for existing deployments, as their existing coturn will subsequently only be used for STUN.

**Comment by neonphog** [comment]
@steveej - this is not a no-op. please see the updated description.

**Comment by neonphog** [comment]
@steveej - I'm pretty sure this got closed in error. From what I can tell there are no STUN servers separate from TURN servers. Happy to be wrong though : )

**Comment by steveej** [comment]
thanks @neonphog, i indeed didn't intend to close this :smiley:

**Comment by steveej** [comment]
as a first step, two URLs for STUN are now available at `stun:stun-0.main.infra.holo.host:443` and `stun:stun-1.main.infra.holo.host:443`. they both point to the same coturn instance as of now. it allows us to put both in the default conductor configurations already before having the infrastructure fully built out.

in addition to successfully testing with https://icetest.info/ i also ran the following simple test:

```
$ nix shell nixpkgs#stuntman --command stunclient stun-0.main.infra.holo.host 443
nix shell nixpkgs#stuntman --command stunclient stun-1.main.infra.holo.host 443
Binding test: success
Local address: 192.168.24.192:36616
Mapped address: 80.218.43.120:24265
Binding test: success
Local address: 192.168.24.192:47718
Mapped address: 80.218.43.120:37638
```
