### ISSUE TITLE
`get_link_details` should accept a `GetLinksInput`

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#3502]
Now that `get_links` accepts `GetLinksInput`, I think `get_link_details` should as well just for the sake of consistency. I discovered that's not the case today and I was quite confused by it. Is there a reason I'm not seeing of why that wouldn't be the case?

**Comment by ThetaSinner** [comment]
I think it's the same as the difference between passing GetStrategy and GetOptions that only contains a GetStrategy, just an inconsistency that should be corrected

**Comment by pdaoust** [comment]
Closing in favour of #4575 which is a 'round-up' issue for all three links getters and the inconsistencies among them.
