### ISSUE TITLE
Fetch Pool

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#3513]
Review how the gossip fetch queue effects other system behaviors (such as get, get_details, get_links, etc.) because in some cases people are asking for multiple results (for metadata such as links, validation status, agent chain status, etc.). Is the fetch queue reducing this to a single source? How are active queries prioritized vs gossip? Is the pool sorted in some way? Is it possible new requests are getting stuck behind old requests which are failing to fetch?

**Comment by ThetaSinner** [comment]
There's an incorrect assumption here that get and get_details etc go via the fetch pool. There's been a conversation since this description was written about that not being the case. We could possibly unify the two but for now these are separate things.

**Comment by ThetaSinner** [comment]
For the behaviour of the fetch pool, I re-worked that recently and can answer any questions about how it functions.
