### ISSUE TITLE
[BUG] CI: the release-prepare job uses rustup's toolchain instead of the devShell's one

### ISSUE THREAD

**Issue by steveej** [holochain/holochain#3535]
this can lead to different semantics (lints, etc.) and thus the PR checks aren't predictive of release-prepare's behavior.

[failing job example](https://github.com/holochain/holochain/actions/runs/8531346251/job/23370834629#step:7:6961)

#### `nix develop --ignore-environment`
this approach requires explicitly listing the env vars we want inside the shell

#### remove rustup from the image
ensure the environment doesn't have a rust toolchain. this approach might require adaption over time

**Comment by ThetaSinner** [comment]
From the tools docs `If cargo-sweep fails to run rustup, it fallbacks to bare rustc call`. So it will always run rustup if it can and we have to try to block it to get it to behave sensibly. What problem was this tool originally solving and is there a way of solving it that doesn't involve this complexity?

**Comment by steveej** [comment]
i think [it's this invocation of release-automation](https://github.com/holochain/holochain/actions/runs/8531346251/job/23370834629#step:7:133) which runs the [failing rustc command (via cargo but that's not shown int the logs)](https://github.com/holochain/holochain/actions/runs/8531346251/job/23370834629#step:7:6958)
