### ISSUE TITLE
[FEATURE REQUEST] `list_app_interfaces()` should return `AllowedOrigins`, or some way to identify the app for which that app interface was created

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#3538]
After https://github.com/holochain/holochain/pull/3460, I'm configuring my tauri runtime to have a separate app interface per each holochain app in the conductor. I can only do that if `list_app_interfaces()` returns which app is associated with which port, so that from the runtime side I can spawn the given app's UI pointing to the appropriate websocket port.

**Comment by ThetaSinner** [comment]
We might have to re-work this depending on what happens next with app websocket security so I'm not going to fix this right now. If we keep the concept of multiple websockets rather than authenticated connections then I agree and I will add this :)

**Comment by ThetaSinner** [comment]
This got done as part of #3622
