### ISSUE TITLE
Cache pushes to cachix not working for Intel Macs

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain#3548]
This is failing because builds for Intel Macs are actually failing in Nix.

This breaks the instructions on the getting started portal and everyone using Intel Macs has to build Holochain from scratch with all its environment dependencies which can take hours, in my experience.

e.g. https://github.com/holochain/holochain/actions/runs/8553004129/job/23435291082#step:3:723

**Comment by steveej** [comment]
potential solutions to follow-up on:
* https://discourse.nixos.org/t/golang-macos-intel-x86-64-darwin-sectrustevaluatewitherror/42707/6

**Comment by ThetaSinner** [comment]
Check for a green cache build (on `develop`) when macos intel builds are fixed

**Comment by neonphog** [comment]
We're not going to fix this. The current state is that we are not building hc-launch because that doesn't work for intel mac. You should instead use hc-spin. We can more completely support intel mac when we refactor holonix.
