### ISSUE TITLE
Integrate Influxdb to Open Telemetry tracking of zome calls

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#3584]
Include the Open Telemetry call so that when zome calls happen, they send metering data through OTel to Influxdb so the collected metrics can be visualized

**Comment by thedavidmeister** [comment]
@ThetaSinner didn't we discuss this on a call and the outcome was that this is a runtime config thing?

if not, what needs to happen here?

**Comment by ThetaSinner** [comment]
@thedavidmeister For getting data sent from Holochain to Influx, yes absolutely. 

The only thing that I don't know here is whether we're collecting the information that you would want for visualising zome calls. Is that this metric? https://github.com/holochain/holochain/blob/develop/crates/holochain_metrics/src/lib.rs#L103

If so, then yes this can probably just be closed
