### ISSUE TITLE
Clarification on atomic write locking / auto retrying in the case of write collisions

### ISSUE THREAD

**Issue by Tails** [holochain/holochain#359]
For my use case of deferred non-agent-node users I am interested in the working of parallel atomic write locking, as stated in [this 'unpacking' blog post](https://blog.holochain.org/announcing-and-unpacking-the-new-holochain/):

> Concurrency is also enhanced by causing workflows to produce all their changes in a scratch space and allowing them read-only access to Holochain while doing so. Then at the end of their processing, we grab a lock for a very brief, atomic write transaction to the data sources and flush the changes from the scratch space to the underlying tables. We also guarantee that if multiple processes are attempting to write to the source chain, only the one to finish first will succeed, **requiring the others to retry their validation on top of the newly updated local state**.

This retrying process, is it automatic, perhaps with a MAX_TRIES configuration, or is it left up to the (client) caller to perform the retry? 

I'm asking because I would like 100+ users to issue calls to a Holochain node and write entries, and I'm hoping that retrying is not left up to the client...

**Comment by maackle** [comment]
See also this forum post: https://forum.holochain.org/t/threading-thread-safety/3963/15?u=maackle

For the near future, the retrying is left up to the client (sorry!). We just haven't implemented auto-retrying yet, though it's something we've considered. One reason is that in some cases, the UI definitely will *not* want to retry, so at the least, it would have to be configurable per-zome call, and we're trying to keep things simple while still building a lot of other functionality.

However that's not even the full story: this case isn't properly handled at the moment, and when there is a write collision, the conductor will panic. Here's a separate issue for that problem: https://github.com/holochain/holochain/issues/361

**Comment by Tails** [comment]
Thanks for this insightful answer. Could I leave this issue open to track the possible future auto-retry implementation?

**Comment by maackle** [comment]
Sure, and I updated the title to be a little more instructive

**Comment by maackle** [comment]
Commit retrying was implemented in https://github.com/holochain/holochain/pull/939
