### ISSUE TITLE
Update conductor state when an agent key is updated

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#3595]
When an agent changes their key, conductor state needs to be updated accordingly.

AC:
- [ ] Update conductor state when CellId changes
- [ ] Update any dependent cells that had "use_existing"-d this one by updating the role mapping to point to new CellId
- [ ] Workflows referencing a particular database need to be restarted

**Comment by ThetaSinner** [comment]
Suggestion for moving database files. Be careful with renaming! 

Check the code that was added for migrating from unencrypted to encrypted in `holochain_sqlite`. 

Database file moves could be done by doing something like:
- Close the database connection pool to ensure nobody is using the database from within Holochain.
- Create a single connection to the database and ask sqlite to compact the log (WAL) into the main database file.
- Close the single connection.
- Rename the file from the old cell ID to the new cell ID.
- Finish and allow the new connection pool to be opened by the caller, which will find the new database file and start a new log (WAL) etc.

**Comment by ThetaSinner** [comment]
- `must_get_agent_activity` queries by author so the implementation of that needs looking at
- Agent authorities need to keep serving the whole chain so that also needs considering -> see https://github.com/holochain/holochain/issues/3576

**Comment by jost-s** [comment]
Instead of updating the agent key on the same chain, new cells will be created, so no conductor state update is needed.
