### ISSUE TITLE
Source chain "as-at" collision check should return nice error, not panic

### ISSUE THREAD

**Issue by maackle** [holochain/holochain#361]
When the source chain head has moved while a zome call is running, the zome call will fail. It should indicate this failure to the user so they can decide what to do next, including retrying. However, currently this exception is not handled, and causes a panic that looks like this:

```rust
FATAL PANIC PanicInfo {
    payload: Any,
    message: Some(
        Error running Workflow: WorkspaceError(SourceChainError(HeadMoved(Some(HeaderHash(uhCkk7dmvdD82KuUcBSfE-ycS4-pJW2piai3nM-t9PXoNay00KlHB)), Some(HeaderHash(uhCkkcsEdVX-NC93QBm4lZVfkTskD6aK9Jq61mn6ZlhUHCqGiOJ5I))))),
    ),
    location: Location {
        file: "crates/holochain/src/core/queue_consumer/produce_dht_ops_consumer.rs",
        line: 34,
        col: 17,
    },
}
```

The `SourceChainError::HeadMoved` error needs to be properly handled and passed back as a response

**Comment by guillemcordoba** [comment]
If I have time over the next weekend I will give this a try, will strengthen my understanding of workflows.

**Comment by maackle** [comment]
Looks like this is still up for grabs, but @guillemcordoba say so if you still want to tackle it.

**Comment by artbrock** [comment]
Isn't this now properly returning a "chain head moved" error?

**Comment by guillemcordoba** [comment]
Yes it is, can be closed
