### ISSUE TITLE
DB access must find the right cell id after agents update their agent key

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#3610]
When agents update their agent key, cell ids of existing apps change. The DB has to be renamed, so that subsequent zome calls and DB accesses targeting new CellIds can call the new CellId.

AC:
- [ ] Create symlinks for the DB files when changing cell id to look up DB for previous cell ids
- [ ] Zome calls to the new cell id must find the new cell id
- [ ] DB calls to the new DB must be made to the new DB
- Test that
  - [ ] ops by the old agent can be published by the new agent
  - [ ] ops by the new agent can be published by the new agent

**Comment by jost-s** [comment]
Should database names have to be updated after all, here are considerations:

**Suggestion for moving database files. Be careful with renaming!**

Check the code that was added for migrating from unencrypted to encrypted in holochain_sqlite.

Database file moves could be done by doing something like:

- Close the database connection pool to ensure nobody is using the database from within Holochain.
- Create a single connection to the database and ask sqlite to compact the log (WAL) into the main database file.
- Close the single connection.
- Rename the file from the old cell ID to the new cell ID.
- Finish and allow the new connection pool to be opened by the caller, which will find the new database file and start a new log (WAL) etc.

**Comment by jost-s** [comment]
App needs to call the new cell id.
