### ISSUE TITLE
Stability testing for the 0.3 release

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain#3613]
Want to lay some groundwork that we can follow for later minor releases.

- [ ] #3846
  - Peer discovery.
  - Gossip should work.
  - Publishing should work.
  - Restarting conductors.
  - Multiple instances of the same app on the same machine, on a single conductor.
  - More than one session with the same happ to make sure gossip and peer discovery keep working over a period of time.

~~Which launcher are we launching with for 0.3? That's where we should do the testing above.~~ Electron

- [x] #3848
  - Simple test with agent-centric testing tools if we have enough tooling ready to do that.
  - Create Tryorama + TryCP test.

- [x] #3849
  - Run the existing scenarios.
  - Manually summarize the metrics produced.
  - As an outcome for next time, have a baseline to work off and hopefully some new ideas about what we still need from WT to make it useful.

- [x] #3829
  - Assume Holo has done the bump to an RC version for all HF deps and bumped HF.
  - Update the sweettest branch to work with the latest Holochain RC.
  - Run the test.

- [ ] #3847
  - Pick an happ that other people commit to using. Also needs to be an app that creates entries so that gossip and publishing etc are all in use.
  - Run the same happ on an always-on node and keep an eye on the performance of it.
  - We for realtime and load, but something with heavier validation and data creation for publishing/gossip
  
  Not a perfect check, but if we don't see the 100% CPU issue then that is a good sign.

- [ ] (Must have) Sharding
  - Turn down sharding threshold and test locally that sharding behaves correctly. #3436

**Comment by abe-njama** [comment]
I've appended the TargetRelease/0.3.0 label so as to track this as a release dependency.

**Comment by jost-s** [comment]
too late
