### ISSUE TITLE
Make sure authorities serve invalid data appropriately in different contexts

### ISSUE THREAD

**Issue by maackle** [holochain/holochain#3640]
When retrieving data from other authorities:

When the data is being retrieved to be used as a validation dependency for some ChainOp, if the data is actually invalid, the authority should serve `None` instead of the invalid data. This is the minimum requirement for ops based on invalid data to not be validated. They will instead remain in limbo indefinitely because no honest authority will serve that invalid dependency.

However, when retrieving an Op for the purpose of validating a Warrant, the authority needs to serve that invalid data.

If there are any other cases of the system fetching Actions, Entries, or Records (but not DhtOps themselves), make sure the proper behavior is occurring.

It may be the case that this simply breaks down to: if the requestor is using data to validate Chain Ops, don't return invalid data. If the requestor is using the data to validate a Warrant, do return invalid data.

Note that when sticky warrants land, the authority will return sticky warrants instead of None, in the former case.

**Comment by abe-njama** [comment]
Related PR: #4020
