### ISSUE TITLE
`get!()` does not return the entry as per latest develop

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#365]
I'm getting back an element with no entry with holochain repository at commit https://github.com/holochain/holochain/commit/490e6ba9c06e3962e7e319f997dbd56a7bb905f9. 

With a previous version (maybe two days ago?), I was getting the entry alongside the element with no problem.

**Comment by maackle** [comment]
@guillemcordoba can you describe a scenario where this happens so we can try to write a regression test?

**Comment by guillemcordoba** [comment]
Yes, sorry today I was out of time, tomorrow I'll try to post either a core test PR or a repro repo.

**Comment by guillemcordoba** [comment]
For now, rolling back before https://github.com/holochain/holochain/pull/351/files has restored good behavior. Will investigate more.

**Comment by guillemcordoba** [comment]
So sorry, not an issue. The problem was cargo cache while pointing to `git = { branch = "develop" }`. Develop on remote changed data structures with the PR I referenced, but cargo cache one was still with the old one.

Lesson learned, will point to a specific commit from now on.

**Comment by maackle** [comment]
Yeah, things are still changing fast :grimacing: glad you found the solution
