### ISSUE TITLE
Dependent DNA

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#3659]
System needs to give a useful error for missing deps. User needs to resolve the problem.
Conductor just needs to check for dependencies on install.
Possible undefined behaviour on out-of-order uninstall. Or a warning etc.
It should return an error that you need to to install the hApp then you can go to the App Store to install that hApp

Use case:
Expect people to want to build against HF, so need to be able to depend on it.

**Comment by ThetaSinner** [comment]
- Complete the deferred cells implementation:
  - Add a new request to the app interface to enable a deferred cell.
  - Ensure that what's currently available for "install method deferred" cells is sufficient, is enabled and is tested.


- Make it possible to depend on a DNA from another app at install time:
  - New field in the DNA manifest to specify a lineage of DNA hashes that are compatible (coordinator interface) with the current one.
  - `hc_bundle` updated to be able to create a new happ bundle with a lineage, based on the previous app.
  - Make `use_existing` an enum with a default of `Local` where the conductor will search through installed apps to find an appropriate dependency.
  - On install:
    - Check the `use_existing` and look for a DNA lineage in other apps that allow the app being installed to run.
    - Check for lineage forks and reject the install, require the user/developer to resolve the ambiguity.
    - Add a field to `InstallApp` that would allow somebody to resolve an ambiguous lineage and continue with installation without needing a developer to change something.
    - Return helpful error messages to explain what is missing so that users can work out what to go and install. Error should be human readable but also ensure that something like Launcher could use the missing DNA hashes to try and figure out what app the user might need to install.

**Comment by abe-njama** [comment]
#3956 
#3955
