### ISSUE TITLE
holonix: maintain a range of supported Nix versions

### ISSUE THREAD

**Issue by steveej** [holochain/holochain#3718]
> it's occurring to me that when we bump our version on various builders/workflows of our CI infrastructure, we don't know the minimum compatible Nix version that end-users of e.g. `.#holonix` will need. i think it's worth adding/extending a workflow that has a matrix of Nix versions that we want to test. this would give us the freedom to update CI versions and nix expressions while remaining compatible to the extent that we choose.

_Originally posted by @steveej in https://github.com/holochain/holochain/issues/3671#issuecomment-2067590480_

**Comment by ThetaSinner** [comment]
Prefer to support current stable for now and maybe consider this later

**Comment by steveej** [comment]
> Prefer to support current stable for now and maybe consider this later

pretty small though still a range: `[nixVeresions.stable.version]`.

leaves us with our source for "stable". here's an idea

```
$ nix eval github:holochain/holochain\#nixVersions.stable.version
"2.18.2"
```
