### ISSUE TITLE
[Sys validation] Reject deletes of deletes

### ISSUE THREAD

**Issue by jost-s** [holochain/holochain#3754]
Sys validation allows delete ops that delete another delete op. It has no meaning to do so and should be rejected.

AC:
- reject delete that references a delete action
- remove corresponding tests in app validation
  - https://github.com/holochain/holochain/blob/develop/crates/holochain/src/core/workflow/app_validation_workflow/get_zomes_to_invoke_tests.rs#L886
  - https://github.com/holochain/holochain/blob/develop/crates/holochain/src/core/workflow/app_validation_workflow/get_zomes_to_invoke_tests.rs#L966
  - https://github.com/holochain/holochain/blob/develop/crates/holochain/src/core/workflow/app_validation_workflow/get_zomes_to_invoke_tests.rs#L1429

**Comment by ThetaSinner** [comment]
In these cases we already retrieve deletes:
- https://github.com/holochain/holochain/blob/develop/crates/holochain/src/core/workflow/sys_validation_workflow.rs#L461
- https://github.com/holochain/holochain/blob/develop/crates/holochain/src/core/workflow/sys_validation_workflow.rs#L464

Would need to be added in StoreRecord:
- https://github.com/holochain/holochain/blob/develop/crates/holochain/src/core/workflow/sys_validation_workflow.rs#L424

And in StoreEntry?:
- https://github.com/holochain/holochain/blob/develop/crates/holochain/src/core/workflow/sys_validation_workflow.rs#L429

Then once we have the dependency, we can add a rule to check that the deleted action wasn't a delete itself. Tests will need to be updated as in the description

**Comment by ThetaSinner** [comment]
Refinement notes:

- Prevent apps with the same DNA hash but before/after this change from talking to each other.
