### ISSUE TITLE
feat(nix,holonix): use the rust-toolchain.toml for all rust packages

### ISSUE THREAD

**Issue by steveej** [holochain/holochain#3759]
1. initialize [rust-toolchain.toml](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) into each of the rust projects' repositories with the currently used rust toolchain, e.g. `1.77.0`.
2. use [rust-overlay's `fromRustupToolchainFile`](https://github.com/oxalica/rust-overlay/blob/2a42c742ab04b61d9b2f1edf392842cf9f27ebfd/README.md?plain=1#L195-L200) to assemble the toolchain
3. optional but encouraged: ensure holonix only contains a single desired (holochain's?) toolchain (#3696)

open questions:
1. [ ] should holonix support reading from the end-users project's `rust-toolchain.toml` or whether use holochain's version?

**Comment by ThetaSinner** [comment]
Bullet 3. possibly overlaps with -> https://github.com/holochain/holochain/issues/3696
