### ISSUE TITLE
Release automation can't handle self deps with a version

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain#3789]
When you create a `[dev-dependencies]` entry on self to set features in test, you cannot set a version. The release automation does not list self as a dependency and so will not bump the version. This will go unnoticed until a minor version bump where it will cause problems.

We either need to prevent versions being specified in self dev deps, or the release automation needs to bump the version.

This bug has been around for a long time and is a pain to debug each time it happens.

**Comment by jost-s** [comment]
We'll wait for the new release automation.
