### ISSUE TITLE
Dry run releases are broken due to a missing label

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain#3792]
For example https://github.com/holochain/holochain/actions/runs/8895398181/job/24430115829

**Comment by steveej** [comment]
i added the _release_ label and triggered a rerun for job in the first comment.

@ThetaSinner 

assuming that will allow the PR creation there is the mystery of how that label went missing. i'm willing to accept it as a one-time mystery and leave it at that until it were to happen again. is there more that you had in mind for this issue?

**Comment by steveej** [comment]
resulting PR of the retriggered run: https://github.com/holochain/holochain/pull/3838

**Comment by ThetaSinner** [comment]
Great if that was all that was wrong. I wanted to open an issue because I already had several things on the go but this doesn't need to be any more work if the dry-run is working again!

Yes a one-time mystery is fine. We need to be careful removing labels in general.

I do see that the versions produced on that PR aren't right which is a separate issue.

**Comment by steveej** [comment]
> I do see that the versions produced on that PR aren't right which is a separate issue.

is there an github issue for tracking that? "wrong version" sounds like we should definitely not let that slip through
