### ISSUE TITLE
Review of Key Manager Browser Extension

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#3826]
The Holo Key Manager is a browser extension that interfaces and connects to Chaperone, Holo’s client-side connection manager. It handles key derivation and signing. It has a currently unimplemented interface to store key metadata in DeepKey so that keys can be restored across multiple devices or in the event that local storage is wiped.

For launch, Holo Key Manager has the following product requirements::

- Generates seeds and keys according to the Holochain key management paradigm:
   - Master seed from randomness
   - Revocation seed derived using a derivation path agreed by convention
   - Device seed derived using a derivation path agreed by convention
- Seed and revocation key handling and exports are done following best practices
- Application keys derived using derivation paths that are compatible with DeepKey
- We store revocation pubkey and derivation paths so that keys can be registered in DeepKey later
- Users can use Key Manager to sign up and sign in to Hosted hApps
   - We handle the case where sign up requires a registration code and email 
- Chaperone can forward signing requests to key manager for signing
- All data held in local storage is encrypted by extension password
- Extension password can be changed
- Key handling all follows best practices for browser extensions
- Support for Chrome and FireFox

We are currently looking into a centralised storage option for key derivation paths before DeepKey integration. This is to ensure that if a user loses their Key Manager data, they can restore it (and thus restore their keys).

[Holo Key Manager Extension](https://docs.google.com/document/d/14A7bX831cbsYfSHeTJx_0vt83todE10tyIV60gtBm7g/edit#heading=h.x3obmhce0mxn)

[Repo](https://github.com/holo-host/holo-key-manager)

**Comment by neonphog** [comment]
Haven't heard any feedback, closing this as completed. Please re-open if there is something else to do here.
