### ISSUE TITLE
Atomic Holonix updates

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain#3844]
We are currently updating Holochain+Lair in Holonix together but Scaffolding and Launcher are being updated separately. We want to release all Holonix components atomically, when they are compatible with each other. 

e.g. Otherwise you end up scaffolding an app that needs to run on a different version of Holochain than is being provided etc.

To make this work we need:
- To disable the automatic flake updates for all versions, these will just release automatically when components change.
- A way to apply flake updates on an existing PR so that we can integrate component updates with PRs created by the `"Update Holonix versions"` workflow.

**Comment by abe-njama** [comment]
Related PR: #3850
