### ISSUE TITLE
query!() may be nicer to accept multiple variants of HeaderType

### ISSUE THREAD

**Issue by tatssato** [holochain/holochain#387]
the `query!()` macro accepts the `QueryFilter` which is a union of each of the field in the QueryFilter struct.
Right now, you can only specify one variant of the `HeaderType` enum in the header_type() method for `QueryFilter`.
This may not be necessary (because we can filter HeaderType in zome_fn level against what is returned from query macro), but may be nice to have if the `header_type` field in `QueryFilter` accepts an `Option<Vec<HeadrType>>` instead. This is especially useful when we want to have an intersected result of entry_type(EntryType::App(AppEntryType::new())) and any of the "entry-related" `HeaderType` variant such as `HeaderType::Create()`, `HeaderType::Update()`, and `HeaderType::Delete()` and just ignore all the other `HeaderType` variants.

**Comment by maackle** [comment]
Sounds useful to me, the only thing I'd add is that I suspect it would be better to use an `Option<HashSet<HeaderType>>` instead. If anyone wants to add this, say so and make a PR.

**Comment by abe-njama** [comment]
@tatssato I'd like to invite you to submit a PR for this feature enhancement. We will support this request by reviewing the submitted changes.

**Comment by maackle** [comment]
No, query still is limited to filtering by only one ActionType and one EntryType

**Comment by maackle** [comment]
PRs still welcome!
