### ISSUE TITLE
Deferred memproof provisioning

### ISSUE THREAD

**Issue by maackle** [holochain/holochain#3904]
In order to enable a UI-driven membrane joining process for apps, we need to be able to install an app and start up the app websocket listener before creating any cells for the app. The app's UI will take the user through the joining process, which may or may not involve generating new agent keys to use for the app using new method `RotateAppAgent`, and will finalize the app installation by calling `ProvideMembraneProofs`, which takes the same payload as the `InstallApp::membrane_proofs` field.

The main state change is that apps now have a new type of state they can be in, corresponding to the time between these two phases of installation. In this state, the only two app websocket methods which will be accepted are the two new ones: all others will fail with an error message telling the user that memproofs must be provided.

Detail:

### Changes to App installation process

`InstallAppPayload::membrane_proofs` can now take two values instead of just `HashMap<RoleName, MembraneProof>`:

```rust
MemproofProvisioning {
    /// Same as the current argument
    Provided(HashMap<RoleName, MembraneProof>)
    /// No proofs provided, must be provided later via app websocket call
    Deferred
}
```

#### `RotateAppAgent`

Updates (rotates) the agent keypair associated with this app.
Cannot be called once the app is fully installed, can only be called while memproofs are still deferred.

#### `ProvideMemproofs(HashMap<RoleName, MembraneProof>)`

Provide all memproofs for this app. Same as the old `membrane_proofs` field.
Cannot be called once the app is fully installed, can only be called while memproofs are still deferred.

### System changes

If using deferred memproofs, no cells are created at installation time.
If a zome call is attempted, or anything which requires a source chain or agent key to be known, an error is returned specifying that memproofs must be provided. This allows the UI to know whether to render the pre-join or the post-join UI.
As soon as `ProvideMemproofs` is called, the app is installed as normal.

### State changes

App entry in conductor state needs just needs to be able to determine if memproofs have been provided or not.

**Comment by artbrock** [comment]
> In this state, the only two app websocket methods which will be accepted are the two new ones: all others will fail with an error message telling the user that memproofs must be provided.

I don't think this limitation is realistic. For the app UI to perform the joining process, it almost surely needs some of the "info" methods such as: `AppInfo()`, `DnaInfo()`, and `AgentInfo()` (even though the agent key is not finalized yet).

**Comment by matthme** [comment]
Yes agreed, `AppInfo` should be callable as well and return the app status ("uninitiated" or similar) as well as the currently registered public key for this app.

**Comment by artbrock** [comment]
Questions:
 - If an app / some DNAs were partially installed, but the membrane process was never completed, is there some kind of clean up process needed?
 - If the process is attempted again at some point in the future, is there a new partial install, or do we recognize an existing partial install in progress?
 - Re: Port bindings... How does the UI know what port to use? Is this the same port for the app once fully installed? Is there any clean up of ports needed?

**Comment by matthme** [comment]
Regarding 1: I don't think so, at least not for the launcher case. Such an app would show up as a normal app in launcher. From an end-user perspective there is no difference between an app that has gone through joining and one that hasn't, the difference for them lies only in what they're presented in the app UI. It is therefore up to the end-user to uninstall such an app again if they decide that they don't want to complete the joining process.

**Comment by abe-njama** [comment]
First PR: #3928

**Comment by maackle** [comment]
Yes, I agree that only calls which require cells should fail. AppInfo and anything else that's purely about the app and not the cells should succeed.

@artbrock your questions: 

2. the full installation happens in two parts. From the perspective of a runtime like launcher, after the initial installation, the app shows up like any other, but when you open the app, you're given the joining flow. So you can open the app UI as many times as you like, and until you pass the joining process, that's what you'll see every time you use the app. If you want to clean up the partial install, you can uninstall the app like any other.
3. the same way UIs know what port to use in a normal installation. The app interface is created after the partial install. The only thing not created are the cells.
