### ISSUE TITLE
Re-review of Key Manager Browser Extension with all the audit findings resolved

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#3982]
This would be a second pass at reviewing the Key Manager Browser Extension once all the findings from the initial  review have been resolved. 
The focus would ideally be on the changes.

AC:
- Update to the audit report after all the changes are made based on recommendations and the PRs are reviewed

[Holo Key Manager Extension](https://docs.google.com/document/d/14A7bX831cbsYfSHeTJx_0vt83todE10tyIV60gtBm7g/edit#heading=h.x3obmhce0mxn)

[Repo](https://github.com/holo-host/holo-key-manager)

Initial Issue: #3826

**Comment by abe-njama** [comment]
Commit of Key Manager to review: 026ca8ef87b03a7d70348c0fa26ab9e3bf3b0dc3

**Comment by neonphog** [comment]
This has been completed.
