### ISSUE TITLE
Add DPKI call to HDK to get lineage of agent keys

### ISSUE THREAD

**Issue by jost-s** [holochain/holochain#4023]
The HDK needs a DPKI query to return the lineage of keys, given a key in the lineage. The bulk of this feature should be implemented in the Deepkey DNA.

Key updates are only possible with DPKI installed. If DPKI is not installed, a key can only be deleted.

When wanting to fetch data beyond agent key updates, it must be possible to query a lineage of keys for that key, so that the authority of the key before or after that key can be queried.

AC:
- Add HDK call to get a lineage of agent keys
- Method takes an agent key as parameter
- Returns a vector of keys, ordered by timestamp
- Return input agent key when DPKI is not installed
- Write a wasm test that uses this new call

**Comment by maackle** [comment]
Is it actually:

> If DPKI is not installed, a key can only be ~~revoked~~ deleted (via a `Delete` action).

Ideally this would be cached too, but that gets tricky. Hopefully this is not an expensive wasm invocation, I imagine it won't be though.

**Comment by jost-s** [comment]
Yes, it's "deleted" - updated.

**Comment by abe-njama** [comment]
@ThetaSinner @maackle is this change to the HDK breaking in nature? If so, I was hoping that we'd get this into a version for Holo to run the long-lived tests on.

**Comment by abe-njama** [comment]
The HDK call agent_key_lineage will increase the HDK version, and if you want to use the call, you'll need to recompile your DNA with it. So not breaking if you don't use it.
