### ISSUE TITLE
Review of Chaperone with Key Manager

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#4028]
Review of Chaperone and how it interacts with key manager

**Comment by abe-njama** [comment]
Update:

Holo will undertake a manual verification process to pick a happ and check the public keys displayed in key manager and also in chaperone. This is to prove that both key manager and chaperone use the same agent public key.

**Comment by neonphog** [comment]
Thanks @abe-njama ,

Indeed, given the existing audit of the key manager which ensures the private keys are not exposed, the theory is that the only way chaperone could be operating incorrectly is if it is using a different keypair. Checking that the public key identified by the key manager is also the one used on the other side should be enough to ensure secure behavior.

**Comment by jost-s** [comment]
Not required any more
