### ISSUE TITLE
Incremental arc resizing

### ISSUE THREAD

**Issue by maackle** [holochain/holochain#4047]
When starting from holding no data, or knowing you're significantly out of sync:

- start gossiping, advertise yourself as holding a single segment (at the power level of the arc you will eventually hold)
- wait until you've done rounds of gossip with 2 others
- now grow the arc to include the next segment, until reaching the desired arc size

alternatively: when querying yourself as an authority, always treat your arc as one segment smaller than what you advertised, so that you can be sure you're querying an arc that you are confident to be holding.

**Comment by ThetaSinner** [comment]
Superseded by Kitsune2 which will implement this
