### ISSUE TITLE
[BUG - HOLONIX] holochain 0.3.2 requires lair-keystore 0.4.5 but 0_3_rc ships with 0.4.4

### ISSUE THREAD

**Issue by joshuavial** [holochain/holochain#4119]
**Describe the bug**
I ran a `nix flake update` on a project with 0_3_rc and holochain wouldn't start due to lair-keystore incompatibility

**System information:**
wsl2, ubuntu

**Steps to reproduce**

```
nix run github:holochain/holochain#hc-scaffold -- example hello-world
cd hello-world
```
edit flake.nix to 0_3_rc
```
nix flake update
nix develop
npm install
npm start
```

My current work around is to put `  holochain-flake.inputs.lair.url = "github:holochain/lair/lair_keystore-v0.4.5";` into the flake.nix inputs

**Comment by jost-s** [comment]
Holochain 0.3 is out and you could upgrade to it. That should have the correct lair keystore.

**Comment by ThetaSinner** [comment]
Yes, upgrading to 0.3.1 is absolutely an option. But this is my mistake, I updated the `rc` version on 0_3_rc without updating Lair. I thought we had tests to catch this mismatch but still I should have caught this.

There's a linked PR that will resolve the problem. Thank you for reporting it!
