### ISSUE TITLE
Permission Denied Error Message While Attempting To Install

### ISSUE THREAD

**Issue by dellams** [holochain/holochain#413]
Hi Guys,

Just been following your instructions below, but I got a permission denied error message (below), any ideas?

"dellams@DESKTOP-CEETMKE:~$ git clone git@github.com:holochain/holochain.git
Cloning into 'holochain'...
The authenticity of host 'github.com (140.82.121.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? y
Please type 'yes', 'no' or the fingerprint: yes
Warning: Permanently added 'github.com,140.82.121.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository."

Also, I installed Nix as per the instructions in the link below, but when I run "nix-shell" I get this error message:

"dellams@DESKTOP-CEETMKE:~$ nix-shell
error: getting status of '/home/dellams/default.nix': No such file or directory"

I am using WSL2 on Windows 10, which worked fine for the previous hc with holocain.love. I presume that still points to the redux version? When will it be updated to the new version do you think? :)

Keep up the great work, really impressed with the new version and keen to upgrade HoloNET .NET/Unity client & .NET HDK to it along with my other hc code... thanks :)

Cheers
D.

**Comment by guillemcordoba** [comment]
Hi @dellams , I think this is more an issue with git authentication than with this repository. Do you have SSH keys setup for github in your computer? If not, you may want to try doing this instead:

`git clone https://github.com/holochain/holochain`

**Comment by dellams** [comment]
Ok great thanks. No I dont have them installed.

**Comment by dellams** [comment]
Whens the next RSM playground call? 🙂

**Comment by maackle** [comment]
Yes, this looks like more of a git auth issue.

**Comment by dellams** [comment]
What about the 2nd part of my question?

"Also, I installed Nix as per the instructions in the link below, but when I run "nix-shell" I get this error message:

"dellams@DESKTOP-CEETMKE:~$ nix-shell
error: getting status of '/home/dellams/default.nix': No such file or directory"

I am using WSL2 on Windows 10, which worked fine for the previous hc with holocain.love. I presume that still points to the redux version? When will it be updated to the new version do you think? :)"

Cheers
D.

**Comment by maackle** [comment]
@dellams did you run `nix-shell` inside the holochain repo?
