### ISSUE TITLE
[BUG] DepMissingFromDht when testing on a single conductor with a network of 1 agent

### ISSUE THREAD

**Issue by mjbrisebois** [holochain/holochain#4169]
**Describe the bug**
A `DepMissingFromDht` error in validation when running tests on 1 agent on 1 conductor.  The claimed missing dependency is the `AgentPubKey` entry when calling `must_get_agent_activity`.

**Expected behavior**
Since all the dependencies are local, they should be available.

**System information:**
 - Github Actions Ubuntu
 - Holochain v0.4.0-dev.15

**Steps to reproduce**
https://github.com/holochain/deepkey/actions/runs/10268373944/job/28411210074?pr=30#step:5:1970

**Additional Information**
[This test](https://github.com/holochain/deepkey/blame/main/tests/integration/test_change_rules.js#L117-L133) has consistently passed and remained unchanged since Jan 25, 2024.

**Comment by abe-njama** [comment]
In devhub, there are more validation anomalies that may be related to this. It seems like there has been a change to the order of events.  In devhub tests, zome calls are returning before the new actions are added to the chain. So if the next call uses a reference from the previous commit, it may not exist yet.

**Comment by jost-s** [comment]
Are you awaiting DHT consistency/synchronization in the test before making any zome calls?

**Comment by mjbrisebois** [comment]
@jost-s If there is a function for doing that, I am not calling it.  How do you wait for consistency?

**Comment by jost-s** [comment]
@mjbrisebois Well there is one in [Tryorama](https://github.com/holochain/tryorama/blob/d5033e0ad6b3b33fb885293aab91ee83d552d579/ts/src/util.ts#L114) which you can copy and try if that makes the test pass.

**Comment by mjbrisebois** [comment]
@jost-s It looks like that solution only works for multiple cells.  This bug is happening with a single cell.

**Comment by jost-s** [comment]
@mjbrisebois You're right, then it must be a different issue.

**Comment by ThetaSinner** [comment]
Resolved by https://github.com/holochain/holochain/pull/4197
