### ISSUE TITLE
[BUG] URL format panic

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#4170]
When starting up Launcher 0.300 you run into a URL format panic

[launcher.log](https://github.com/user-attachments/files/16513304/launcher.log)

[databases.zip](https://github.com/user-attachments/files/16513312/databases.zip)

```
Panic:
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"FATAL PANIC PanicInfo {"}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"    payload: Any { .. },"}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"    message: Some("}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"        called `Result::unwrap()` on an `Err` value: InvalidByte(5, 46),"}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"    ),"}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"    location: Location {"}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"        file: \"/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kitsune_p2p_proxy-0.3.1/src/proxy_url.rs\","}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"        line: 150,"}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"        col: 14,"}
{"timestamp":"2024-07-29T16:43:53.437Z","label":"HOLOCHAIN 0.3.1 @ partition 0.3.x","level":"info","message":"    },"}
```

**Comment by jost-s** [comment]
Initially I was able to reproduce the bug with the launcher downloaded from the releases page. I could also run locally built launcher instances and would always get the error. I was not able to see the string that failed to be parsed.

Once I cleaned the support folders that launcher creates in the OS's profile folder, the bug did not reappear. Since then I have not been able to reproduce it again, be it with downloaded or with built versions of launcher.

My suspicion is that some remaining support folders of previous launcher runs were not compatible with this current version of launcher.

**Comment by matthme** [comment]
reopening because it is not fixed.

**Comment by zippy** [comment]
Notes from refinement:

- `url2::parse` only happens in test
- `url2!()` may exist in production code


Possible Causes
- May have to do with different versions of Holochain using sbd with different format URLs.
- Bug in close where where URL is empty string.

Work required:
- sweep for parse and url2!()
- may need to bubble up result more plumbing.

**Comment by c12i** [comment]
@matthme is this bug only reproducible with launcher  `v0.300`?

**Comment by matthme** [comment]
No, it also occurred in Moss using 0.4.0-rc.0 for example. And there is no known way to reliably reproduce it since the cause for the occurrence of invalid URLs is still unknown.

**Comment by c12i** [comment]
Did a scan through the codebase, most of `url2` and `url2::Url2::parse` usage is limited to tests and test_utils. The one usage that I can link to production code is [here](https://github.com/holochain/holochain/blob/4a6bc89a50b93e2d8928a5f8d3a7383169daaf75/crates/kitsune_p2p/types/src/tx_utils/proxy_url.rs#L27).
