### ISSUE TITLE
Passing multiple functions in create_cap_grant macro and calling one of those function corrupts the database

### ISSUE THREAD

**Issue by tatssato** [holochain/holochain#418]
This issue is not urgent but I found it coincidentally when I was fiddling with create_cap_grant.

I tried passing multiple functions in to the `functions` argument of create_cap_grant! macro and tested if it will be executed properly in tryorama. the macro looks like this 

```rust
#[hdk_extern]
fn create_cap_grant(_: ()) -> ExternResult<()> {
    let mut functions: GrantedFunctions = HashSet::new();
    functions.insert((zome_info!()?.zome_name, "get_links_from_foo".into()));
    functions.insert((zome_info!()?.zome_name, "create_foofoo_and_link".into()));
    create_cap_grant!(
        CapGrantEntry {
            tag: "".into(),
            // empty access converts to unrestricted
            access: ().into(),
            functions,
        }
    )?;
    Ok(())
}

// showing create_foofoo_and_link since that is the only relevant function here
#[hdk_extern]
fn create_foofoo_and_link(_: ()) -> ExternResult<FooFoo> {
    let foofoo = FooFoo("foofoo".to_owned());
    let barbar = BarBar("barbar".to_owned());
    let base_hash = hash_entry!(&foofoo)?;
    let target_hash = hash_entry!(&barbar)?;
    create_entry!(&foofoo)?;
    create_entry!(&barbar)?;
    create_link!(
        base_hash,
        target_hash,
        LinkTag::new("foofoo->barbar")
    )?;
    Ok(foofoo)
}

// Then i have a call_remote to `create_foofoo_and_link`
#[hdk_extern]
fn commit_foofoo_remotely(agent: AgentPubKey) -> ExternResult<FooFoo> {
    let function = zome::FunctionName("create_foofoo_and_link".to_owned());

    match call_remote!(
        agent,
        zome_info!()?.zome_name,
        function,
        None,
        ().try_into()?
    )? {
        ZomeCallResponse::Ok(output) => {
            let sb = output.into_inner();
            let foofoo: FooFoo = sb.try_into()?;
            Ok(foofoo)
        },
        ZomeCallResponse::Unauthorized => {
            Err(HdkError::Wasm(WasmError::Zome(
                "this agent has no proper authorization".to_owned()
            )))
        },
    }
}
```
The test scenario is, 
1. bobbo commits cap grant
2. alice calls `commit_foofoo_remotely`
```typescript
orchestrator.registerScenario('Scenario 9: creating private entries remotely', async (s, t) => {
  const { conductor } = await s.players({ conductor: config })
  await conductor.spawn()

  const [dna_hash_2, agent_pubkey_bobby] = conductor.cellId('bobbo');
  
  let grant = await conductor.call("bobbo", "zomeone", "create_cap_grant", null);
  await delay(1000);
  let foofoo = await conductor.call("alice", "zomeone", "commit_foofoo_remotely", agent_pubkey_bobby);

  await delay(1000);
  t.ok(foofoo);
});
```

Now, testing this in tryorama shows this error when alice calls `commit_foofoo_remotely` (i think) which tells that the database is corrupted.
![image](https://user-images.githubusercontent.com/58587369/95958323-f6b74f80-0e3b-11eb-993d-c56dc93690d8.png)

Important note is that, this error only happens when I am calling remotely (to another cell) to a function that actually creates an entry (in the above case the `create_foofoo_and_link`). It seems like it has something to do with hashes not being equal (maybe because I included 2 functions in cap grant) but more than that, I don't really know the reason.

Again, this is not blocking me in any part of the dev but I thought it was worth it to leave a record of this here (just in case people start passing multiple functions into one cap grant in the future and one of those functions actually commit an entry).

**Comment by Connoropolous** [comment]
It isn't just remote calling, but any call to the function, as I've seen in the linked PR 'unit test for signalCb' above.

**Comment by tatssato** [comment]
I see. Thanks for the clarification @Connoropolous!
