### ISSUE TITLE
ability to specify DNA by URL not path in install

### ISSUE THREAD

**Issue by zippy** [holochain/holochain#419]
Currently when installing a hApp DNA is [specified by path](https://github.com/holochain/holochain/blob/45dd3f827caea18f41f77486ca2c37149a18b4ca/crates/types/src/app.rs#L29) It would be really good if we could specify by URL and have holochain download it.

**Comment by maackle** [comment]
Actually what we want to do is have holochain accept the bytes of the DNA directly, rather than have holochain fetch it from anywhere. The thing driving Holochain should be responsible for fetching and providing the DNA so that Holochain doesn't have to be concerned with those details.

**Comment by maackle** [comment]
Created #421 to reflect this, closing this issue

**Comment by maackle** [comment]
Reopening in light of the fact that browsers may have a hard time corralling billions of bytes over websocket

**Comment by ThetaSinner** [comment]
This is supported when installing a happ or webhapp https://github.com/holochain/holochain/blob/develop/crates/mr_bundle/src/bundle.rs#L141. Closing as done
