### ISSUE TITLE
Holochain should accept DNA as bytes, not as a file path

### ISSUE THREAD

**Issue by maackle** [holochain/holochain#421]
#419 points out that [DNAs can only be installed by passing in a file path](https://github.com/holochain/holochain/blob/45dd3f827caea18f41f77486ca2c37149a18b4ca/crates/types/src/app.rs#L29), but what we really want is for Holochain to accept the actual bytes of the DNA and not be responsible for fetching anything. That way, whatever UI is driving Holochain can fetch DNAs any way it wants to.

**Comment by zippy** [comment]
I think there's problem with this when the UI for managing the admin is a browser. It means that it pushes the responsibility of loading large DNA data blobs into browser memory and then passing that back over to holochain.  I don't think that can be relied on to work.

**Comment by maackle** [comment]
Totally true
