### ISSUE TITLE
Document the specification for a CHC implementation

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain#4212]
The rustdoc describes the Holochain implementation and the [design doc](https://hackmd.io/@hololtd/HynX6a6j9?type=view#Chain-Head-Coordinator-usage-in-Holochain) doesn't explicitly describe the requirements for an implementation.

Something along the lines of the [sbd spec](https://github.com/holochain/sbd/blob/main/spec.md) would be useful for pinning down what a CHC implementation should do. That would give us a reference point between a test implementation for WT and the Holo implementation that we can treat as a source of truth.

**Comment by abe-njama** [comment]
Closed by #4216
