### ISSUE TITLE
[BUG] `hc dna pack --dylib-ios` does not set dylib key in dna manifest

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain#4254]
**Describe the bug**
Running `hc dna pack` with the flag `--dylib-ios` build and seriailizes the wasms and saves them to .dylib files, but it does not include the paths of those files in the dna manifest, and thus they are not used.

**Expected behavior**
The dna manifest should include a key `dylib: path/to/file.dylib` for each zome

**System information:**
 - OS: n/a
 - Browser: n/a
 - Holochain and HDK Version: 0.3.2

**Steps to reproduce**
- `hc dna pack --dylib-ios dnas/mydna/workdir`
- `hc dna unpack /dnas/mydna/workdir/mydna.dna`
- View the manifest of the unpacked dna

**Screenshots**
n/a

**Additional context**
n/a

**Comment by mattyg** [comment]
I'm also not sure if the pre-compiled wasms will execute on iOS, as we are not telling wasmer to compile the wasm for a specific target.

**Comment by mattyg** [comment]
We may even want to consider disabling this feature behind a feature flag until we decide its worthwhile to implement it fully -- given that we are integrating a wasmer interpreter that superceeds the original need for this feature, we may end up wanting to remove it entirely.

**Comment by jost-s** [comment]
Re-open or create new issue when there's a pull.
