### ISSUE TITLE
hc-fmt-all command doesn't seem to work

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#429]
In nix-shell, `hc-fmt-all` command doesn't seem to run

<img width="949" alt="Screen Shot 2020-10-21 at 1 21 52 PM" src="https://user-images.githubusercontent.com/1409121/96755270-7eeba680-13a0-11eb-86ca-61eb4819a867.png">

**Comment by Connoropolous** [comment]
Update on this... it actually just APPEARS not to work, according to the console output, but it does actually perform the formatting.

**Comment by freesig** [comment]
There's also `hn-rust-fmt` which is what I use. @steveeJ maybe we don't need both? Unless I'm missing the difference between them.

**Comment by ThetaSinner** [comment]
There is now just one way (that I know of) to format the project

```shell
nix build -L --override-input holochain . .#build-holochain-tests-static-fmt
```

This does not output the error that it used to about failing to find targets.

I'm going to close this issue as resolved but feel free to respond or open another issue if I'm missing something
