### ISSUE TITLE
Assess Sharding feature flag feasibility

### ISSUE THREAD

**Issue by jost-s** [holochain/holochain#4332]
Refer to #4326

**Comment by jost-s** [comment]
As a starting point, set arcs to full and set the threshold to u32::MAX for example to prevent sharding to kick in.

**Comment by ThetaSinner** [comment]
Ideally, we want to support either full or empty arc when the feature flag is forcing behavior. That lets us still use zero arc nodes when arc resizing is disabled

**Comment by maackle** [comment]
Simple idea: https://github.com/holochain/holochain/pull/4344

Still allows people to go to zero arc, or even to enable sharding altogether, but it's not really terrible if they do. We just want to protect the default user from sharding for now.
