### ISSUE TITLE
Assess Rate Limiting feature flag feasibility

### ISSUE THREAD

**Issue by jost-s** [holochain/holochain#4333]
Refer to #4326

**Comment by maackle** [comment]
There is no significant logic around rate limiting, only placeholders in public interfaces, and that is a single `u8`. Doesn't seem worth removing, and there is actually benefit in keeping it around, to let the placeholder continue to hold a place for the future feature. I am not the only one of this opinion.

**Comment by maackle** [comment]
If we agree with the above, then this issue can be closed

**Comment by ThetaSinner** [comment]
@ThetaSinner to open new issues to complete this feature

**Comment by jost-s** [comment]
Are there definitely not any conditional code branches for entry weights?

**Comment by ThetaSinner** [comment]
Not really, it's just threaded through in many many places and I believe it's not used for anything. We didn't get to disabling this so I'm just going to close this issue
