### ISSUE TITLE
Assess HDK functions feature flag feasibility

### ISSUE THREAD

**Issue by jost-s** [holochain/holochain#4334]
Refer to #4326

**Comment by maackle** [comment]
Let's get more specific about this? Which HDK functions are up for consideration?

**Comment by maackle** [comment]
One high-level consideration is, if we flip off certain HDK functions, do we also want to flip off as much code as possible behind it? I assume so.

As for actually just disabling the HDK functions, it's just a matter of removing the definitions [here](https://github.com/holochain/holochain/blob/74887c9a7f9f5d523123653d02d3b13e42a5128b/crates/holochain_zome_types/src/zome_io.rs#L32) and [here](https://github.com/holochain/holochain/blob/74887c9a7f9f5d523123653d02d3b13e42a5128b/crates/holochain/src/core/ribosome/host_fn.rs#L59)

#### block/unblock agent

We still need the blocking functionality for enforcing validation rejections, so we can't disable that. The block database table, and the functionality for blocking will remain, we can just disable the HDK function that exposes it

#### crypto operations

I don't see much benefit in disabling these, they're pretty much hardwired to libsodium, right?

#### agent key lineage

This should just continue to return a singleton list with the current agent key. Better if people start building with this in mind, we're not saving on complexity by removing this call.

#### is same agent

Same rationale here, this should just always return false, unless the two agents being compared have the same key

#### schedule

We can straightforwardly disable all scheduling codepaths by following the `ScheduledFn` type, of which there are only 19 instances. And scheduled functions can include a lot of complexity

#### sleep

not implemented, can be removed

#### countersiging_session_times/start countersigning session

I'm surprised we didn't discuss disabling countersigning before, when we were looking at things to remove complexity. This deserves its own topic.

**Comment by maackle** [comment]
modify macros to include `unstable` keyword, which adds `cfg(feature = "unstable-[hdk|hdi}-functions")`

make everything unstable except for the crypto functions
