### ISSUE TITLE
Assess pre-bundled wasms feature flag feasability

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain#4367]
The feature for including pre-bundled wasms is incomplete and possibly not working fully (see #4254). Its original goal (enabling holochain apps on ios) is also fulfilled by including the wasm interpreter (#4206). 

We may want to disable this functionality behind a feature flag until we can revisit it and ensure it is implemented fully. Or else consider it superceeded by #4206 and not necessary.

**Comment by ThetaSinner** [comment]
- Deprecate in the CLI tool docs, and print a warning if it's populated during bundling
- Same in the ribosome if this field is found in use, print a warning

Do this on 0.5 and backport to 0.4. Remove as part of 0.5?
