### ISSUE TITLE
Decide what to do with the tx2-based code which no longer works and has to be rewritten or removed

### ISSUE THREAD

**Issue by maackle** [holochain/holochain#4392]
This PR removes tx2, and comments out all code which no longer works without tx2: https://github.com/holochain/holochain/pull/3225

And this PR is based on that one, and removes all commented code from the previous PR (and this one passes CI): https://github.com/holochain/holochain/pull/4369

Decisions need to be made about what will be salvaged.

**Comment by zippy** [comment]
closing because this is all deprecated by kitsune2
