### ISSUE TITLE
[Enhancement] Specify a name when emitting an App Signal

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain#4428]
When emitting a signal, pass both the payload bytes and a string name, such that when an app signal is received it can always be matched by the name string, without first decoding the payload.

From the HDK Wish List https://github.com/holochain/holochain/issues/889#issuecomment-966531159
> An expected `Payload` struct type in rust for zomes `{ name: string, data: any} `where we can get the signal name and than arbitrary data with any structure

**Comment by jost-s** [comment]
This can be achieved with app data that contains name tags. Docs to be enhanced for signals.

**Comment by jost-s** [comment]
If name matching is required for some use case prior to decoding, please re-open.
