### ISSUE TITLE
Make Kitsune P2P into its own workspace within the Holochain repository

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain#4435]
We want to extract Kitsune P2P into its own repository at some point. It already has a reasonably good separation from Holochain and with the API changes we're looking to make, it should be possible to work on and test Kitsune separately from Holochain. We also believe it will be useful in its own right, so there is extra motivation to separate it out.

AC:
- [ ] Kitsune P2P should be its own Cargo workspace
- [ ] There is a way to release Kitsune P2P crates
- [ ] The existing release automation for releasing Holochain crates is still working
- [ ] Holochain functional tests can be run against the latest Kitsune PP2 code with minimal developer friction

**Comment by jost-s** [comment]
not to be implemented any more
