### ISSUE TITLE
[Enhancement] Ensure conductor refuses to start if using an already existing, incompatible data directory created from a newer version

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain#4437]
Prevent a user from unintentionally corrupting their data directory under the following condition:

- User runs holochain version X
- User runs newer holochain version Y with the same data directory, holochain modifies the data directory so it is compatible with version Y
- User runs holochain version X again

Even if versions X & Y are semver compatible, and backwards compatible, they will not be forwards compatible. Holochain should recognize this and fail to launch or panic if the data directory has an incompatible future format.

**Comment by ThetaSinner** [comment]
I've created a duplicate here -> #4472

Hadn't spotted this one when I did it, my bad. Happy to merge content onto here if you think my suggestion would be an acceptable first solution?

**Comment by mattyg** [comment]
Yes that solution sounds good. I'll close this as duplicate
