### ISSUE TITLE
crates/keystore/README.md out of date

### ISSUE THREAD

**Issue by zippy** [holochain/holochain#445]
https://github.com/holochain/holochain/tree/develop/crates/keystore/README.md

references `holochain_crypto` which is no more...

**Comment by abe-njama** [comment]
Updating the correct URL here:

https://github.com/holochain/holochain/blob/develop/crates/holochain_keystore/README.md

@jost-s this is the crate whose readme is out of date.

**Comment by jost-s** [comment]
@neonphog Is this README not generated from the rust docs?

**Comment by jost-s** [comment]
@neonphog The idea is to add those README generations to a CI eventually.

But right now, why I'm asking is that the example on docs.rs is up to date https://docs.rs/holochain_keystore/0.0.37/holochain_keystore/. So did this README generation fail or not happen yet?

**Comment by neonphog** [comment]
@jost-s - my guess is I manually copied in that code to that particular reamde, but I don't remember for certain.

**Comment by jost-s** [comment]
@neonphog Alright. I would assign this issue to you then and ask you to copy it again =)

**Comment by neonphog** [comment]
@jost-s - I'm happy to delete anything that could get out of date, like the version / code example. I don't want to just replace what's out of date now with something that'll be out of date later. Until we're willing to invest in the automation.

**Comment by jost-s** [comment]
Okay, I can include that as part of the cargo readme task.

**Comment by jost-s** [comment]
@abe-njama @neonphog With the upcoming release this will be resolved.

**Comment by jost-s** [comment]
Done https://github.com/holochain/holochain/pull/1411/files#diff-0a5b06bc1fbd769b715e6e667b0dcb8dda8026a6ef318b795b072a4d6c393eb5
