### ISSUE TITLE
[BUG] `sysinfo` v0.30 will need to be bumped

### ISSUE THREAD

**Issue by DrewMcArthur** [holochain/holochain#4496]
**Describe the bug**
A heads up that due to https://github.com/GuillaumeGomez/sysinfo/issues/1392, `sysinfo` crate dependencies will likely need to be bumped.  since libc v0.2.165, that crate won't build.  there's a PR open that fixes the issue, but i'm assuming hc will need to bump versions to address failing builds.

**Expected behavior**

**System information:**
 - OS: macOS
 - Browser: safari
 - Holochain and HDK Version (run `hn-introspect` as well as `holochain --build-info` 
 from the nix shell and paste output): 0.3.5

**Comment by matthme** [comment]
Yes, I worked around it for now by explicitly pinning `libc` to 0.2.161 which you can do with
```
cargo update --precise "0.2.161" -p libc
```

**Comment by ThetaSinner** [comment]
We released 0.3.6, 0.4.0-rc.2 and 0.5.0-dev.8 this week which contain an upgrade of `sysinfo` for all the current versions of Holochain. 

I believe this resolves the issue. We are still in the process of updating Holonix for the dev release on 0.5 but for 0.3 and 0.4 this fix should be visible now

**Comment by DrewMcArthur** [comment]
`cargo install holochain_cli` (which was broken before because of this) works now, thank you!

**Comment by ThetaSinner** [comment]
Fantastic! Good to hear that's working now :) Thank you for your report
