### ISSUE TITLE
MDB_MAP_FULL when commiting more than 40MB of entries

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#454]
I get this error whenever I try to commit more than 40MB (more or less) of entries in the [file-storage-module](https://github.com/holochain-open-dev/file-storage-module)

```
{
  type: 'error',
  data: {
    type: 'internal_error',
    data: 'Workspace error: Workspace error: Error interacting with the underlying LMDB store: lmdb error: MDB_MAP_FULL: Environment mapsize limit reached'                               
  }
}
```

**Comment by maackle** [comment]
We've currently got the LMDB database hardcoded at 100MB with no way to dynamically expand it yet. It hasn't been a high enough priority to allow for dynamic expansion yet.

**Comment by freesig** [comment]
@guillemcordoba do you have a need for this or can it wait a little as we will be making some changes to the db soon that might allow us to sidestep this entirely

**Comment by guillemcordoba** [comment]
No problem, no need for this urgently, thanks.

**Comment by ThetaSinner** [comment]
@guillemcordoba Is this still relevant now that LMDB has been replaced or do you still run into issues trying to store larger amounts of data in one go?

**Comment by guillemcordoba** [comment]
No this is not relevant anymore.
