### ISSUE TITLE
`remote_call` should function as bridge across DNAs (not just zomes)

### ISSUE THREAD

**Issue by JettTech** [holochain/holochain#460]
Request: Expand `remote_call` functionality to act as a bridge between DNAs (...or create an alternative bridging mechanism). 

Pull/Context: Holo Hosting - Currently, the holo-hosting-app dna depends on a bridge-style functionality in order to directly call and set happ bundle preferences in the servicelogger dna associated with that happ bundle.

**Comment by freesig** [comment]
I believe this might create issues as it allows dnas from outside your network to message you without needing to actually be on the dht (which means there's no security checks).
You can use `call` to do this locally. Do you need this to work across the network?

**Comment by ThetaSinner** [comment]
@JettTech any thoughts on the question above? 

Or alternatively, is this still an issue for you? If it is and there's a workaround in place it would be good to get the work required to clean this up written up and prioritised.
