### ISSUE TITLE
hc-merge-test fails!

### ISSUE THREAD

**Issue by the-a-man-006** [holochain/holochain#469]
**failures:
    conductor::compat::tests::test_build_conductor_from_legacy_regression
    core::workflow::sys_validation_workflow::tests::sys_validation_workflow_test**

Is this expected? Have I got something wrong?

**Comment by the-a-man-006** [comment]
**test result: FAILED. 201 passed; 2 failed; 23 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p holochain --lib'**

**Comment by iGwadaa** [comment]
I have the same error but only for "core::workflow::sys_validation_workflow::tests::sys_validation_workflow_test".
I'm on archlinux

**Comment by the-a-man-006** [comment]
Have you been able to run the demo 'elemental-chat' app? For me the tests failed, I guess partly due to the "bad-conductor" failure mentioned above...

**Comment by iGwadaa** [comment]
Hmmm.... in the list of the last commits there are a marker to see if the compilation of Holochain (by "hc-merge-test") works or not. So we can "git clone" a version that is compilable.

You can access to the list from here https://github.com/holochain/holochain :
![there](https://user-images.githubusercontent.com/30246773/98927246-9407b100-24d8-11eb-83b9-f66064abc378.png)

Here are the markers :
![there](https://user-images.githubusercontent.com/30246773/98927632-14c6ad00-24d9-11eb-90c9-ad6e4ad191ce.png)

And you can get the right version with clicking on this button :
![there](https://user-images.githubusercontent.com/30246773/98927787-48a1d280-24d9-11eb-9c59-c1320f0f80e5.png)

I guess you can mark the issue as resolved.

**Comment by iGwadaa** [comment]
Also, i believe the "core::workflow::sys_validation_workflow::tests::sys_validation_workflow_test" failure is about OS detection. Maybe this is not a problem.

**Comment by maackle** [comment]
We do have a few flaky tests that mostly pass but occasionally fail. Is this what you're seeing? Or is it always failing for you?

**Comment by abe-njama** [comment]
@the-a-man-006 We recently carried out a clean up of the flaky tests. Have you still been experiencing test failures?

**Comment by ThetaSinner** [comment]
@the-a-man-006 I'm closing this as `test_build_conductor_from_legacy_regression` no longer exists and `sys_validation_workflow_test` is behaving like it should for me and on CI. 

Please feel free to open a new issue if you are still seeing unexpected test failures.
