### ISSUE TITLE
(25dae14560997bb446b93e3d76fca293c67775da) hc-merge-test fails (supposed to not fail for this version)

### ISSUE THREAD

**Issue by ghost** [holochain/holochain#477]
hc-merge-test :
Failure on :
core::workflow::sys_validation_workflow::tests::sys_validation_workflow_test

Inconsistent failures on :
core::workflow::publish_dht_ops_workflow::tests::test_sent_to_r_nodes::_Xn_Yn

**Comment by iGwadaa** [comment]
hc-merge-test :
Failure on :
core::workflow::sys_validation_workflow::tests::sys_validation_workflow_test

Inconsistent failures on :
core::workflow::publish_dht_ops_workflow::tests::test_sent_to_r_nodes::_1_1
core::workflow::publish_dht_ops_workflow::tests::test_sent_to_r_nodes::_1_10
core::workflow::publish_dht_ops_workflow::tests::test_sent_to_r_nodes::_1_100

core::workflow::publish_dht_ops_workflow::tests::test_sent_to_r_nodes::_100_10 ?
core::workflow::publish_dht_ops_workflow::tests::test_sent_to_r_nodes::_100_100 ?

Testing 100_10 and 100_100

**Comment by freesig** [comment]
Given this users account has been deleted and this is passing on current develop I'm going to close this. I know we still do have some flaky tests and hopefully this will be resolved with some new test utilities that are coming with better shutdown handling.
