### ISSUE TITLE
HDK wish list

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#479]
These are issues that I think create some friction when developing, nothing major I think (in general the experience with the HDK is really good). It's likely that there is some way to work around some of them I haven't realized, so @thedavidmeister if that's the case please tell me and I'll remove it from the list.

- Various types should be made available directly in the prelude as their usage is very frequent:
  - `hdk3::prelude::timestamp::Timestamp` ([example](https://github.com/holochain-open-dev/calendar-events-module/blob/master/zome/zomes/calendar_events/src/calendar_event.rs))
  - `hdk3::prelude::link::Link` ([example](https://github.com/holochain-open-dev/profiles-module/blob/main/zome/zomes/profiles/src/profile.rs))
- Easier conversion between `AgentPubKey` and `EntryHash`, or alternatively let `create_link` receive an `AgentPubKey`. [Example](https://github.com/holochain-open-dev/profiles-module/blob/main/zome/zomes/profiles/src/profile.rs#L79) of what we need to do right now.
- Be able to do `query` with the entry type as a string. Right now we need to pass  as parameter the `EntryDefIndex`, which forces us to do something like [this](https://gist.github.com/guillemcordoba/442e0b1f58d2c2c3b96cfe9e06bff60f).
- Have structs derived with `#[hdk_entry]` implement some sort of `HdkEntry` trait, so that I can write a function like [this](https://gist.github.com/guillemcordoba/1b34ee361ed92de81f2c9cda24b88aa9).

**Comment by thedavidmeister** [comment]
aight, i've got these chalked up thanks

**Comment by guillemcordoba** [comment]
I'm going to add the exports we are missing here:

- `use hdk3::prelude::metadata::EntryDetails;`

**Comment by maackle** [comment]
@guillemcordoba FYI there are direct From impls between `EntryHash` and `AgentPubKey` https://github.com/holochain/holochain/blob/2a1085a3413d4d0f71961fc68c9cf0ba2e0b50a3/crates%2Fholo_hash%2Fsrc%2Fhash_type%2Fprimitive.rs#L135

**Comment by guillemcordoba** [comment]
All good now!

**Comment by artbrock** [comment]
> All good now!

@guillemcordoba Does that mean ALL your items in the original ticket are addressed?  I wasn't sure about the last one. But it might have been addressed in the recent changes around entry_defs and types for @pospi
