### ISSUE TITLE
hc-install missing

### ISSUE THREAD

**Issue by programmarchy** [holochain/holochain#545]
I'm on develop (commit 047531c4ef404e98006fa6bc3ecc1aa4f9138a6a)

After checking out and running nix-shell, I can no longer run hc-install.

Currently bisecting to see when this may have broken...

**Comment by programmarchy** [comment]
broke on 8804ddf2d4fc6261ca1fc17afab4a870c6dd55b4
verified working on bc1e9b98cc30a0dac8bf8d9a3eee5cc3c5e4e218

**Comment by zippy** [comment]
Hi @programmarchy this was on purpose.  hc-install was causing havoc for some folks in that it would install holochain in unpredictable places depending on the configuration.   For now if you want to install holochain locally I recommend using:

```
cargo install --path crates/holochain
cargo install --path crates/dna_util
```
And make sure that you've added the `.cargo/bin` of your holochain repo to your path which is where it will get built.
There's a bunch of good work being done on holonix right now that will ensure correct building and availability of holochain direct after `nix-shell` invocations.

Thanks for the report!
