### ISSUE TITLE
Investigation / possible limiting bug: lifetime bounds in create/update_entry HDK methods

### ISSUE THREAD

**Issue by pospi** [holochain/holochain#548]
Hi everyone :)

I have a complex set of issues presenting itself in the creation of an abstract helper library for HDK developers. I'd like to open by saying that [the new version of this library](https://github.com/holo-rea/holo-rea/tree/feature/167-holochain-rsm/lib/hdk_graph_helpers/src) is *much* cleaner and easier to understand than the previous one. Really enjoying the experience of building with the new HDK- kudos! The `Path` construct, in particular, has greatly simplified a lot of previous subtly-differing "anchor patterns" I was using.

The stage I'm at is that everything is passing compiler checks, save two things. I believe these two things are to do with these trait bounds in the HDK core methods `create_entry` and `update_entry`:

```rust
where
    EntryDefId: From<&'a I>,
    SerializedBytes: TryFrom<&'a I, Error = SerializedBytesError>,
```

I'm at the limits of my Rust experience in understanding this (specifically lifetimes & borrowing), so perhaps to explain why I believe this is a problem with core it's best to build from first principles up to the point at which the error started blocking me; and folks can follow along with my assumptions and we can decide whether these limitations I'm hitting justify any changes or not.

To keep things simple, I'll focus on entry creation. The first goal was to abstract away some of the common functionality I would need in dealing with reading and writing entries, by creating my own `create_entry` wrapper:

```rust
use hdk3::prelude::create_entry as hdk_create_entry;

pub fn create_entry<'a, E: 'a>(
    entry_struct: &'a E,
) -> HdkResult<(HeaderHash, EntryHash)>
    where EntryDefId: From<&'a E>,
        SerializedBytes: TryFrom<&'a E, Error = SerializedBytesError>,
{
    let entry_hash = hash_entry(&entry_struct)?;
    let header_hash = hdk_create_entry(&entry_struct)?;

    Ok((header_hash, entry_hash))
}
```

So far, so good- I have a nice clean, memory-efficient API. The trait bounds I've had to add here are a little verbose, but that's to be expected and it all seems to work fine-

```rust
#[cfg(test)]
mod tests {
    #[hdk_entry(id="test_entry")]
    #[derive(Clone, PartialEq, Debug)]
    pub struct TestEntry {
        field: Option<String>,
    }

    #[test]
    fn test_entry_creation() {
        let entry = TestEntry { field: None };
        let (header_hash, entry_hash) = create_entry(&entry).unwrap();
        // ...
    }
}
```

Now- can I implement some [higher-order abstraction](https://github.com/holo-rea/holo-rea/blob/cff4ed0/lib/hdk_graph_helpers/src/record_helpers.rs#L122), one that wraps `create_entry` and potentially performs some additional logic? Indeed I can! I have to repeat those trait bounds again, but it still seems to work fine-

```rust
fn new_test_entry<'a, R: 'a>(
    entry: &'a R,
) -> (HeaderHash, EntryHash)
    where EntryDefId: From<&'a R>,
        SerializedBytes: TryFrom<&'a R, Error = SerializedBytesError>,
{
    let (header_hash, entry_hash) = create_entry(&entry).unwrap();

    (header_hash, entry_hash)
}

#[test]
fn test_entry_creation() {
    let entry = TestEntry { field: None };
    let (header_hash, entry_hash) = new_test_entry(&entry);
    // ...
}
```

In a real application though, my goal is to abstract away record management behaviour by having a creation payload separate to the input for writing an entry. *This means that the payload I pass to `create_entry` is an inner (temporary) variable*. Rewriting the higher-order helper method to perform this conversion is where lifetime errors begin to pop up (errors shown as comments):

```rust
pub struct Creation;

impl Into<TestEntry> for Creation {
    fn into(self) -> TestEntry {
        TestEntry { field: None }
    }
}

fn new_test_entry<'a, E: 'a, C>(    // <-- lifetime `'a` defined here
    create_payload: C,
) -> (HeaderHash, EntryHash, E)
    where
        C: Into<E>,
        EntryDefId: From<&'a E>,
        SerializedBytes: TryFrom<&'a E, Error = SerializedBytesError>,
{
    let entry: E = create_payload.into();

    let (header_hash, entry_hash) = create_entry(&entry).unwrap();  // <-- borrow of `entry` occurs here; argument requires that `entry` is borrowed for `'a`

    (header_hash, entry_hash, entry)    // <-- cannot move out of `entry` because it is borrowed; move out of `entry` occurs here
}   // <-- `entry` dropped here while still borrowed
```

If I make `E` cloneable, moving the value out of the function seems fine but still the borrow in `create_entry` does not seem to be released by the inner function-

```rust
fn new_test_entry<'a, E: 'a, C>(    // <-- lifetime `'a` defined here
    create_payload: C,
) -> (HeaderHash, EntryHash, E)
    where
        E: Clone,
        C: Into<E>,
        EntryDefId: From<&'a E>,
        SerializedBytes: TryFrom<&'a E, Error = SerializedBytesError>,
{
    let entry: E = create_payload.into();

    let (header_hash, entry_hash) = create_entry(&entry).unwrap();  // <-- argument requires that `entry` is borrowed for `'a`

    (header_hash, entry_hash, entry.clone())
}   // <-- `entry` dropped here while still borrowed

#[test]
fn test_entry_creation() {
    let (header_hash, entry_hash, entry): (_,_, TestEntry) = new_test_entry(Creation);

    // ...
}
```

So, all I can infer is that these lifetime bounds in `Try/From<&'a` require the borrow to last for too long. I really don't care that *"`entry` dropped here while still borrowed"*... how do I tell Rust not to care about this?

Or &mdash; is there an alternate pattern for polymorphism and abstraction here that I should be exploring? Is this not in fact an idiomatic Rust pattern? Should I investigate use of a closure-based API for managing entry abstractions?

Any help is greatly appreciated. Once I have moved through [these](https://github.com/holo-rea/holo-rea/blob/cff4ed0/lib/hdk_graph_helpers/src/record_helpers.rs#L138) two lifetime [errors](https://github.com/holo-rea/holo-rea/blob/cff4ed0/lib/hdk_graph_helpers/src/record_helpers.rs#L181), the rest of the RSM conversion I'm working on should fall into place rapidly.

**Comment by freesig** [comment]
Hi @pospi 
Thanks for creating such a detailed issue. This will be helpful in writing tests to ensure the API works for your usecase.
After have a think through this I think we can remove the lifetimes altogether which should make this much simpler.
I'll update here once we have figured out exactly how this should work

**Comment by pospi** [comment]
I had a bit of a go at this today since it's blocking me from making any further progress. Seems like a hard one to solve:

- Using `'static` lifetime bounds on the parameters doesn't seem to change anything (same error for `'static` as for `'a`).
- You can't omit the lifetimes because of the requirement to serialize from a reference of the original data.

The only way to make this work may be to consume the values, or to bind `I: Clone` and pass cloned data to `EntryDefId::from` and `SerializedBytes::try_from`. I think it may also be worth considering if avoiding cloning is an optimisation worth making- looking at the internals of `holochain_serialized_bytes::encode` it appears to be allocating temporary memory anyway.

This bug doesn't affect decoding, so no issues there.

**Comment by pospi** [comment]
A note for those who come here looking to push the envelope on memory-optimised code: data always eventually has to be cloned when passing through the WASM / Host membrane. 

@thedavidmeister says-

> we clone the data internally so the allocator can safely forget it, the old way had two clones one to serialize and one to forget, this way just takes ownership of literal entries and either ownership or borrow of something that serializes.

This means that the *only* way to write the above helper is as-

```rust
pub fn create_entry<I: Clone, E>(
    entry_struct: I,
) -> GraphAPIResult<(HeaderHash, EntryHash)>
    where HdkError: From<E>,
        HdkEntry: TryFrom<I, Error = E>,
        Entry: TryFrom<I, Error = E>,
{
    let entry_hash = hash_entry(entry_struct.clone())?;
    let header_hash = hdk_create_entry(entry_struct)?;

    Ok((header_hash, entry_hash))
}
```

i.e. the cloning of `entry_struct` in order to both hash *and* write the entry is unavoidable, and as optimised as possible. In practise this probably only presents a problem to applications dealing with large amounts of binary data, and the memory spikes are probably confined to 32MB since 16MB is the payload size limit for JSONRPC calls into a Holochain node.
