### ISSUE TITLE
macos compilation issues (numerous users have reported on forum and discord)

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#554]
If I use `holonix`, and try to run inside it

```
REV=15dd4ba75ae02d02b48a05da012e8fbeabe2f48e

cargo install --force holochain \
  --git https://github.com/holochain/holochain.git \
  --rev $REV
```

this will lead to producing an error like this:
```
Compiling lair_keystore_client v0.0.1-alpha.8
   Compiling holochain_wasmer_host v0.0.50
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-L" "/nix/sto 
...
...
...
re/c1spfc6wbipbk64akin9lsf3hihf12gy-rust/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-f0244eb4ede32fb8.rlib" "-framework" "Security" "-framework" "Security" "-lSystem" "-lresolv" "-lc" "-lm"
  = note: ld: framework not found Security
          clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error

error: could not compile `lair_keystore_client`.
```

This is being experienced by myself on MacOS Big Sur, and also Tats reports seeing it on Catalina. 

There is a post by Kristofer on the forum on this as well: 
https://forum.holochain.org/t/holochain-rsm-on-macos/4435/5
and a post by @tatssato on Discord about this as well:
https://discord.com/channels/727959104777224303/728647693244694648/788278575916777472

**Comment by steveeJ** [comment]
@Connoropolous please share some context around this issue, specifically how you set up `holonix`.

**Comment by Connoropolous** [comment]
sure :) that would be config.nix and default.nix here: https://github.com/h-be/acorn-hc

**Comment by steveeJ** [comment]
@Connoropolous Work for RSM support in https://github.com/holochain/holonix/ is currently in progress. What you could try in the meantime is run the nix-shell in a local clone in this repository as [pointed out in the README](https://github.com/holochain/holochain#using-nix-shell-on-a-local-clone). There's currently no documentation for it as it's also under heavy development and not finalized, so here's a short description. The *happDev* shell effectively provides binaries in PATH for `holochain` and `dna-util`. `lair-keystore` is automatically installed using `cargo install` on-demand, which we currently consider acceptable for development environments.

**Comment by abe-njama** [comment]
@Connoropolous are you recently experiencing this issue especially with the recent improvements and support for MacOS?

**Comment by Connoropolous** [comment]
We can close this
