### ISSUE TITLE
Link is only available by zoom creator!

### ISSUE THREAD

**Issue by HedayatAbedijoo** [holochain/holochain#563]
In PeerShare happ, I am facing this scenario, 

I am adding a link from `my_address` to `file_hash` inside the `tags` zome. 
And I want to load the same link from `peershare` zome. and it is not working?
while I can just load the link form `tags` zome. 

you can see the scenario from here:
[PeerShare](https://github.com/HedayatAbedijoo/peershare/commit/0e252c9f0db4ee19498d10471abd9a3f63b61a1f
)

**Comment by freesig** [comment]
Hey @HedayatAbedijoo you can `call` into the `tags` zome from the `peershare` to get the links cross zome like that

**Comment by maackle** [comment]
@HedayatAbedijoo is this still an issue based on @freesig's comment or can we close this?

**Comment by guillemcordoba** [comment]
@pospi and me just uncovered this as well, and we don't think that calling across zomes is acceptable... You need to know the API for that zome, now you are depending on it, and you need to expose API calls just for the sake of getting the links. Also you need to do 2 get_links calls...

I think it's much better to return all the links, as they can always be filtered by zome id after the get_links call.

**Comment by maackle** [comment]
More discussion at https://github.com/holochain/holochain/issues/743

**Comment by ThetaSinner** [comment]
@HedayatAbedijoo @pospi The linked discussion is closed, can this issue be closed or is something else still needed?
