### ISSUE TITLE
Feature Request! configurable zome logging levels

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#570]
It would be super useful to have a way to just get logs from your zome out to the main log, and not have to set debug as the level of logging for holochain too, because there is so much noise. 

I just want a really simple way to get clean logs that will only or almost entirely show my zome logs. 
One solution to this problem is also adding an Option, to the hdk debug call, that lets you set the log level it will appear at. 

Right now, even the Info level is firehosing kitsune logs, such as:
```
Dec 27 18:53:00.923  INFO kitsune_p2p_proxy::tls_srv: CcL0hd: SRV: INCOMING TLS: kitsune-proxy://vU2NBBRBAxmarS-eu6f61C5pztGUU3B2b_plTj--ACU/kitsune-quic/h/45.33.73.72/p/4010/--
Dec 27 18:53:00.923  INFO kitsune_p2p_proxy::tls_srv: CcL0hd: SRV: INCOMING TLS: kitsune-proxy://vU2NBBRBAxmarS-eu6f61C5pztGUU3B2b_plTj--ACU/kitsune-quic/h/45.33.73.72/p/4010/--
Dec 27 18:53:02.862  INFO kitsune_p2p_proxy::inner_listen: CcL0hd: wishes to proxy through VYgwCr:kitsune-proxy://VYgwCrh2ZCKL1lpnMM1VVUee7ks-9BkmW47C_ys4nqg/kitsune-quic/h/kitsune-proxy.harris-braun.com/p/4010/--
Dec 27 18:53:03.039  INFO kitsune_p2p_proxy::inner_listen: Proxy renewed for ProxyUrl { full: Url2 { url: "kitsune-proxy://VYgwCrh2ZCKL1lpnMM1VVUee7ks-9BkmW47C_ys4nqg/kitsune-quic/h/kitsune-proxy.harris-braun.com/p/4010/--" }, base: Url2 { url: "kitsune-quic://kitsune-proxy.harris-braun.com:4010" } }
Dec 27 18:53:18.040  INFO kitsune_p2p_proxy::inner_listen: CcL0hd: wishes to proxy through VYgwCr:kitsune-proxy://VYgwCrh2ZCKL1lpnMM1VVUee7ks-9BkmW47C_ys4nqg/kitsune-quic/h/kitsune-proxy.harris-braun.com/p/4010/--
```

**Comment by neonphog** [comment]
@Connoropolous - I know this issue was filed a while ago, but have you tried adding [more complex directives to the RUST_LOG environment variable](https://docs.rs/tracing-subscriber/0.3.15/tracing_subscriber/struct.EnvFilter.html)?

**Comment by Connoropolous** [comment]
Yeah well theres now also logging levels for the WASM, via WASM_LOG

In general, there are ways to tune it via the, as you say, more complex directives. I think back then I was thinking of keyword "simple" and just black or white. "Dont give me holochain logs, give me wasm logs"

**Comment by ThetaSinner** [comment]
@Connoropolous Have you settled on a solution for getting logs when you need them? If so it would be useful to know what and make sure that has been / does get fed back into holochain documentation.

Otherwise, is something still lacking that could be improved?

**Comment by Connoropolous** [comment]
Im too out of the loop to know or comment at the moment. Feel free to close, or seek feedback from other active devs as you see fit
