### ISSUE TITLE
libssl-dev is required on ubuntu

### ISSUE THREAD

**Issue by freesig** [holochain/holochain#574]
Tried to build on a fresh Pop Os and pkgconfig can't find openssl.
This is fixed by:
`sudo apt-get install libssl-dev`
Should maybe add this to the readme

**Comment by steveeJ** [comment]
i don't see any section in the current README on development environments beyond the nix-shell that we maintain. i suggest we keep it that way for now as it'll be difficult to keep up to date unless we set up a CI job for it.

**Comment by ThetaSinner** [comment]
@freesig Did you manage to get a build using the Nix environment? If so I'm inclined to agree with @steveeJ that we stick with supporting Nix and try to avoid getting into specifics of environment configuration otherwise, then we can close this.
