### ISSUE TITLE
Running selected test from holochain crate requires explicit compilation of wasms before.

### ISSUE THREAD

**Issue by peeech** [holochain/holochain#591]
### Description
When running a selected test from `crates/holochain`, for example:
```
cargo test -- --exact conductor::api::api_external::admin_interface::test::register_list_dna_app
```
I get an error:
```
running 1 test
test conductor::api::api_external::admin_interface::test::register_list_dna_app ... FAILED

failures:

---- conductor::api::api_external::admin_interface::test::register_list_dna_app stdout ----
FATAL PANIC PanicInfo {
    payload: Any,
    message: Some(
        Wasm: "/root/holochain/.wasm_target/wasm32-unknown-unknown/release/test_wasm_foo.wasm" was not found. Maybe you need to build the test wasms
        
                Run `cargo build --features 'build_wasms' --manifest-path=crates/holochain/Cargo.toml`
                or pass the feature flag to `cargo test`
                : Os { code: 2, kind: NotFound, message: "No such file or directory" },
    ),
    location: Location {
        file: "crates/test_utils/wasm/./src/lib.rs",
        line: 214,
        col: 25,
    },
}
thread 'conductor::api::api_external::admin_interface::test::register_list_dna_app' panicked at 'Wasm: "/root/holochain/.wasm_target/wasm32-unknown-unknown/release/test_wasm_foo.

        Run `cargo build --features 'build_wasms' --manifest-path=crates/holochain/Cargo.toml`
        or pass the feature flag to `cargo test`
        : Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/test_utils/wasm/./src/lib.rs:214:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    conductor::api::api_external::admin_interface::test::register_list_dna_app

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 226 filtered out
```
Following cargo's advice and running `cargo build --features 'build_wasms' --manifest-path=crates/holochain/Cargo.toml` fixes an issue and I can successfully run selected test.

#### How to reproduce
Check out rev `9180f0841419d71f5862161209d86e6c9af7bc27` of holochain and run `cargo test register_list_dna_app`.

### Environment:
- Observed on both Darwin and Linux
- holochain rev `9180f0841419d71f5862161209d86e6c9af7bc27`

**Comment by ThetaSinner** [comment]
You can get the test wasms built with `nix build -L --override-input holochain . .#build-holochain-tests-unit-wasm` and I think that this will happen under `build-holochain-tests-unit-all` too. However, if you're running with Cargo there's no link between the wasms being built/up-to-date and the tests that depend on them. I think you could run specific tests by providing a filter to `nextest` through `build-holochain-tests-unit-all` but I'd have to defer to @steveeJ for how to do that if that's right?

@steveeJ @jost-s do you have a view on how this should work or should be done?

**Comment by jost-s** [comment]
This is how we're doing it as well, build the wasms and then run the tests.

@peeech Do you expect the wasms to be built automatically if necessary prior to running the tests?
