### ISSUE TITLE
Networking performance degrades over time

### ISSUE THREAD

**Issue by alastairong** [holochain/holochain#598]
Issue:
- Networking performance degrades over time - signals are no longer received and gossip becomes patchy / slow. It can become noticeably less reliable within 2 hours and after a day or two may not receive any signals at all
- I suspect this is a holochain networking issue because:
  - UI still able to make zome calls to the Holoport reliably
  - Holoport returns zome call successes to UI (e.g. confirmation of signals sent)
  - Restarting holochain fixes issues
  - Proxy server does not need restarting / intervention
  
Urgency:
- Low - we can use interim solutions for now (e.g. having holochain on a regular restart timer).

**Comment by artbrock** [comment]
We'll address this after our database changeover when we actually implement our intended gossip protocols. We don't want to invest much effort optimizing/troubleshooting code we're replacing.

**Comment by abe-njama** [comment]
@alastairong Reviving this thread to check in whether this is still a recurring issue with the recent versions of Holochain.

**Comment by alastairong** [comment]
We haven't tested at any sort of scale recently so it's hard to say.
