### ISSUE TITLE
Error on Installation: hc-install command not found

### ISSUE THREAD

**Issue by toledoroy** [holochain/holochain#622]
Hi, 
Using a fresh Ubuntu (on Win10). 
Cloned the Git

Then opened the Nix Shell

```
user@DESKTOP-06MEQ70:~/holochain$ nix-shell
Using /home/roy/holochain as target prefix...
```

Then I try to run the hc-install and get this error
```
[nix-shell:~/holochain]$ hc-install
bash: hc-install: command not found
```

**Comment by mlaradji** [comment]
It looks like the `hc-install` binary was removed. See #545. 
The command can be replaced with the following:
```bash
cargo install --path crates/holochain
cargo install --path crates/dna_util
```
(from https://github.com/holochain/holochain/issues/545#issuecomment-748930146)

**Comment by toledoroy** [comment]
> It looks like the `hc-install` binary was removed. See #545.
> The command can be replaced with the following:
> 
> ```shell
> cargo install --path crates/holochain
> cargo install --path crates/dna_util
> ```
> 
> (from [#545 (comment)](https://github.com/holochain/holochain/issues/545#issuecomment-748930146))

Thank you for your response. 
It didn't seem to have worked, but I see that there have been some updates and a new procedure came out, so I'll try that
