### ISSUE TITLE
Querying for multiple entry types

### ISSUE THREAD

**Issue by robbiecarlton** [holochain/holochain#658]
Very similar to https://github.com/holochain/holochain/issues/387, it would be useful to be able to specify multiple entry types for a query. The solution would likely be the same: in ChainQueryFilter, store an `Option<HashSet<HeaderType>>` instead of `Option<EntryType>`.

**Comment by ThetaSinner** [comment]
This actually got covered by #2302 because it seemed like a good idea as suggested here. If you're happy with the changes on that PR then this will be appearing in `0.3.0`

**Comment by ThetaSinner** [comment]
This actually released in 0.2.2 in the end, I'm going to close this as complete
