### ISSUE TITLE
Question: hApp crate & JS module naming conventions

### ISSUE THREAD

**Issue by pospi** [holochain/holochain#692]
Hi (: Thought it worth sensing on this before we all start pushing things to package registries.

What kinds of naming conventions are folks using for crates of various types? Here's what I have been using & seeing; also have [had long discussions](https://forum.holochain.org/t/naming-conventions-module-patterns-for-rust-crates/1294/) with @pdaoust...

- `hdk_` as a prefix for general-purpose application library crates (crates to be used within zome WASM bundles)
- `hc_zome_` as a prefix for related crates which provide functionality for implementing a specific Holochain zome

On the JS side it seems like it's more a case of

- `hc-` as a prefix for browser library NPM modules is something I've seen in development but not yet on NPM. But it also seems it might be ambiguous as other things abbreviated `hc` exist. Should we adopt this?
- `holochain-` as a prefix for bundled UI modules is also something I've seen from @guillemcordoba - more verbose but perhaps for modules which aren't scoped to a project it could work.

Or should we keep releasing utility libraries [as org-scoped packages](https://github.com/holochain-open-dev/core-types) under the Holochain Open Dev initiative?

Discuss.

**Comment by pdaoust** [comment]
I know I'm part of the choir to which you're preaching, but those look good to me. Part of me wants to see the `hc_` prefix on general-purpose lib crates, or maybe `hc_lib_` so it's not construed as part of the official HDK?

**Comment by pospi** [comment]
I'm not against that, makes sense. I do wonder whether that unnecessarily privileges the core HDK team over other package maintainers, though. I have previously pondered whether it would make sense for `Path` to be in its own `hdk_path` crate, though I'm glad that it's not as it's a useful universal convention for everybody to be adopting.

These are the HDK libs I've needed thus far, you tell me- https://github.com/holo-rea/holo-rea/tree/4c6789c/lib

Some of them (`hdk_records`) feel as though they are equally general-utility as `hdk::Path`. Others are obviously more application-specific. But are they different kinds of things or the same kinds of things?

+1 for org-scoped packages, as well.

**Comment by guillemcordoba** [comment]
Yeah, I like these names so far. I agree with @pdaoust that `hc_` makes more sense, I would not overload `hdk` with utility libraries (e.g. `hc_utils` was its own thing and I think it was quite clear).

I would try to align rust names with js names as much as possible though. This presents a problem as crates.io doesn't do scoped packages... Right now it's not really an issue, but in the future with more variants and nuances it could be big. For example:

Crates: `hc_zome_file_storage`
NPM: `@holochain-open-dev/file-storage`

Dunno... Maybe we change the NPM one to @holochain-open-dev/hc_zome_file_storage? What do you think?

**Comment by pospi** [comment]
I think actually the relationship between Rust crates and NPM modules is likely to be indirect. (Related but that's also an issue I have with your reusable module template- it presumes each project is a single zome.)

But yeah in these 1:1 cases I think the context of `hc_zome_` and `@holochain-open-dev/` is *mostly* equivalent. Equivalent enough? But can also see cases for eg. `hc_zome_timestamp_api` + `hc_zome_timestamp_contrib_peer_witnessed` being crates used by something like `@holochain-open-dev/event-viewer`.

I think it makes sense what you're saying about the other names, so all happy with these suggestions and will change `hdk_records` to `hc_records` et al in hREA's package manifest.

**Comment by guillemcordoba** [comment]
Perfect.

> Related but that's also an issue I have with your reusable module template- it presumes each project is a single zome

Mmm interesting. With that, I'm not suggesting that all holochain projects/repos should be coded 1 zome at a time, what I am suggesting though is that if you want to build a module (UI+zome) that's reusable accross happs, the zome is the unit that I see fits best. 

Could you tell me more about this? I'd like to improve it if possible.
