### ISSUE TITLE
Provenance not found in `zome_info`

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#702]
The provenance of the caller of the function that is executing is not found in `zome_info`, or anywhere else as far as I can see.

**Comment by artbrock** [comment]
Hmm... yes... Good point, we should make the calling context available for the current zome call.

**Comment by guillemcordoba** [comment]
And also, in a bridged `call`, it would be potentially very useful to know the hash of the "caller DNA", and I think this is possible as far as the conductor goes. What do you think?

**Comment by ThetaSinner** [comment]
@guillemcordoba Is this issue still something that should be looked at?

**Comment by guillemcordoba** [comment]
No, this is solved by [`call_info`](https://docs.rs/hdk/latest/hdk/info/fn.call_info.html), although now that I see the docs they say "Trivial wrapper for __agent_info host function", and that alarms me. The provenance of who called the zome function is definitely not always the same as the agent info, for example in a bridge call across apps. So I would close this issue if:

- If the docs are wrong, the docs are fixed.
- If the docs are right and `call_info` is just a wrapper around agent_info, a proper way of getting the caller provenance is implemented.
