### ISSUE TITLE
`remote_signal` doesn't match grammar of other host functions

### ISSUE THREAD

**Issue by pdaoust** [holochain/holochain#761]
Other host functions have the grammar `verb_(adjective|noun)`, and there's an existing `emit_signal`. I propose renaming `remote_signal` to `emit_remote_signal`... I can create a PR; just want to record it as an issue somewhere first.

**Comment by artbrock** [comment]
I could be on board with SEND remote signal... Emit is to the local socket connections. Send feels more like the network function which contacts another node where they might then EMIT the signal to their UI locally.

Does that make sense to you @pdaoust ?

-art

**Comment by pdaoust** [comment]
yeah, totally. Useful distinction.

**Comment by ThetaSinner** [comment]
I'll take this one on in that case, it's a sensible suggestion and not too big a change in Holochain. Though it will be a breaking change for consumers.
