### ISSUE TITLE
hc-merge-test FAIL on MacOS 10.15

### ISSUE THREAD

**Issue by lorerave85** [holochain/holochain#766]
After clone this repo

Using nix-shell (Nix) 2.3.10

run: hc-merge-test

warning: src/apple/macos/disk.m:1:9: fatal error: 'AppKit/AppKit.h' file not found
warning: #import <AppKit/AppKit.h>
warning:         ^~~~~~~~~~~~~~~~~
warning: 1 error generated.

error: failed to run custom build command for `sysinfo v0.15.9`

Caused by:
  process didn't exit successfully: `/Users/ravello001/Documents/GithubSourceCode/holochain/target/clippy/debug/build/sysinfo-d5e213c779c7eac7/build-script-build` (exit code: 1)
  --- stdout
  TARGET = Some("x86_64-apple-darwin")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-apple-darwin")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = Some("clang")
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  running: "xcrun" "--show-sdk-path" "--sdk" "macosx"
  exit code: 0
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=x86_64-apple-darwin" "-Wall" "-Wextra" "-o" "/Users/ravello001/Documents/GithubSourceCode/holochain/target/clippy/debug/build/sysinfo-1b49d989be37fefe/out/src/apple/macos/disk.o" "-c" "src/apple/macos/disk.m"
  cargo:warning=src/apple/macos/disk.m:1:9: fatal error: 'AppKit/AppKit.h' file not found
  cargo:warning=#import <AppKit/AppKit.h>
  cargo:warning=        ^~~~~~~~~~~~~~~~~
  cargo:warning=1 error generated.
  exit code: 1

  --- stderr

  error occurred: Command "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=x86_64-apple-darwin" "-Wall" "-Wextra" "-o" "/Users/ravello001/Documents/GithubSourceCode/holochain/target/clippy/debug/build/sysinfo-1b49d989be37fefe/out/src/apple/macos/disk.o" "-c" "src/apple/macos/disk.m" with args "clang" did not execute successfully (status code exit code: 1).

**Comment by artbrock** [comment]
We've made some recent updates to Holonix to address some of the mac dependencies like clang. 

And we're about to roll out releases with the new versions.

@steveeJ Can you confirm that the new release solves this issue?  Or provide instructions for testing before the release?

**Comment by steveeJ** [comment]
@artbrock 

I don't see `hc-merge-test` related to release state.

@lorerave85 can you confirm you're trying this on the _develop_ branch? If so please make sure you're on a commit that has https://github.com/holochain/holochain/pull/717 merged in, as that fixes the most recent macOS issues I'm aware of.

**Comment by lorerave85** [comment]
Hi, now the procedure proceed more but I see an other error: Argument list too long

+ hc-test
+ export RUST_BACKTRACE=1
+ RUST_BACKTRACE=1
+ export NUM_JOBS=8
+ NUM_JOBS=8
+ export CARGO_BUILD_JOBS=8
+ CARGO_BUILD_JOBS=8
+ cargo test --manifest-path=crates/holochain/Cargo.toml --features slow_tests,test_utils,build_wasms,db-encryption -- --nocapture --test-threads 1


error: linking with `cc` failed: exit code: 1
...
 = note: clang-7: error: unable to execute command: posix_spawn failed: Argument list too long
          clang-7: error: linker command failed with exit code 1 (use -v to see invocation)

error: aborting due to previous error
error: could not compile `holochain_wasm_test_utils`

**Comment by steveeJ** [comment]
@lorerave85 could you try this again on the develop branch on any commit after https://github.com/holochain/holochain/commit/9be6dacff9a82f43eaac917617a1851829cf76b8 ?

**Comment by abe-njama** [comment]
@lorerave85 we've recently made some infrastructure improvements to support MacOS. Could you test this with the recent versions of Holochain and confirm whether you're still experiencing this issue?
