### ISSUE TITLE
[Feature Request] Ability to get the zome names of a particular Cell with `app_info`

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#774]
This would enable a lot of flexibility in making dynamic and composable UIs.

Maybe the best place for this would be with the alongside the cell info [here](https://github.com/holochain/holochain-conductor-api/blob/develop/src/api/types.ts#L10).

**Comment by pospi** [comment]
I think this might also be a useful prerequisite for the planned DNA-local zome API contracts coming as a result of discussing #743. Gives us ways of cross-referencing zome names with zome & cell IDs.
