### ISSUE TITLE
fixt crate: Inconvenient syntax limitation of `fixturator!`

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#852]
In Acorn, we have a struct like:

```rust
#[hdk_entry(id = "goal")]
#[derive(Clone, PartialEq)]
pub struct Goal {
  pub content: String,
  pub user_hash: WrappedAgentPubKey,
  pub user_edit_hash: Option<WrappedAgentPubKey>,
  pub timestamp_created: f64,
  pub timestamp_updated: Option<f64>,
  pub hierarchy: Hierarchy,
  pub status: Status,
  pub tags: Option<Vec<String>>,
  pub description: String,
  pub time_frame: Option<TimeFrame>,
  pub is_imported: bool,
}
```

It uses all these wrappers like `Option<TimeFrame>`, however when we use the `fixturator!` macro with the `constructor fn new` pattern, it can't handle `Option<TimeFrame>`. I had to do:
`type OptionTimeFrame = Option<TimeFrame>;`
and then:
```rust
fixturator!(
      Goal;
        constructor fn new(String, WrappedAgentPubKey, OptionWrappedAgentPubKey, f64, Optionf64, Hierarchy, Status, OptionVecString, String, OptionTimeFrame, bool);
    );
```

It's just unintuitive and feels awkward, and wasn't easy for me to figure out what to do. 

You can see it here:
https://github.com/h-be/acorn/blob/main/dna/zomes/projects/src/project/fixtures.rs

@thedavidmeister

**Comment by Connoropolous** [comment]
@maackle

**Comment by maackle** [comment]
@Connoropolous you might consider using the [https://docs.rs/arbitrary/1.0.1/arbitrary/](Arbitrary) trait, it has an excellent derive macro with a sensible impl for just about everything.

And then there is [contrafact](https://github.com/maackle/contrafact-rs), which I wrote to impose constraints on purely arbitrary data. It's not well documented though.

**Comment by thedavidmeister** [comment]
@Connoropolous also you did it right FYI, the type name is just being fed into `paste` so defining a type works fine

**Comment by Connoropolous** [comment]
@thedavidmeister thanks. Is there any way to make paste digest the <> of generics perhaps though? Would that be the right question to ask even?

**Comment by Connoropolous** [comment]
I realized that the problem is that the character flags for paste are `[< ... >]`  which is prbly why the generics text throws an error

**Comment by thedavidmeister** [comment]
@Connoropolous do you have suggestions for the syntax? i'm just using the TT munch pattern here https://danielkeep.github.io/tlborm/book/pat-incremental-tt-munchers.html#:~:text=A%20%22TT%20muncher%22%20is%20a,recurses%20on%20the%20input%20tail.

**Comment by Connoropolous** [comment]
@thedavidmeister i dont quite know what you mean, but I almost do I think lol. I actually did some looking into it and I couldn't find any examples of successfully using a generic type in a paste block of text. I read the paste source code. I guess a generic type can't be treated as an ident :s 

You think something is possible here? Also I've peeked into Michaels suggestion but not understood it yet.

**Comment by thedavidmeister** [comment]
@Connoropolous they're all different, arbitrary kinda like `fixt` if you only use the `Unpredictable` curve and is based on noise, rather than pushing for common pain points like `0` and `-1` or `u32::MAX` etc. - fixt is not arbitrary, it is targetted

contrafact is more like spec from clojure

also no i don't have a way to make a generic into an ident, i use aliases like you are, i was wondering if you had an alternative proposal for the syntax generally

**Comment by Connoropolous** [comment]
Ah ok gotcha, thanks. I will give it some thought see if anything occurs to me

**Comment by maackle** [comment]
@Connoropolous yeah, `arbitrary` is just that, an easy way to get an arbitrary value of a type. It also makes it possible to do fuzz and property testing but we haven't experimented with that yet. The docs are pretty good if that's the route you want.
