### ISSUE TITLE
`local_network_tests::conductors_remote_gossip` and `local_network_tests::conductors_remote_boot_gossip` fail

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#855]
Hi! I've been experiencing gossip issues when going through a proxy server. This has happened to me both with the proxy at `proxy.holochain.org`, and running my own with the current tip of develop.

Investigating, I ran [this](https://github.com/holochain/holochain/blob/develop/crates/holochain/src/local_network_tests.rs#L190) and [this](https://github.com/holochain/holochain/blob/develop/crates/holochain/src/local_network_tests.rs#L237) tests, and they both fail. 

This is the result of running `hc-merge-test` in develop when unignoring those tests:

```
failures:

failures:
    local_network_tests::conductors_remote_boot_gossip::_10_10_1
    local_network_tests::conductors_remote_boot_gossip::_10_10_10
    local_network_tests::conductors_remote_boot_gossip::_1_10_1
    local_network_tests::conductors_remote_boot_gossip::_1_1_1
    local_network_tests::conductors_remote_boot_gossip::_1_5_5
    local_network_tests::conductors_remote_boot_gossip::_2_1_1
    local_network_tests::conductors_remote_boot_gossip::_5_1_1
    local_network_tests::conductors_remote_boot_gossip::_5_5_5
    local_network_tests::conductors_remote_boot_gossip::_8_8_8
    local_network_tests::conductors_remote_gossip::_10_10_1
    local_network_tests::conductors_remote_gossip::_10_10_10
    local_network_tests::conductors_remote_gossip::_1_10_1
    local_network_tests::conductors_remote_gossip::_1_1_1
    local_network_tests::conductors_remote_gossip::_1_5_5
    local_network_tests::conductors_remote_gossip::_2_1_1
    local_network_tests::conductors_remote_gossip::_5_1_1
    local_network_tests::conductors_remote_gossip::_5_5_5
    local_network_tests::conductors_remote_gossip::_8_8_8

test result: FAILED. 187 passed; 18 failed; 39 ignored; 0 measured; 0 filtered out; finished in 298.70s
```

This is an example result of those failures:

```
###HOLOCHAIN_SETUP###
###ADMIN_PORT:34375###
###HOLOCHAIN_SETUP_END###
FATAL PANIC PanicInfo {
    payload: Any,
    message: Some(
        assertion failed: `None` does not match `Some(_)`,
    ),
    location: Location {
        file: "crates/holochain/src/local_network_tests.rs",
        line: 474,
        col: 9,
    },
}
thread 'main' panicked at 'assertion failed: `None` does not match `Some(_)`', crates/holochain/src/local_network_tests.rs:474:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:435:5
   2: holochain::local_network_tests::check_gossip::{{closure}}
             at ./src/local_network_tests.rs:474:9
```

**Comment by guillemcordoba** [comment]
Okey just a minute, didn't see that there were a bunch of commits merged in the last PR. Re-running the tests right now, with current tip of develop.

**Comment by guillemcordoba** [comment]
Yeap, same result with the current tip of develop!

**Comment by neonphog** [comment]
@guillemcordoba - I don't think the timing in these tests are reasonable, 600 tries at 100 ms = 1 minute max runtime on the test.

The gossip loop is the slow heal side, we have a timer to not communicate with the same node again for 1 minute. Between false positives in the bloom filter, network effects of individual data items missing the train, and bad nodes slowing down the loop, it can take 3-5 minutes for an individual agent or op to sync through the network.

In addition, we have a weak "fast push" right now that only publishes to a handful of remotes, that will hopefully be strengthened greatly as part of sharding.

In the mean time, for experimentation, you can set [the tuning param "gossip_peer_on_success_next_gossip_delay_ms"](https://github.com/holochain/holochain/blob/9e8fb9168e122dd363e7c62a54e20a9f8bb31c4b/crates/kitsune_p2p/direct_test/src/consistency_stress.rs#L570) to something shorter like 1000 ms. This will increase the network bandwidth used by holochain.

Just incase you are unaware, you can [configure tuning params in conductor config like this](https://github.com/holochain/holochain/blob/9e8fb9168e122dd363e7c62a54e20a9f8bb31c4b/crates/holochain_conductor_api/src/config/conductor.rs#L169).

**Comment by guillemcordoba** [comment]
Ohhh that timer for 1 minute might totally be the thing... Thanks, I was only trying with networks of 2 nodes. Will try again.

**Comment by guillemcordoba** [comment]
Okey that did not work for the launcher... I've tried these ones without success: 

```
            gossip_peer_on_success_next_gossip_delay_ms: 500
            gossip_peer_on_error_next_gossip_delay_ms: 2000
            tx2_implicit_timeout_ms: 60000
            default_rpc_single_timeout_ms: 60000
```

I'll keep investigating. I'm getting a bunch of these:

```
Jul 01 12:27:41.134  WARN kitsune_p2p_transport_quic::tx2: failed to establish outgoing connection (quic) err=KitsuneError(Other(TimedOut))
Jul 01 12:27:41.134  WARN kitsune_p2p::gossip::simple_bloom::step_4_com_loop_inner: failed to send outgoing: GossipTgt { agents: [KitsuneAgent(0x792c2644d1254193fcec0f8a7f24abcbda446a064d42f134f5f921f0f7bf77576c8dbf26)], cert: Cert(j78K5n..hRSDq4) } KitsuneError(Other(TimedOut))
```

and

```
Jul 01 12:27:45.589  WARN kitsune_p2p_transport_quic::tx2: failed to establish outgoing connection (quic) err=KitsuneError(Other(TimedOut))
Jul 01 12:27:45.589  WARN kitsune_p2p::spawn::actor: failure to establish proxy connection: KitsuneError(Other(TimedOut))
```

so no gossip seems to be able to finally go through.

**Comment by guillemcordoba** [comment]
@neonphog  I'm rerunning the tests again, with these configurations, which should give 10 mins for the conductors to gossip:

```rust
    const NUM_ATTEMPTS: usize = 300;
    const DELAY_PER_ATTEMPT: std::time::Duration = std::time::Duration::from_millis(2000);
```

They are all failing again, giving the same warnings that the launcher conductor gives. I'm also getting these ones, although much less frequent:

```
Jul 01 14:07:06.691  WARN kitsune_p2p::gossip::simple_bloom::step_4_com_loop_inner: failed to send outgoing: GossipTgt { agents: [KitsuneAgent(0x03ad386e18721c96db86c4455fa3ed3177a377eb925063194b625fa071d861a4a3c9896e)], cert: Cert(Vv23GL..0sw3aw) } KitsuneError(Other(OtherError("failed to find url for cert")))
Jul 01 14:07:09.320  WARN holochain_p2p::spawn::actor: (hp2p:handle) sign_network_data elapsed_s=90.009583824 byte_count=291
Jul 01 14:07:09.326  WARN holochain_p2p::spawn::actor: (hp2p:handle) fetch_op_hashes_for_constraints elapsed_s=62.699081285
Jul 01 14:07:24.208 ERROR holochain::core::workflow::incoming_dht_ops_workflow: incoming_dht_ops_workflow error err=DatabaseError(DbConnectionPoolError(Error(Some("unable to open database file: /tmp/tmp.iaHiSZYopv/holochain-test-environments.GOgawK7h3k4h/cell/Cell(uhC0kZmvAIBihiRYlJUputZhgmVVBlr8JMFmAt5SHWBDQ8GzKzpA6, uhCAk-eEbaV30T7KDISgziV4zhUE_PLf9AJoRY2ephcBZhm3ufhU7).sqlite3"))))
```

**Comment by neonphog** [comment]
@guillemcordoba - It looks like we had some tls certificate / port changes, try this one:

`kitsune-proxy://SYVd4CF3BdJ4DS7KwLLgeU3_DbHoZ34Y-qroZ79DOs8/kitsune-quic/h/proxy.holochain.org/p/5779/--`

**Comment by neonphog** [comment]
@guillemcordoba - Actually, you might want to try with a direct IP address, there's some matching logic that might not work properly with the DNS version:

`kitsune-proxy://SYVd4CF3BdJ4DS7KwLLgeU3_DbHoZ34Y-qroZ79DOs8/kitsune-quic/h/165.22.32.11/p/5779/--`

**Comment by guillemcordoba** [comment]
Okey I'll try... Although I was also using my own proxy with the same results.

**Comment by guillemcordoba** [comment]
Using that new proxy worked! I don't know what was happening before... Thanks for the support and sorry if I wasted time, I'll keep an eye on more strange behaviors along these lines.

**Comment by neonphog** [comment]
No worries @guillemcordoba - talk to us about anything any time, we want to make sure things are working :+1:

**Comment by guillemcordoba** [comment]
Closing for now.
