### ISSUE TITLE
[Tracking Issue] Support IOS

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#890]
Back in November 2020, I tried to compile Holochain for ios rust targets. It didn't work and it was because of wasmer, primarily. There could be other additional things, but wasmer seemed to be the blocker.

https://github.com/wasmerio/wasmer/issues/1832

I logged a question about ios support on the wasmer repo, and it got a couple responses, and then recently it's been filed under 'ready' and there's a bit of activity around it. 

Hopefully when something comes through there, we can see about bringing things up to date with it and thus enabling ios support for holochain. It'd be huge.

As a side note, I've gathered from a forum comment by @ddd-mtl that wasmer already is capable of compiling for Android, and that he's tried it, and that there was some networking related issue, as well as filepath handling, once he compiled Holochain for Android. Something similar might occur with ios. [forum thread about android](https://forum.holochain.org/t/holochain-on-android/1632)

**Comment by Connoropolous** [comment]
Tagging you @artbrock for awareness

**Comment by yasharpm** [comment]
I am also looking for holochain for Android. It will open up an ocean of use cases. I already have 3 in my mind I need for my projects. Any updates on when it can happen? Can I give a hand? Specially if there is a grant available for it.

**Comment by f13end** [comment]
https://wasmer.io/posts/wasmer-2.1

https://github.com/holzschu/a-shell/tree/373793652d124e96f070c4ddf182790063d4b13f#a-shell-a-terminal-for-ios-with-multiple-windows
