### ISSUE TITLE
How to generate the docs and run tests

### ISSUE THREAD

**Issue by mjbrisebois** [holochain/holochain#9]
A `CONTRIBUTOR.md` with a tool list and minimal command-line examples would be enough to get me going.

Even to someone who knows rust, it is not always obvious whether the tests are just `cargo test` or something else such as `hc test`.  Seemingly simple documentation can add a lot of determinism to someone's mental model.

**Comment by ThetaSinner** [comment]
I believe this is resolved. Please feel free to open a new issue if there is anything missing
