### ISSUE TITLE
Is this `to_ownded` cloning the entry? I don't think that's needed is it?

### ISSUE THREAD

**Issue by freesig** [holochain/holochain#910]
Is this `to_ownded` cloning the entry? I don't think that's needed is it?

_Originally posted by @freesig in https://github.com/holochain/holochain/pull/895#discussion_r684886506_

**Comment by maackle** [comment]
Looks like there is no clone anymore https://github.com/holochain/holochain/blob/78fef7e8088ed5741f2ad9b67c7ef690122b7ed1/crates/holochain/src/core/ribosome/host_fn/create.rs#L24
