### ISSUE TITLE
Implement mechanisms for custom validation of zome & DNA properties

### ISSUE THREAD

**Issue by pospi** [holochain/holochain#976]
> (A solution for #909 should be implemented before proceeding with this enhancement.)

Further to [this comment](https://github.com/holochain/holochain/issues/743#issuecomment-847522767), my understanding is that DNA properties validation is being actively discussed by Holochain core team (ping @zippy @thedavidmeister @freesig @guillemcordoba). I wanted to weigh in with what seems like an elegant solution to this feature request which can hopefully service a few needs besides my own.

As the linked comment illustrates, it would be beneficial for application correctness guarantees if zome developers were able to enforce constraints on the configuration of a DNA. This could be done relatively easily with the addition of a new `hdk_extern` (call it `validate_properties` for the sake of discussion) which accepts any struct(s) implementing `TryFrom<SerializedBytes>`.

The extern would be triggered by the `hc` utility when running both `dna pack` and `app pack`, and cause it to abort and print any returned error if misconfigured. I am unclear on whether other runtime checks would be needed when executing within the conductor or if this would be sufficient.

Means of implementing such validation should be fairly simple for the zome developer:

- For simple validation, the type defined as the function input would handle any decoding and throw a serialization error if the properties are malformed. All the zome author would need to do is provide the appropriate type and return `Ok(())`.
- For more complex validation logic, the zome author could perform any additional checks within the body of the method and return some `Err()` as needed.
- Since such validation logic might require a lot of reflection as to the current state of the DNA, we should leverage existing introspection methods wherever possible. (For example, being able to check that the value of a property corresponds to the name of another zome that is included in the DNA bundle.) If `hdk::dna_info()`, `hdk::zome_info()` etc are not already able to function in the "bundling" phase of an hApp's lifecycle, perhaps they could be made to do so? This feels like the best approach, since it means that any necessary improvements to the reflective capabilities of Holochain can be scoped and logged as separate improvements.

**Comment by maackle** [comment]
This sounds like a good idea. Perhaps we can incorporate this into existing validation (e.g. adding DnaDef [here](https://github.com/holochain/holochain/blob/91ddd04c9422c9511120925a85cc8da9a123f08e/crates/holochain_integrity_types/src/op.rs#L640-L647)) instead of creating a new callback, and then running normal validation for the Dna during bundling.

**Comment by mattyg** [comment]
I believe this can be implemented by calling `dna_info()` within the validate callback when validating `OpRecord:Dna` or `Action::AgentValidationPkg`.

Closing this as complete. If anyone thinks there is still work needed for this, feel free to reopen with a comment.
