### ISSUE TITLE
Misleading error when not running lair-keystore

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#990]
This error:

![image](https://user-images.githubusercontent.com/2046932/134044476-3938a3cc-2efd-4ebf-a713-8073ad5a4ea1.png)

is really confusing to a lot of people that think they are missing something in their setup, and that things have failed and are not working properly. It is also very usual, all developers are going to see this in one point or another.

I think it would be better to just put out a warning, explaining that holochain is defaulting to running the lair-keystore itself.

**Comment by Connoropolous** [comment]
agree agree

**Comment by neonphog** [comment]
The intention is to delete this whole lair_keystore_client concept with the new lair api, providing the following options:
- external lair that will error if it is not already running
- in-process lair that doesn't depend on another process, but requires exclusive access to the store file
- or in-process in-memory test keystore

**Comment by Connoropolous** [comment]
@neonphog we haven't quite got there yet with this have we? what's the status on the in-process lair?

also "requires exclusive access to the store file". Does this mean the current lair-keystore process can handle multiple holochain processes connecting to it, and using it for signing?

**Comment by Connoropolous** [comment]
devs are still having 'misleading' difficulties with this reported error

**Comment by neonphog** [comment]
@Connoropolous - steps needed for this:

- delete the legacy lair dependency (i think we recently found some (tryorama?) code that was using legacy lair?)
- make db encryption the default on everything except windows (our rusqlite dependency doesn't yet support sqlcipher windows)

it's mostly just a question of priority at this point

**Comment by ThetaSinner** [comment]
@guillemcordoba @neonphog Has this work been done now? If not, what is left that needs to be tackled?

**Comment by neonphog** [comment]
@ThetaSinner - Yeah the client has been removed, this should no longer be relevant.
